// ============================================================
// generate-world.ts — builds src/data/worldPaths.ts
//
// REBUILD §7.1: the Explore map uses BUNDLED country shapes — no
// tile server, no API key, works offline in Electron. Source:
// world-atlas TopoJSON (Natural Earth 110m, committed npm data),
// projected once at build time to plain SVG path strings.
//
// ISO numeric (ccn3) -> ISO alpha-2 mapping via world-countries;
// every data country without a shape at 110m resolution (small
// states) is reported so the country grid can cover it.
//
// Run: npx tsx scripts/generate-world.ts
// ============================================================

import fs from "node:fs";
import path from "node:path";
import { feature } from "topojson-client";
import { geoNaturalEarth1, geoPath } from "d3-geo";
import type { Topology, GeometryCollection } from "topojson-specification";
import wc from "world-countries";
import { TERMINALS } from "../src/data/destinations";
import { europeCarriers } from "../src/data/carriers";

const ROOT = process.cwd();
const SRC = path.join(ROOT, "node_modules", "world-atlas", "countries-110m.json");
const OUT = path.join(ROOT, "src", "data", "worldPaths.ts");

const W = 1000;
const H = 500;

interface Shape {
  cc: string;
  name: string;
  d: string;
}

interface WcEntry {
  cca2: string;
  ccn3?: string;
  name: { common: string };
}

function fail(msg: string): never {
  console.error(`generate-world: ${msg}`);
  process.exit(1);
}

function main() {
  if (!fs.existsSync(SRC)) fail(`missing ${SRC} — npm install first`);

  const list = wc as unknown as WcEntry[];
  const numToCc = new Map<string, string>();
  const ccName = new Map<string, string>();
  for (const c of list) {
    ccName.set(c.cca2, c.name.common);
    if (c.ccn3) numToCc.set(String(Number(c.ccn3)), c.cca2);
  }
  if (numToCc.size < 200) fail(`only ${numToCc.size} ccn3 mappings`);

  const topo = JSON.parse(fs.readFileSync(SRC, "utf8")) as Topology;
  const gc = topo.objects.countries as GeometryCollection;
  const geo = feature(topo, gc) as unknown as GeoJSON.FeatureCollection<
    GeoJSON.Polygon | GeoJSON.MultiPolygon
  >;

  const projection = geoNaturalEarth1().fitExtent(
    [
      [4, 4],
      [W - 4, H - 4],
    ],
    geo
  );
  const pathGen = geoPath(projection);

  const shapes: Shape[] = [];
  const unmappedFeatures: string[] = [];
  const seenCc = new Set<string>();

  for (const f of geo.features) {
    const rawId = String(f.id ?? "");
    const cc = numToCc.get(String(Number(rawId)));
    const name = (cc && ccName.get(cc)) || f.properties?.name || rawId;
    const d = pathGen(f);
    if (!d) continue;
    if (!cc) {
      unmappedFeatures.push(`${rawId}:${name}`);
      continue;
    }
    if (seenCc.has(cc)) continue;
    seenCc.add(cc);
    // Round to 1 decimal — visually identical, much smaller source.
    shapes.push({ cc, name, d: d.replace(/(-?\d+\.\d+)\d+/g, "$1") });
  }
  shapes.sort((a, b) => a.cc.localeCompare(b.cc));

  if (shapes.length < 150) fail(`only ${shapes.length} shapes — projection/mapping broken`);
  for (const s of shapes) {
    if (!s.d.startsWith("M")) fail(`bad path for ${s.cc}`);
    if (!/^[A-Z]{2}$/.test(s.cc)) fail(`bad cc "${s.cc}"`);
  }

  // Data countries = terminal records + carrier countries; each must
  // either have a shape or be reported for the grid fallback.
  const dataCc = new Set<string>();
  for (const t of TERMINALS) dataCc.add(t.countryCode);
  for (const c of europeCarriers) dataCc.add(c.code);
  const noShape = [...dataCc].filter((cc) => !seenCc.has(cc)).sort();

  const out = `/* ============================================================
 * AUTO-GENERATED by scripts/generate-world.ts — DO NOT EDIT.
 * Source: world-atlas countries-110m (Natural Earth), bundled at
 * build time — no tile server, no API key, offline-safe (§7.1).
 * Shapes: ${shapes.length} (ISO alpha-2), viewBox ${W}x${H}
 * Data countries without a 110m shape (grid fallback): ${
    noShape.length ? noShape.join(", ") : "none"
  }
 * ============================================================ */

export interface WorldShape {
  cc: string;
  name: string;
  d: string;
}

export const WORLD_VIEWBOX = "0 0 ${W} ${H}";

export const WORLD_SHAPES: WorldShape[] = ${JSON.stringify(shapes)};

export const WORLD_SHAPE_STATS = {
  shapes: ${shapes.length},
  dataCountries: ${dataCc.size},
  dataWithoutShape: ${JSON.stringify(noShape)},
  unmappedFeatures: ${JSON.stringify(unmappedFeatures)},
  generatedAt: ${JSON.stringify(new Date().toISOString())},
} as const;
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out, "utf8");
  console.log("generate-world: OK");
  console.log(`  shapes: ${shapes.length} | data countries: ${dataCc.size}`);
  console.log(
    `  data countries without 110m shape: ${noShape.length ? noShape.join(", ") : "none"}`
  );
  if (unmappedFeatures.length) console.log(`  unmapped features: ${unmappedFeatures.join(", ")}`);
  console.log(`  output: ${path.relative(ROOT, OUT)} (${(fs.statSync(OUT).size / 1024).toFixed(0)} KB)`);
}

main();
