"use client";

// Trip builder (REBUILD Phase 4): add / reorder / remove itinerary
// items, persisted locally, exported as JSON or Markdown.
//
// Pricing honesty §5.1.7: every price shown here was TYPED BY THE
// USER ("entered by you") — wrapped in [data-user-price] so the
// honesty gate can tell user bookings apart from live quotes. The
// app never invents a figure; no prices entered = no totals.

import { useState } from "react";
import { Download, FileJson, FileText, Luggage, Plus, Trash2, ChevronUp, ChevronDown } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { useSettings } from "@/lib/store/settings";
import { formatPrice } from "@/data/currencies";
import {
  tripTotals,
  useTrips,
  type Trip,
  type TripItemKind,
} from "@/lib/store/trips";

const KINDS: Array<{ id: TripItemKind; label: string }> = [
  { id: "transport", label: "Transport" },
  { id: "stay", label: "Stay" },
  { id: "activity", label: "Activity" },
  { id: "note", label: "Note" },
];

function exportJson(trip: Trip): string {
  return JSON.stringify(
    {
      app: "AllinOne Travel",
      exportedAt: new Date().toISOString(),
      note: "All prices in this file were entered by the user — the app never generates prices.",
      trip,
    },
    null,
    2
  );
}

function exportMarkdown(trip: Trip): string {
  const lines: string[] = [`# ${trip.name}`, ""];
  if (trip.startDate || trip.endDate) {
    lines.push(`**Dates:** ${trip.startDate ?? "?"} → ${trip.endDate ?? "?"}`, "");
  }
  if (trip.items.length === 0) lines.push("_No items yet._", "");
  trip.items.forEach((item, i) => {
    const bits = [item.date, item.from && item.to ? `${item.from} → ${item.to}` : (item.from ?? item.to)]
      .filter(Boolean)
      .join(" · ");
    lines.push(`${i + 1}. **${item.title}** (${item.kind})${bits ? ` — ${bits}` : ""}`);
    if (typeof item.price === "number") {
      lines.push(`   - price entered by you: ${formatPrice(item.price, item.currency || "EUR")}`);
    }
    if (item.notes) lines.push(`   - ${item.notes}`);
  });
  const totals = tripTotals(trip);
  if (totals.length > 0) {
    lines.push("", "## Totals (entered by you)");
    for (const t of totals) {
      lines.push(`- ${formatPrice(t.total, t.currency)} — sum of ${t.count} price(s) you entered, ${t.currency}`);
    }
  }
  lines.push("", "_Generated by AllinOne Travel — prices are user-entered, never app-generated._");
  return lines.join("\n");
}

function download(filename: string, text: string) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 5000);
}

export function TripsScreen() {
  const { currency } = useSettings();
  const {
    trips,
    activeId,
    addTrip,
    removeTrip,
    setActive,
    updateTrip,
    addItem,
    removeItem,
    moveItem,
  } = useTrips();

  const [newName, setNewName] = useState("");
  const [form, setForm] = useState({
    kind: "transport" as TripItemKind,
    title: "",
    date: "",
    from: "",
    to: "",
    price: "",
    notes: "",
  });
  const [exportText, setExportText] = useState<{ format: string; filename: string; text: string } | null>(null);

  const active = trips.find((t) => t.id === activeId) ?? null;
  const totals = active ? tripTotals(active) : [];

  function createTrip(e: React.FormEvent) {
    e.preventDefault();
    if (!newName.trim()) return;
    addTrip(newName);
    setNewName("");
  }

  function addItemForm(e: React.FormEvent) {
    e.preventDefault();
    if (!active || !form.title.trim()) return;
    const priceNum = form.price.trim() === "" ? undefined : Number(form.price.replace(",", "."));
    addItem(active.id, {
      kind: form.kind,
      title: form.title.trim(),
      date: form.date || undefined,
      from: form.from.trim() || undefined,
      to: form.to.trim() || undefined,
      price: priceNum !== undefined && Number.isFinite(priceNum) ? priceNum : undefined,
      currency: form.price.trim() === "" ? undefined : currency,
      notes: form.notes.trim() || undefined,
    });
    setForm({ ...form, title: "", date: "", from: "", to: "", price: "", notes: "" });
  }

  function showExport(format: "json" | "markdown") {
    if (!active) return;
    const text = format === "json" ? exportJson(active) : exportMarkdown(active);
    const slug = active.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "trip";
    setExportText({
      format,
      filename: `${slug}.${format === "json" ? "json" : "md"}`,
      text,
    });
  }

  return (
    <div className="animate-fade-up space-y-5" data-testid="trips-page">
      <div className="flex items-center gap-3">
        <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent/15 text-accent">
          <Luggage size={22} />
        </span>
        <div>
          <h1 className="font-display text-3xl font-extrabold tracking-tight">Trips</h1>
          <p className="text-sm text-fg-muted">
            Your itinerary — built by you, priced only by you. Stored on this device.
          </p>
        </div>
        <Badge className="ml-auto">
          Local only · no account
        </Badge>
      </div>

      {/* ---------- create ---------- */}
      <Card className="p-4">
        <form onSubmit={createTrip} className="flex flex-wrap items-end gap-3">
          <label className="min-w-[240px] flex-1">
            <span className="mb-1.5 block text-xs font-semibold text-fg-muted">New trip</span>
            <Input
              data-testid="trip-create-input"
              placeholder="e.g. Iceland ring road"
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
            />
          </label>
          <Button type="submit" data-testid="trip-create" disabled={!newName.trim()}>
            <Plus size={14} />
            Create trip
          </Button>
        </form>
      </Card>

      {trips.length === 0 ? (
        <Card className="p-6" data-testid="trips-empty">
          <p className="font-display text-lg font-bold">No trips yet</p>
          <p className="mt-1 text-sm text-fg-muted">
            Create a trip above, then add legs — flights you booked, trains, hotels —
            and enter what you actually paid. Totals only ever add prices you typed.
          </p>
        </Card>
      ) : (
        <div className="grid gap-4 lg:grid-cols-[minmax(0,3fr)_minmax(0,2fr)]">
          {/* ---------- active trip ---------- */}
          <div className="space-y-4">
            {active ? (
              <Card className="space-y-5 p-5" data-testid="trip-detail">
                <div className="flex flex-wrap items-center gap-3">
                  <h2 className="font-display text-2xl font-extrabold tracking-tight" data-testid="trip-name">
                    {active.name}
                  </h2>
                  <Badge tone="neutral">
                    {active.items.length} item{active.items.length === 1 ? "" : "s"}
                  </Badge>
                  <span className="ml-auto flex items-center gap-2 text-xs text-fg-muted">
                    <label htmlFor="trip-start">From</label>
                    <input
                      id="trip-start"
                      type="date"
                      data-testid="trip-start"
                      value={active.startDate ?? ""}
                      onChange={(e) => updateTrip(active.id, { startDate: e.target.value || undefined })}
                      className="h-8 rounded-lg border bg-raised px-2 text-xs text-fg focus:border-accent focus:outline-none"
                    />
                    <label htmlFor="trip-end">to</label>
                    <input
                      id="trip-end"
                      type="date"
                      data-testid="trip-end"
                      value={active.endDate ?? ""}
                      onChange={(e) => updateTrip(active.id, { endDate: e.target.value || undefined })}
                      className="h-8 rounded-lg border bg-raised px-2 text-xs text-fg focus:border-accent focus:outline-none"
                    />
                  </span>
                </div>

                {/* ---------- items ---------- */}
                {active.items.length === 0 ? (
                  <p className="text-sm text-fg-muted" data-testid="trip-items-empty">
                    Nothing added yet — use the form below.
                  </p>
                ) : (
                  <ol className="space-y-2" data-testid="trip-items">
                    {active.items.map((item, i) => (
                      <li
                        key={item.id}
                        data-testid="trip-item"
                        data-index={i}
                        data-kind={item.kind}
                        className="flex flex-wrap items-center gap-2 rounded-xl border bg-raised p-3"
                      >
                        <Badge tone="neutral">{item.kind}</Badge>
                        <span className="text-sm font-semibold text-fg" data-testid="trip-item-title">
                          {item.title}
                        </span>
                        <span className="text-xs text-fg-muted">
                          {[item.date, item.from && item.to ? `${item.from} → ${item.to}` : (item.from ?? item.to)]
                            .filter(Boolean)
                            .join(" · ")}
                        </span>
                        {typeof item.price === "number" && (
                          <span
                            data-user-price
                            className="inline-flex items-center gap-1.5 rounded-lg bg-muted px-2 py-0.5 text-xs font-bold tabular-nums text-fg"
                          >
                            <span>{formatPrice(item.price, item.currency || currency)}</span>
                            <span className="text-[10px] font-semibold uppercase tracking-wide text-fg-subtle">
                              Entered by you
                            </span>
                          </span>
                        )}
                        <span className="ml-auto flex items-center gap-1">
                          <button
                            type="button"
                            aria-label={`Move ${item.title} up`}
                            data-testid="trip-item-up"
                            disabled={i === 0}
                            onClick={() => moveItem(active.id, item.id, -1)}
                            className="rounded-lg border p-1.5 text-fg-muted transition-colors hover:border-accent hover:text-fg disabled:opacity-35"
                          >
                            <ChevronUp size={13} />
                          </button>
                          <button
                            type="button"
                            aria-label={`Move ${item.title} down`}
                            data-testid="trip-item-down"
                            disabled={i === active.items.length - 1}
                            onClick={() => moveItem(active.id, item.id, 1)}
                            className="rounded-lg border p-1.5 text-fg-muted transition-colors hover:border-accent hover:text-fg disabled:opacity-35"
                          >
                            <ChevronDown size={13} />
                          </button>
                          <button
                            type="button"
                            aria-label={`Remove ${item.title}`}
                            data-testid="trip-item-remove"
                            onClick={() => removeItem(active.id, item.id)}
                            className="rounded-lg border p-1.5 text-fg-muted transition-colors hover:border-warn hover:text-warn"
                          >
                            <Trash2 size={13} />
                          </button>
                        </span>
                      </li>
                    ))}
                  </ol>
                )}

                {/* ---------- totals (user-entered only) ---------- */}
                <div className="rounded-xl border border-dashed p-3" data-testid="trip-totals">
                  {totals.length === 0 ? (
                    <p className="text-xs text-fg-muted" data-testid="totals-empty">
                      No prices entered yet — a total appears only once you type
                      what you actually paid. We never estimate costs.
                    </p>
                  ) : (
                    <div className="flex flex-wrap items-center gap-3">
                      {totals.map((t) => (
                        <span
                          key={t.currency}
                          data-user-price
                          data-testid="trip-total"
                          className="inline-flex items-center gap-2 rounded-lg bg-muted px-2.5 py-1"
                        >
                          <strong className="text-sm tabular-nums text-fg">
                            {formatPrice(t.total, t.currency)}
                          </strong>
                          <span className="text-[10px] font-semibold uppercase tracking-wide text-fg-subtle">
                            Entered by you
                          </span>
                          <span className="text-[10px] text-fg-subtle">
                            sum of {t.count} price{t.count === 1 ? "" : "s"} you typed
                          </span>
                        </span>
                      ))}
                      {totals.length > 1 && (
                        <span className="text-[11px] text-fg-muted">
                          Mixed currencies — not converted (we don&apos;t invent rates).
                        </span>
                      )}
                    </div>
                  )}
                </div>

                {/* ---------- add item ---------- */}
                <form onSubmit={addItemForm} className="space-y-3 rounded-xl border bg-surface/50 p-4" data-testid="item-add-form">
                  <p className="text-xs font-semibold uppercase tracking-wide text-fg-subtle">
                    Add to {active.name}
                  </p>
                  <div className="grid gap-3 sm:grid-cols-2">
                    <label className="text-xs font-semibold text-fg-muted">
                      Type
                      <select
                        data-testid="item-kind"
                        value={form.kind}
                        onChange={(e) => setForm({ ...form, kind: e.target.value as TripItemKind })}
                        className="mt-1.5 h-10 w-full rounded-xl border bg-raised px-3 text-sm text-fg focus:border-accent focus:outline-none"
                      >
                        {KINDS.map((k) => (
                          <option key={k.id} value={k.id}>
                            {k.label}
                          </option>
                        ))}
                      </select>
                    </label>
                    <label className="text-xs font-semibold text-fg-muted">
                      Title <span className="text-fg-subtle">(required)</span>
                      <Input
                        data-testid="item-title"
                        className="mt-1.5"
                        placeholder="e.g. Berlin → Keflavik flight"
                        value={form.title}
                        onChange={(e) => setForm({ ...form, title: e.target.value })}
                      />
                    </label>
                    <label className="text-xs font-semibold text-fg-muted">
                      Date
                      <Input
                        data-testid="item-date"
                        type="date"
                        className="mt-1.5"
                        value={form.date}
                        onChange={(e) => setForm({ ...form, date: e.target.value })}
                      />
                    </label>
                    <div className="grid grid-cols-2 gap-2">
                      <label className="text-xs font-semibold text-fg-muted">
                        From
                        <Input
                          data-testid="item-from"
                          className="mt-1.5"
                          placeholder="Berlin"
                          value={form.from}
                          onChange={(e) => setForm({ ...form, from: e.target.value })}
                        />
                      </label>
                      <label className="text-xs font-semibold text-fg-muted">
                        To
                        <Input
                          data-testid="item-to"
                          className="mt-1.5"
                          placeholder="Keflavik"
                          value={form.to}
                          onChange={(e) => setForm({ ...form, to: e.target.value })}
                        />
                      </label>
                    </div>
                    <label className="text-xs font-semibold text-fg-muted">
                      Price you paid <span className="text-fg-subtle">({currency} — optional)</span>
                      <Input
                        data-testid="item-price"
                        type="text"
                        inputMode="decimal"
                        className="mt-1.5"
                        placeholder="only what YOU paid"
                        value={form.price}
                        onChange={(e) => setForm({ ...form, price: e.target.value })}
                      />
                      <span className="mt-1 block text-[10px] font-normal text-fg-subtle">
                        Entered by you — never suggested, estimated or compared.
                      </span>
                    </label>
                    <label className="text-xs font-semibold text-fg-muted">
                      Notes
                      <Input
                        data-testid="item-notes"
                        className="mt-1.5"
                        placeholder="confirmation, seat, room…"
                        value={form.notes}
                        onChange={(e) => setForm({ ...form, notes: e.target.value })}
                      />
                    </label>
                  </div>
                  <Button type="submit" data-testid="item-add" disabled={!form.title.trim()}>
                    <Plus size={14} />
                    Add item
                  </Button>
                </form>

                {/* ---------- export ---------- */}
                <div className="flex flex-wrap items-center gap-2 border-t pt-4">
                  <span className="text-xs font-semibold uppercase tracking-wide text-fg-subtle">
                    Export
                  </span>
                  <Button variant="outline" size="sm" data-testid="export-json" onClick={() => showExport("json")}>
                    <FileJson size={13} />
                    JSON
                  </Button>
                  <Button variant="outline" size="sm" data-testid="export-markdown" onClick={() => showExport("markdown")}>
                    <FileText size={13} />
                    Markdown
                  </Button>
                  {exportText && (
                    <Button
                      variant="ghost"
                      size="sm"
                      data-testid="export-close"
                      onClick={() => setExportText(null)}
                    >
                      Close preview
                    </Button>
                  )}
                </div>

                {exportText && (
                  <div className="space-y-2" data-testid="export-preview" data-format={exportText.format}>
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge tone="accent">{exportText.filename}</Badge>
                      <button
                        type="button"
                        data-testid="export-download"
                        onClick={() => download(exportText.filename, exportText.text)}
                        className="inline-flex items-center gap-1.5 text-xs font-semibold text-accent hover:underline"
                      >
                        <Download size={12} />
                        Download {exportText.filename}
                      </button>
                    </div>
                    <pre className="max-h-72 overflow-auto whitespace-pre-wrap rounded-xl border bg-raised p-3 text-[11px] leading-relaxed text-fg-muted">
                      {exportText.text}
                    </pre>
                  </div>
                )}
              </Card>
            ) : (
              <Card className="p-6" data-testid="trip-select-prompt">
                <p className="text-sm text-fg-muted">Select a trip from the list.</p>
              </Card>
            )}
          </div>

          {/* ---------- trip list ---------- */}
          <Card className="h-fit space-y-3 p-4">
            <p className="text-xs font-semibold uppercase tracking-wide text-fg-subtle">
              Your trips ({trips.length})
            </p>
            <ul className="space-y-2" data-testid="trips-list">
              {trips.map((t) => (
                <li
                  key={t.id}
                  data-testid="trip-card"
                  data-selected={t.id === activeId ? "1" : "0"}
                  className={`flex items-center gap-2 rounded-xl border p-3 ${
                    t.id === activeId ? "border-accent bg-accent/10" : "bg-raised"
                  }`}
                >
                  <button
                    type="button"
                    data-testid="trip-select"
                    onClick={() => setActive(t.id)}
                    className="min-w-0 flex-1 text-left"
                  >
                    <span className="block truncate text-sm font-semibold text-fg">{t.name}</span>
                    <span className="block text-[11px] text-fg-subtle">
                      {t.items.length} item{t.items.length === 1 ? "" : "s"}
                    </span>
                  </button>
                  <button
                    type="button"
                    aria-label={`Delete ${t.name}`}
                    data-testid="trip-delete"
                    onClick={() => removeTrip(t.id)}
                    className="rounded-lg border p-1.5 text-fg-muted transition-colors hover:border-warn hover:text-warn"
                  >
                    <Trash2 size={13} />
                  </button>
                </li>
              ))}
            </ul>
          </Card>
        </div>
      )}
    </div>
  );
}
