// ============================================================
// FreeBuff Travel — Norway (NO) destination entries
// Converted from: TravelApp_Norway.pdf
// NOTE: Coastal Express (Hurtigruten + Havila Kystruten) runs
// Bergen–Kirkenes year-round along 34 ports. Rail operators:
// Vy (Bergensbanen/Dovrebanen/Sørlandsbanen), SJ Nord (Nordlandsbanen).
// ============================================================

// ---------- Paste into AIRPORTS (category: "air") ----------

  { id: "osl", name: "Oslo Gardermoen Airport", displayName: "Oslo (OSL)", country: "NO", countryCode: "NO", category: "air", city: "Oslo", iata: "OSL", timezone: "Europe/Oslo", tags: ["major-hub", "avinor", "sas", "norwegian", "rail-connected"] },
  { id: "trf", name: "Oslo Sandefjord Torp Airport", displayName: "Sandefjord (TRF)", country: "NO", countryCode: "NO", category: "air", city: "Sandefjord", iata: "TRF", timezone: "Europe/Oslo", tags: ["low-cost-hub", "ryanair", "wizz-air", "oslo-secondary", "vestfold"] },
  { id: "ryg", name: "Oslo Moss Rygge Airport", displayName: "Moss Rygge (RYG)", country: "NO", countryCode: "NO", category: "air", city: "Moss", iata: "RYG", timezone: "Europe/Oslo", tags: ["closed-civilian", "military-use", "former-low-cost-hub", "historical"] },
  { id: "krs", name: "Kristiansand Kjevik Airport", displayName: "Kristiansand (KRS)", country: "NO", countryCode: "NO", category: "air", city: "Kristiansand", iata: "KRS", timezone: "Europe/Oslo", tags: ["sorlandet", "denmark-ferry-connection", "sas", "norwegian", "wideroe"] },
  { id: "bgo", name: "Bergen Flesland Airport", displayName: "Bergen (BGO)", country: "NO", countryCode: "NO", category: "air", city: "Bergen", iata: "BGO", timezone: "Europe/Oslo", tags: ["second-busiest", "avinor", "west-norway-hub", "fjord-gateway", "rail-connected"] },
  { id: "svg", name: "Stavanger Sola Airport", displayName: "Stavanger (SVG)", country: "NO", countryCode: "NO", category: "air", city: "Stavanger", iata: "SVG", timezone: "Europe/Oslo", tags: ["oil-capital", "international-charter", "sas", "norwegian"] },
  { id: "hau", name: "Haugesund Karmøy Airport", displayName: "Haugesund (HAU)", country: "NO", countryCode: "NO", category: "air", city: "Haugesund", iata: "HAU", timezone: "Europe/Oslo", tags: ["rogaland", "charter", "viking-history", "ryanair"] },
  { id: "aes", name: "Ålesund Vigra Airport", displayName: "Ålesund (AES)", country: "NO", countryCode: "NO", category: "air", city: "Ålesund", iata: "AES", timezone: "Europe/Oslo", tags: ["more-romsdal", "art-nouveau-city", "geiranger-access", "german-charter"] },
  { id: "mol", name: "Molde Ørø Airport", displayName: "Molde (MOL)", country: "NO", countryCode: "NO", category: "air", city: "Molde", iata: "MOL", timezone: "Europe/Oslo", tags: ["city-of-roses", "jazz-festival", "atlantic-road-access", "regional"] },
  { id: "ksu", name: "Kristiansund Kvernberget Airport", displayName: "Kristiansund (KSU)", country: "NO", countryCode: "NO", category: "air", city: "Kristiansund", iata: "KSU", timezone: "Europe/Oslo", tags: ["møre-romsdal", "oil-region", "regional", "wideroe"] },
  { id: "fro", name: "Florø Airport", displayName: "Florø (FRO)", country: "NO", countryCode: "NO", category: "air", city: "Florø", iata: "FRO", timezone: "Europe/Oslo", tags: ["sogn", "coastal-town", "wideroe-regional", "oil"] },
  { id: "sog", name: "Sogndal Haukåsen Airport", displayName: "Sogndal (SOG)", country: "NO", countryCode: "NO", category: "air", city: "Sogndal", iata: "SOG", timezone: "Europe/Oslo", tags: ["sognefjord", "fjord-access", "wideroe", "winter-tourism"] },
  { id: "sdn", name: "Sandane Anda Airport", displayName: "Sandane (SDN)", country: "NO", countryCode: "NO", category: "air", city: "Sandane", iata: "SDN", timezone: "Europe/Oslo", tags: ["gloppen", "nordfjord", "wideroe-short-runway"] },
  { id: "fde", name: "Førde Bringeland Airport", displayName: "Førde (FDE)", country: "NO", countryCode: "NO", category: "air", city: "Førde", iata: "FDE", timezone: "Europe/Oslo", tags: ["sogn-fjordane", "regional", "wideroe"] },
  { id: "hov", name: "Ørsta-Volda Hovden Airport", displayName: "Ørsta-Volda (HOV)", country: "NO", countryCode: "NO", category: "air", city: "Ørsta", iata: "HOV", timezone: "Europe/Oslo", tags: ["sunmore", "fjord-mountain", "wideroe", "ski-tourism"] },
  { id: "srp", name: "Stord Sørstokken Airport", displayName: "Stord (SRP)", country: "NO", countryCode: "NO", category: "air", city: "Stord", iata: "SRP", timezone: "Europe/Oslo", tags: ["haugaland", "limited-schedule", "regional"] },
  { id: "trd", name: "Trondheim Værnes Airport", displayName: "Trondheim (TRD)", country: "NO", countryCode: "NO", category: "air", city: "Trondheim", iata: "TRD", timezone: "Europe/Oslo", tags: ["third-busiest", "trondelag", "nidelva", "rail-connected", "military-shared"] },
  { id: "rrs", name: "Røros Airport", displayName: "Røros (RRS)", country: "NO", countryCode: "NO", category: "air", city: "Røros", iata: "RRS", timezone: "Europe/Oslo", tags: ["mining-town-unesco", "winter-charter", "regional", "stockholm-arlanda-seasonal"] },
  { id: "osy", name: "Namsos Airport", displayName: "Namsos (OSY)", country: "NO", countryCode: "NO", category: "air", city: "Namsos", iata: "OSY", timezone: "Europe/Oslo", tags: ["trondelag-coast", "regional", "wideroe"] },
  { id: "rvk", name: "Rørvik Ryumsjøen Airport", displayName: "Rørvik (RVK)", country: "NO", countryCode: "NO", category: "air", city: "Rørvik", iata: "RVK", timezone: "Europe/Oslo", tags: ["ytre-namdal", "coastal", "wideroe"] },
  { id: "boo", name: "Bodø Airport", displayName: "Bodø (BOO)", country: "NO", countryCode: "NO", category: "air", city: "Bodø", iata: "BOO", timezone: "Europe/Oslo", tags: ["nordland-gateway", "city-center-1km", "lofoten-hub", "wideroe", "military-nato", "rail-terminus"] },
  { id: "mqn", name: "Mo i Rana Røssvoll Airport", displayName: "Mo i Rana (MQN)", country: "NO", countryCode: "NO", category: "air", city: "Mo i Rana", iata: "MQN", timezone: "Europe/Oslo", tags: ["helgeland", "polar-circle-adjacent", "regional", "wideroe"] },
  { id: "ssj", name: "Sandnessjøen Stokka Airport", displayName: "Sandnessjøen (SSJ)", country: "NO", countryCode: "NO", category: "air", city: "Sandnessjøen", iata: "SSJ", timezone: "Europe/Oslo", tags: ["helgeland", "seven-sisters-access", "regional", "wideroe"] },
  { id: "bnn", name: "Brønnøysund Brønnøy Airport", displayName: "Brønnøysund (BNN)", country: "NO", countryCode: "NO", category: "air", city: "Brønnøysund", iata: "BNN", timezone: "Europe/Oslo", tags: ["helgeland-coast", "torgensen-bridge", "regional", "wideroe"] },
  { id: "lkn", name: "Leknes Airport", displayName: "Leknes (LKN)", country: "NO", countryCode: "NO", category: "air", city: "Leknes", iata: "LKN", timezone: "Europe/Oslo", tags: ["lofoten", "wideroe-short-haul", "midnight-sun", "beaches"] },
  { id: "svj", name: "Svolvær Helle Airport", displayName: "Svolvær (SVJ)", country: "NO", countryCode: "NO", category: "air", city: "Svolvær", iata: "SVJ", timezone: "Europe/Oslo", tags: ["lofoten-capital", "wideroe", "hurtigruten-port", "tourism"] },
  { id: "skn", name: "Stokmarknes Skagen Airport", displayName: "Stokmarknes (SKN)", country: "NO", countryCode: "NO", category: "air", city: "Stokmarknes", iata: "SKN", timezone: "Europe/Oslo", tags: ["vesteralen", "hurtigruten-birthplace-museum", "wideroe"] },
  { id: "ret", name: "Røst Airport", displayName: "Røst (RET)", country: "NO", countryCode: "NO", category: "air", city: "Røst", iata: "RET", timezone: "Europe/Oslo", tags: ["lofoten-outer", "extreme-weather-cancellations", "wideroe", "birding"] },
  { id: "nvk", name: "Narvik Framnes Airport", displayName: "Narvik (NVK)", country: "NO", countryCode: "NO", category: "air", city: "Narvik", iata: "NVK", timezone: "Europe/Oslo", tags: ["very-limited", "seasonal", "region-uses-eve", "small-airfield"] },
  { id: "tos", name: "Tromsø Langnes Airport", displayName: "Tromsø (TOS)", country: "NO", countryCode: "NO", category: "air", city: "Tromsø", iata: "TOS", timezone: "Europe/Oslo", tags: ["arctic-capital-hub", "northern-norway", "sas", "norwegian", "wideroe", "polar-science"] },
  { id: "eve", name: "Harstad/Narvik Evenes Airport", displayName: "Harstad/Narvik (EVE)", country: "NO", countryCode: "NO", category: "air", city: "Evenes", iata: "EVE", timezone: "Europe/Oslo", tags: ["shared-airport", "lofoten-alternative", "military-shared", "rail-bus-connection"] },
  { id: "bdu", name: "Bardufoss Airport", displayName: "Bardufoss (BDU)", country: "NO", countryCode: "NO", category: "air", city: "Bardufoss", iata: "BDU", timezone: "Europe/Oslo", tags: ["military-civilian", "troms-region", "winter-ski-charter", "wideroe"] },
  { id: "soj", name: "Sørkjosen Airport", displayName: "Sørkjosen (SOJ)", country: "NO", countryCode: "NO", category: "air", city: "Sørkjosen", iata: "SOJ", timezone: "Europe/Oslo", tags: ["nordreisa", "lyngen-alps-access", "regional", "wideroe"] },
  { id: "alf", name: "Alta Airport", displayName: "Alta (ALF)", country: "NO", countryCode: "NO", category: "air", city: "Alta", iata: "ALF", timezone: "Europe/Oslo", tags: ["finnmark-hub", "cathedral-of-ice", "northern-lights", "sas-norwegian-wideroe"] },
  { id: "hft", name: "Hammerfest Airport", displayName: "Hammerfest (HFT)", country: "NO", countryCode: "NO", category: "air", city: "Hammerfest", iata: "HFT", timezone: "Europe/Oslo", tags: ["worlds-northernmost-city-airport", "lng-capital", "wideroe", "polar-night"] },
  { id: "kkn", name: "Kirkenes Høybuktmoen Airport", displayName: "Kirkenes (KKN)", country: "NO", countryCode: "NO", category: "air", city: "Kirkenes", iata: "KKN", timezone: "Europe/Oslo", tags: ["russia-border-area", "hurtigruten-terminus", "golden-hotel", "wideroe", "note-iata-hkn-sources-differ"] },
  { id: "lkl", name: "Lakselv Banak Airport", displayName: "Lakselv (LKL)", country: "NO", countryCode: "NO", category: "air", city: "Lakselv", iata: "LKL", timezone: "Europe/Oslo", tags: ["finnmark", "porsanger", "former-military", "regional"] },
  { id: "hvg", name: "Honningsvåg Valan Airport", displayName: "Honningsvåg (HVG)", country: "NO", countryCode: "NO", category: "air", city: "Honningsvåg", iata: "HVG", timezone: "Europe/Oslo", tags: ["north-cap-access", "europe-northmost", "wideroe", "tourism"] },
  { id: "meh", name: "Mehamn Airport", displayName: "Mehamn (MEH)", country: "NO", countryCode: "NO", category: "air", city: "Mehamn", iata: "MEH", timezone: "Europe/Oslo", tags: ["finnmark-coast", "wideroe-short-runway", "remote"] },
  { id: "bvg", name: "Berlevåg Airport", displayName: "Berlevåg (BVG)", country: "NO", countryCode: "NO", category: "air", city: "Berlevåg", iata: "BVG", timezone: "Europe/Oslo", tags: ["finnmark-coast", "wideroe", "windy-airfield", "remote"] },
  { id: "bjf", name: "Båtsfjord Airport", displayName: "Båtsfjord (BJF)", country: "NO", countryCode: "NO", category: "air", city: "Båtsfjord", iata: "BJF", timezone: "Europe/Oslo", tags: ["varanger", "fishing-village", "wideroe", "remote"] },
  { id: "vaw", name: "Vardø Svartnes Airport", displayName: "Vardø (VAW)", country: "NO", countryCode: "NO", category: "air", city: "Vardø", iata: "VAW", timezone: "Europe/Oslo", tags: ["varanger", "europe-easternmost-city", "gletcher-birding", "wideroe"] },
  { id: "vds", name: "Vadsø Airport", displayName: "Vadsø (VDS)", country: "NO", countryCode: "NO", category: "air", city: "Vadsø", iata: "VDS", timezone: "Europe/Oslo", tags: ["finnmark-capital-area", "varangerfjord", "regional", "wideroe"] },
  { id: "lyr", name: "Longyearbyen Svalbard Airport", displayName: "Longyearbyen (LYR)", country: "NO", countryCode: "NO", category: "air", city: "Longyearbyen", iata: "LYR", timezone: "Arctic/Longyearbyen", tags: ["svalbard", "worlds-northernmost-regular-flight", "polar-expedition-gateway", "norwegian-scandinavian", "special-permit-area"] },

// ---------- Paste into RAIL_STATIONS (category: "rail") ----------

  { id: "oslo-s-rail", name: "Oslo Sentralstasjon (Oslo S)", displayName: "Oslo Central Station", country: "NO", countryCode: "NO", category: "rail", city: "Oslo", timezone: "Europe/Oslo", tags: ["main-hub", "vy", "bergensbanen", "dovrebanen", "sorlandsbanen", "flytoget"] },
  { id: "oslo-gardermoen-rail", name: "Oslo Lufthavn Stasjon (Gardermoen Havalimanı İstasyonu)", displayName: "Oslo Airport Station", country: "NO", countryCode: "NO", category: "rail", city: "Oslo", timezone: "Europe/Oslo", tags: ["airport-station", "flytoget-express", "vy-regional", "dovrebanen"] },
  { id: "drammen-rail", name: "Drammen Stasjon", displayName: "Drammen Station", country: "NO", countryCode: "NO", category: "rail", city: "Drammen", timezone: "Europe/Oslo", tags: ["sorlandsbanen-start", "vestfoldbanen", "vy", "commuter"] },
  { id: "honefoss-rail", name: "Hønefoss Stasjon", displayName: "Hønefoss Station", country: "NO", countryCode: "NO", category: "rail", city: "Hønefoss", timezone: "Europe/Oslo", tags: ["bergensbanen-branch", "robanen", "vy", "junction"] },
  { id: "gol-rail", name: "Gol Stasjon", displayName: "Gol Station", country: "NO", countryCode: "NO", category: "rail", city: "Gol", timezone: "Europe/Oslo", tags: ["bergensbanen", "hallingdal", "vy", "gol-town-church"] },
  { id: "geilo-rail", name: "Geilo Stasjon", displayName: "Geilo Station", country: "NO", countryCode: "NO", category: "rail", city: "Geilo", timezone: "Europe/Oslo", tags: ["bergensbanen", "famous-ski-resort", "vy", "oslo-bergen-3-5h-each"] },
  { id: "finse-rail", name: "Finse Stasjon", displayName: "Finse Station", country: "NO", countryCode: "NO", category: "rail", city: "Finse", timezone: "Europe/Oslo", tags: ["bergensbanen", "1222m-highest-northern-europe", "vy", "star-wars-hoth-filming", "no-car-road-access", "rallarvegen-bike-start"] },
  { id: "myrdal-rail", name: "Myrdal Stasjon", displayName: "Myrdal Station", country: "NO", countryCode: "NO", category: "rail", city: "Myrdal", timezone: "Europe/Oslo", tags: ["bergensbanen-junction", "flamsbana-transfer", "vy", "mountain-station"] },
  { id: "flam-rail", name: "Flåm Stasjon (TURİSTİK)", displayName: "Flåm Station (Tourist)", country: "NO", countryCode: "NO", category: "rail", city: "Flåm", timezone: "Europe/Oslo", tags: ["flamsbana", "scenic-tourist-railway", "unesco-naeroyfjord", "steep-86-percent-gradient", "myrdal-transfer"] },
  { id: "voss-rail", name: "Voss Stasjon", displayName: "Voss Station", country: "NO", countryCode: "NO", category: "rail", city: "Voss", timezone: "Europe/Oslo", tags: ["bergensbanen", "action-sports-capital", "vy", "vestlandet"] },
  { id: "bergen-rail", name: "Bergen Stasjon", displayName: "Bergen Station", country: "NO", countryCode: "NO", category: "rail", city: "Bergen", timezone: "Europe/Oslo", tags: ["bergensbanen-terminus", "vy", "oslo-6-5h", "fish-market-nearby"] },
  { id: "hamar-rail", name: "Hamar Stasjon", displayName: "Hamar Station", country: "NO", countryCode: "NO", category: "rail", city: "Hamar", timezone: "Europe/Oslo", tags: ["dovrebanen", "viken", "vy", "mjsa-connection"] },
  { id: "lillehammer-rail", name: "Lillehammer Stasjon", displayName: "Lillehammer Station", country: "NO", countryCode: "NO", category: "rail", city: "Lillehammer", timezone: "Europe/Oslo", tags: ["dovrebanen", "1994-olympics", "vy", "gudbrandsdalen"] },
  { id: "vinstra-rail", name: "Vinstra Stasjon", displayName: "Vinstra Station", country: "NO", countryCode: "NO", category: "rail", city: "Vinstra", timezone: "Europe/Oslo", tags: ["dovrebanen", "gudbrandsdalen", "vy", "ottadalsbanen-transfer"] },
  { id: "otta-rail", name: "Otta Stasjon", displayName: "Otta Station", country: "NO", countryCode: "NO", category: "rail", city: "Otta", timezone: "Europe/Oslo", tags: ["dovrebanen", "gudbrandsdalen", "vy", "ottadalsbanen"] },
  { id: "dombas-rail", name: "Dombås Stasjon", displayName: "Dombås Station", country: "NO", countryCode: "NO", category: "rail", city: "Dombås", timezone: "Europe/Oslo", tags: ["dovrebanen-junction", "raumabanen-transfer", "vy", "dovrefjell"] },
  { id: "oppdal-rail", name: "Oppdal Stasjon", displayName: "Oppdal Station", country: "NO", countryCode: "NO", category: "rail", city: "Oppdal", timezone: "Europe/Oslo", tags: ["dovrebanen", "trondelag-south", "ski-resort", "vy"] },
  { id: "trondheim-s-rail", name: "Trondheim Sentralstasjon (Trondheim S)", displayName: "Trondheim Central Station", country: "NO", countryCode: "NO", category: "rail", city: "Trondheim", timezone: "Europe/Oslo", tags: ["dovrebanen-terminus", "nordlandsbanen-start", "vy", "sj-nord", "nidelva"] },
  { id: "steinkjer-rail", name: "Steinkjer Stasjon", displayName: "Steinkjer Station", country: "NO", countryCode: "NO", category: "rail", city: "Steinkjer", timezone: "Europe/Oslo", tags: ["nordlandsbanen", "nord-trondelag", "sj-nord", "interchange"] },
  { id: "grong-rail", name: "Grong Stasjon", displayName: "Grong Station", country: "NO", countryCode: "NO", category: "rail", city: "Grong", timezone: "Europe/Oslo", tags: ["nordlandsbanen", "namsos-bus-transfer", "sj-nord", "namdalen"] },
  { id: "mosjoen-rail", name: "Mosjøen Stasjon", displayName: "Mosjøen Station", country: "NO", countryCode: "NO", category: "rail", city: "Mosjøen", timezone: "Europe/Oslo", tags: ["nordlandsbanen", "helgeland", "sj-nord", "old-town-sjosiden"] },
  { id: "mo-i-rana-rail", name: "Mo i Rana Stasjon", displayName: "Mo i Rana Station", country: "NO", countryCode: "NO", category: "rail", city: "Mo i Rana", timezone: "Europe/Oslo", tags: ["nordlandsbanen", "polar-circle-city", "sj-nord", "saltstraumen-access"] },
  { id: "polarsirkelen-rail", name: "Polarsirkelen Stasjon (Kuzey Kutup Dairesi İstasyonu)", displayName: "Polarsirkelen Station (Arctic Circle)", country: "NO", countryCode: "NO", category: "rail", city: "Polarsirkelen", timezone: "Europe/Oslo", tags: ["nordlandsbanen", "arctic-circle-crossing", "sj-nord", "photo-stop"] },
  { id: "fauske-rail", name: "Fauske Stasjon", displayName: "Fauske Station", country: "NO", countryCode: "NO", category: "rail", city: "Fauske", timezone: "Europe/Oslo", tags: ["nordlandsbanen-junction", "salten-line", "sj-nord", "bodo-connection"] },
  { id: "bodo-rail", name: "Bodø Stasjon", displayName: "Bodø Station", country: "NO", countryCode: "NO", category: "rail", city: "Bodø", timezone: "Europe/Oslo", tags: ["nordlandsbanen-terminus", "sj-nord", "arctic-circle-ferry-transfer", "lofoten-gateway"] },
  { id: "kongsberg-rail", name: "Kongsberg Stasjon", displayName: "Kongsberg Station", country: "NO", countryCode: "NO", category: "rail", city: "Kongsberg", timezone: "Europe/Oslo", tags: ["sorlandsbanen", "vy", "silver-mining-town", "defense-industry"] },
  { id: "bo-telemark-rail", name: "Bø Stasjon (Telemark)", displayName: "Bø Station (Telemark)", country: "NO", countryCode: "NO", category: "rail", city: "Bø", timezone: "Europe/Oslo", tags: ["sorlandsbanen", "telemark", "vy", "summerland"] },
  { id: "nordagutu-rail", name: "Nordagutu Stasjon", displayName: "Nordagutu Station", country: "NO", countryCode: "NO", category: "rail", city: "Nordagutu", timezone: "Europe/Oslo", tags: ["sorlandsbanen-junction", "bratsbergbanen", "vy", "interchange"] },
  { id: "kristiansand-rail", name: "Kristiansand Stasjon", displayName: "Kristiansand Station", country: "NO", countryCode: "NO", category: "rail", city: "Kristiansand", timezone: "Europe/Oslo", tags: ["sorlandsbanen", "south-norway-main-station", "vy", "ferry-bus-nearby", "dyreparken-connection"] },
  { id: "egersund-rail", name: "Egersund Stasjon", displayName: "Egersund Station", country: "NO", countryCode: "NO", category: "rail", city: "Egersund", timezone: "Europe/Oslo", tags: ["sorlandsbanen", "vy", "jaren-line", "rogaland-coast"] },
  { id: "sandnes-rail", name: "Sandnes Stasjon", displayName: "Sandnes Station", country: "NO", countryCode: "NO", category: "rail", city: "Sandnes", timezone: "Europe/Oslo", tags: ["sorlandsbanen", "vy", "commuter", "stavanger-agglomeration"] },
  { id: "stavanger-rail", name: "Stavanger Stasjon", displayName: "Stavanger Station", country: "NO", countryCode: "NO", category: "rail", city: "Stavanger", timezone: "Europe/Oslo", tags: ["sorlandsbanen-terminus", "vy", "oil-capital", "lysefjord-access"] },

// ---------- Paste into FERRY_PORTS (category: "sea") ----------

  { id: "oslo-port", name: "Oslo Kruvaziyer Limanı", displayName: "Oslo Cruise Port", country: "NO", countryCode: "NO", category: "sea", city: "Oslo", timezone: "Europe/Oslo", tags: ["main-cruise-port", "150-200-ships-per-year", "aker-brygge-walk", "tjuvholmen"] },
  { id: "sandefjord-port", name: "Sandefjord Limanı", displayName: "Sandefjord Port", country: "NO", countryCode: "NO", category: "sea", city: "Sandefjord", timezone: "Europe/Oslo", tags: ["sweden-ferry", "color-line", "stromstad", "whaling-museum-history"] },
  { id: "larvik-port", name: "Larvik Limanı", displayName: "Larvik Port", country: "NO", countryCode: "NO", category: "sea", city: "Larvik", timezone: "Europe/Oslo", tags: ["color-line", "hirtshals-denmark", "stromstad-sweden", "vestfold"] },
  { id: "kristiansand-port", name: "Kristiansand Limanı", displayName: "Kristiansand Port", country: "NO", countryCode: "NO", category: "sea", city: "Kristiansand", timezone: "Europe/Oslo", tags: ["color-line", "hirtshals-denmark", "cruise", "skjenald-pier", "agder-capital"] },
  { id: "stavanger-port", name: "Stavanger Fiskepiren / Strandkaien Terminali", displayName: "Stavanger Fiskepiren/Strandkaien Terminal", country: "NO", countryCode: "NO", category: "sea", city: "Stavanger", timezone: "Europe/Oslo", tags: ["100-150-cruise-ships", "lysefjord-preikestolen-tours", "fjord-line", "columbus", "norled", "ryfylke-ferry"] },
  { id: "bergen-port", name: "Bergen Feribot ve Kruvaziyer Terminalleri (Strandkaien / Nøstekaien / Skolten-Jekteviken)", displayName: "Bergen Ferry & Cruise Terminals", country: "NO", countryCode: "NO", category: "sea", city: "Bergen", timezone: "Europe/Oslo", tags: ["fjord-line-hirtshals-18h-night", "hurtigruten-south-terminus", "havila", "300-350-cruise-ships", "unesco-bryggen", "skolten-jekteviken-cruise", "regional-fjord1-skyss-norled", "sognefjord-hardangerfjord-gateway"] },
  { id: "langesund-port", name: "Langesund Limanı", displayName: "Langesund Port", country: "NO", countryCode: "NO", category: "sea", city: "Langesund", timezone: "Europe/Oslo", tags: ["telemark-coast", "cruise", "fjordcoast-area"] },
  { id: "bodo-port", name: "Bodø Feribot Terminali", displayName: "Bodø Ferry Terminal", country: "NO", countryCode: "NO", category: "sea", city: "Bodø", timezone: "Europe/Oslo", tags: ["hurtigruten-port", "moskenes-lofoten-ferry-transfer", "regional", "nordland-capital"] },
  { id: "tromso-port", name: "Tromsø Prostneset Feribot/Hurtigruten Terminali", displayName: "Tromsø Prostneset Ferry/Hurtigruten Terminal", country: "NO", countryCode: "NO", category: "sea", city: "Tromsø", timezone: "Europe/Oslo", tags: ["hurtigruten-port", "arctic-capital", "regional-norled", "lyngenfjord-access"] },
  { id: "trondheim-port", name: "Trondheim Hurtigruten/Feribot Terminali", displayName: "Trondheim Hurtigruten/Ferry Terminal", country: "NO", countryCode: "NO", category: "sea", city: "Trondheim", timezone: "Europe/Oslo", tags: ["hurtigruten-port", "havila", "fredrikstad-oddane", "trondelag-coast"] },
  { id: "alesund-port", name: "Ålesund Feribot/Hurtigruten Terminali", displayName: "Ålesund Ferry/Hurtigruten Terminal", country: "NO", countryCode: "NO", category: "sea", city: "Ålesund", timezone: "Europe/Oslo", tags: ["hurtigruten-port", "art-nouveau", "geiranger-fjord-cruise-start", "hellesylt-ferry-transfer"] },
  { id: "geiranger-port", name: "Geiranger Kruvaziyer / Feribot İskelesi", displayName: "Geiranger Cruise/Ferry Pier", country: "NO", countryCode: "NO", category: "sea", city: "Geiranger", timezone: "Europe/Oslo", tags: ["unesco-geirangerfjord", "hellesylt-ferry-fjord1", "valldal-seasonal", "150-200-cruise-ships", "summer-only", "seven-sisters-waterfall", "zero-emission-2026-rule"] },
  { id: "flam-port", name: "Flåm Feribot İskelesi", displayName: "Flåm Ferry Pier", country: "NO", countryCode: "NO", category: "sea", city: "Flåm", timezone: "Europe/Oslo", tags: ["aurlandsfjord", "gudvangen-fjord-cruise", "unesco-naeroyfjord", "bergen-norled-express-summer-5-5h", "the-fjords-as", "fjord1"] },
  { id: "hammerfest-port", name: "Hammerfest Limanı", displayName: "Hammerfest Port", country: "NO", countryCode: "NO", category: "sea", city: "Hammerfest", timezone: "Europe/Oslo", tags: ["hurtigruten-port", "meloya-route", "lng-town", "polar-night"] },
  { id: "honningsvag-port", name: "Honningsvåg Limanı", displayName: "Honningsvåg Port", country: "NO", countryCode: "NO", category: "sea", city: "Honningsvåg", timezone: "Europe/Oslo", tags: ["hurtigruten-port", "north-cap", "europe-northmost-port", "cruise"] },
  { id: "kirkenes-port", name: "Kirkenes Limanı", displayName: "Kirkenes Port", country: "NO", countryCode: "NO", category: "sea", city: "Kirkenes", timezone: "Europe/Oslo", tags: ["hurtigruten-north-terminus", "russia-border-area", "king-crab-safari", "snow-hotel"] },
  { id: "harstad-port", name: "Harstad Limanı", displayName: "Harstad Port", country: "NO", countryCode: "NO", category: "sea", city: "Harstad", timezone: "Europe/Oslo", tags: ["hurtigruten-port", "vesteralsen", "trandal-ferry", "midnight-sun"] },
  { id: "sortland-stokmarknes-port", name: "Sortland / Stokmarknes Limanı (Vesterålen)", displayName: "Sortland/Stokmarknes Port (Vesterålen)", country: "NO", countryCode: "NO", category: "sea", city: "Sortland", timezone: "Europe/Oslo", tags: ["hurtigruten-port", "vesteralen", "hurtigruten-birthplace-museum", "regional"] },
  { id: "svolvaer-port", name: "Svolvær Limanı (Lofoten)", displayName: "Svolvær Port (Lofoten)", country: "NO", countryCode: "NO", category: "sea", city: "Svolvær", timezone: "Europe/Oslo", tags: ["hurtigruten-port", "lofoten-capital", "seasonal-cruise", "fishing-heritage"] },
  { id: "stamsund-port", name: "Stamsund Limanı (Lofoten)", displayName: "Stamsund Port (Lofoten)", country: "NO", countryCode: "NO", category: "sea", city: "Stamsund", timezone: "Europe/Oslo", tags: ["hurtigruten-alternative-lofoten-stop", "season-dependent", "fishing-village", "lofoten"] },
  { id: "molde-port", name: "Molde Kruvaziyer/Feribot Limanı", displayName: "Molde Cruise/Ferry Port", country: "NO", countryCode: "NO", category: "sea", city: "Molde", timezone: "Europe/Oslo", tags: ["hurtigruten-havila-port", "vestnes-ferry-fjord1-30min", "20-40-cruise-ships", "city-of-roses", "atlantic-road-nearby"] },

// ---------- Paste into BUS_HUBS (category: "bus") ----------

  { id: "oslo-bus", name: "Oslo Bussterminal (Oslo Busterminal)", displayName: "Oslo Bus Terminal", country: "NO", countryCode: "NO", category: "bus", city: "Oslo", timezone: "Europe/Oslo", tags: ["main-terminal", "vy-express", "nor-way-bussekspress", "flixbus", "nettbuss", "rail-integrated"] },
  { id: "bergen-bus", name: "Bergen Busstasjon", displayName: "Bergen Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Bergen", timezone: "Europe/Oslo", tags: ["west-norway-hub", "vy-express", "fjord1-buses", "rail-integrated"] },
  { id: "stavanger-bus", name: "Stavanger Bussterminal (Byterminalen)", displayName: "Stavanger Bus Terminal (Byterminalen)", country: "NO", countryCode: "NO", category: "bus", city: "Stavanger", timezone: "Europe/Oslo", tags: ["rogaland-hub", "kolumbus", "vy-express", "rail-integrated"] },
  { id: "trondheim-bus", name: "Trondheim Sentralstasjon (Otobüs Bölümü)", displayName: "Trondheim Central Station (Bus Area)", country: "NO", countryCode: "NO", category: "bus", city: "Trondheim", timezone: "Europe/Oslo", tags: ["atb-regional", "vy-express", "nor-way-bussekspress", "sweden-flixbus-seasonal", "rail-integrated"] },
  { id: "tromso-bus", name: "Tromsø Prostneset Bussterminal", displayName: "Tromsø Prostneset Bus Terminal", country: "NO", countryCode: "NO", category: "bus", city: "Tromsø", timezone: "Europe/Oslo", tags: ["arctic-capital-hub", "troms-trafikk", "regional-north", "ferry-connection"] },
  { id: "kristiansand-bus", name: "Kristiansand Rutebilstasjon", displayName: "Kristiansand Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Kristiansand", timezone: "Europe/Oslo", tags: ["agder-hub", "nor-way-bussekspress", "denmark-ferry-connection", "rail-nearby"] },
  { id: "bodo-bus", name: "Bodø Bussterminal", displayName: "Bodø Bus Terminal", country: "NO", countryCode: "NO", category: "bus", city: "Bodø", timezone: "Europe/Oslo", tags: ["nordland-hub", "sotoruss", "lofoten-buses", "rail-terminus"] },
  { id: "lillehammer-bus", name: "Lillehammer Skysstasjon", displayName: "Lillehammer Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Lillehammer", timezone: "Europe/Oslo", tags: ["olympic-city", "gudbrandsdalen", "vy-express", "rail-integrated"] },
  { id: "haugesund-bus", name: "Haugesund Rutebilstasjon", displayName: "Haugesund Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Haugesund", timezone: "Europe/Oslo", tags: ["kolumbus", "rogaland-north", "karmoy"] },
  { id: "alesund-bus", name: "Ålesund Rutebilstasjon", displayName: "Ålesund Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Ålesund", timezone: "Europe/Oslo", tags: ["more-romsdal", "fjord1-buses", "geiranger-connection"] },
  { id: "hammerfest-bus", name: "Hammerfest Busstasjon", displayName: "Hammerfest Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Hammerfest", timezone: "Europe/Oslo", tags: ["finnmark", "sotoruss", "regional-north"] },
  { id: "alta-bus", name: "Alta Busstasjon", displayName: "Alta Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Alta", timezone: "Europe/Oslo", tags: ["finnmark-hub", "sotoruss", "north-cape-buses", "long-distance"] },
  { id: "narvik-bus", name: "Narvik Busstasjon", displayName: "Narvik Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Narvik", timezone: "Europe/Oslo", tags: ["ofoten", "sweden-border-area", "lofoten-bus-transfer", "rail-adjacent"] },
  { id: "kirkenes-bus", name: "Kirkenes Busstasjon", displayName: "Kirkenes Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Kirkenes", timezone: "Europe/Oslo", tags: ["finnmark-east", "russia-border-area", "hurtigruten-terminus-connection", "sotoruss"] },
  { id: "drammen-bus", name: "Drammen Buskerud Busstasjon", displayName: "Drammen Buskerud Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Drammen", timezone: "Europe/Oslo", tags: ["viken", "oslo-commuter", "rail-integrated"] },
  { id: "fredrikstad-bus", name: "Fredrikstad / Sarpsborg Rutebilstasjon", displayName: "Fredrikstad/Sarpsborg Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Fredrikstad", timezone: "Europe/Oslo", tags: ["ostfold", "oslo-corridor", "rail-integrated"] },
  { id: "skien-bus", name: "Skien / Porsgrunn (Grenland) Rutebilstasjon", displayName: "Skien/Porsgrunn (Grenland) Bus Station", country: "NO", countryCode: "NO", category: "bus", city: "Skien", timezone: "Europe/Oslo", tags: ["telemark-grenland", "regional", "coastal-route"] },

// ============================================================
// TOPLAM: 44 air + 32 rail + 21 sea + 17 bus = 114 kayıt
// Notlar:
// - Rygge (RYG) sivil hizmeti kapatılmış (askeri kullanımda) —
//   tarihsel referans için korundu. Narvik Framnes (NVK) çok
//   sınırlı/dönemsel — bölge genellikle Evenes (EVE) kullanır.
// - Kirkenes IATA kodu kaynak PDF'te KKN olarak geçiyor; yaygın
//   kaynaklarda HKN olarak da rastlanır (tartışmalı — not düşüldü).
// - PDF'te Hirtshals (Danimarka) 22. liman olarak Norveç bağlantılı
//   ana Danimarka limanı olarak listeleniyor; ülke kodu DK
//   olduğundan NO kayıtlarına eklenmedi (sadece bu notta).
// - Hurtigruten + Havila Kystruten aynı rotada çalışır (2021'den
//   beri): Bergen→Kirkenes 34 liman, tek yön 6-7 gün, gidi-dönüş
//   11-12 gün, yıl boyu.
// - Finse 1.222 m ile Kuzey Avrupa'nın en yüksek tren istasyonudur;
//   yalnızca trenle erişilir (araç yolu yok); Star Wars Hoth
//   sahneleri burada çekilmiştir.
// - Flåm Stasjon turistik hat (Flåmsbana) terminüsüdür — Myrdal'dan
//   %86 eğimle iner, UNESCO Nærøyfjord rotasının parçasıdır.
// - Geiranger yalnızca yaz seferi açıktır (yol kışın kapalı);
//   2026'dan itibaren sıfır emisyon zorunluluğu getiriliyor.
// - Svalbard (LYR) özel izin bölgesidir; dünyanın en kuzeydeki
//   düzenli uçuşlarına ev sahipliği yapar.
// ============================================================
