// ============================================================
// FreeBuff Travel — Portugal (PT) destination entries
// Converted from: TravelApp_Portugal.pdf
// NOTE: Mainland has NO international ferry; Azores (AtlânticoLine)
// and Madeira run inter-island ferries. Rail operator: CP
// (Comboios de Portugal). Madeira & Azores have NO railways.
// ============================================================

// ---------- Paste into AIRPORTS (category: "air") ----------

  { id: "lis", name: "Lisbon Humberto Delgado Airport (Aeroporto de Lisboa)", displayName: "Lisbon (LIS)", country: "PT", countryCode: "PT", category: "air", city: "Lisbon", iata: "LIS", timezone: "Europe/Lisbon", tags: ["main-hub", "tp-air-portugal", "star-alliance", "portela", "new-airport-project", "rail-connected"] },
  { id: "opo", name: "Porto Francisco Sá Carneiro Airport (Aeroporto do Porto)", displayName: "Porto (OPO)", country: "PT", countryCode: "PT", category: "air", city: "Porto", iata: "OPO", timezone: "Europe/Lisbon", tags: ["second-busiest", "pedro-salgado", "metro-connected", "ryanair-base", "low-cost"] },
  { id: "fao", name: "Faro Airport (Aeroporto de Faro)", displayName: "Faro (FAO)", country: "PT", countryCode: "PT", category: "air", city: "Faro", iata: "FAO", timezone: "Europe/Lisbon", tags: ["algarve", "seasonal-peak-summer", "charter", "tourism", "ryanair"] },
  { id: "byj", name: "Beja Airport (Aeroporto de Beja)", displayName: "Beja (BYJ)", country: "PT", countryCode: "PT", category: "air", city: "Beja", iata: "BYJ", timezone: "Europe/Lisbon", tags: ["alentejo", "limited-schedule", "military-shared", "charter", "underused"] },
  { id: "fnc", name: "Funchal - Cristiano Ronaldo Airport (Aeroporto da Madeira)", displayName: "Funchal (FNC)", country: "PT", countryCode: "PT", category: "air", city: "Funchal", iata: "FNC", timezone: "Atlantic/Madeira", tags: ["madeira", "short-runway-extended-cliff", "unique-approach", "tourism", "european-charter"] },
  { id: "pxo", name: "Porto Santo Airport (Aeroporto de Porto Santo)", displayName: "Porto Santo (PXO)", country: "PT", countryCode: "PT", category: "air", city: "Porto Santo", iata: "PXO", timezone: "Atlantic/Madeira", tags: ["madeira-neighbor", "golden-sand-beach", "sata", "seasonal"] },
  { id: "pdl", name: "Ponta Delgada - João Paulo II Airport (Aeroporto de Ponta Delgada)", displayName: "Ponta Delgada (PDL)", country: "PT", countryCode: "PT", category: "air", city: "Ponta Delgada", iata: "PDL", timezone: "Atlantic/Azores", tags: ["azores-main-hub", "sata-azores", "north-atlantic", "europe-north-america-refuel", "tourism"] },
  { id: "ter", name: "Lajes - Terceira Airport (Aeroporto das Lajes)", displayName: "Terceira (TER)", country: "PT", countryCode: "PT", category: "air", city: "Lajes", iata: "TER", timezone: "Atlantic/Azores", tags: ["azores", "military-shared-nato", "lajes-field", "sata", "international"] },
  { id: "hor", name: "Horta Airport (Aeroporto da Horta)", displayName: "Horta (HOR)", country: "PT", countryCode: "PT", category: "air", city: "Horta", iata: "HOR", timezone: "Atlantic/Azores", tags: ["azores-faial", "sata", "island-hopping", "marina-pico-connection"] },
  { id: "sma", name: "Santa Maria Airport (Aeroporto de Santa Maria)", displayName: "Santa Maria (SMA)", country: "PT", countryCode: "PT", category: "air", city: "Vila do Porto", iata: "SMA", timezone: "Atlantic/Azores", tags: ["azores-south", "icao-north-atlantic-control", "historic-refueling", "long-runway", "sata", "seasonal-intl"] },
  { id: "pix", name: "Pico Airport (Aeroporto do Pico)", displayName: "Pico (PIX)", country: "PT", countryCode: "PT", category: "air", city: "Pico", iata: "PIX", timezone: "Atlantic/Azores", tags: ["azores", "portugal-highest-point-pico", "unesco-vineyards", "whale-watching", "sata", "triangle-islands"] },
  { id: "sjz", name: "São Jorge Airport (Aeroporto de São Jorge)", displayName: "São Jorge (SJZ)", country: "PT", countryCode: "PT", category: "air", city: "Velaz", iata: "SJZ", timezone: "Atlantic/Azores", tags: ["azores", "short-runway", "sata", "fajas-limited"] },
  { id: "grw", name: "Graciosa Airport (Aeroporto da Graciosa)", displayName: "Graciosa (GRW)", country: "PT", countryCode: "PT", category: "air", city: "Santa Cruz da Graciosa", iata: "GRW", timezone: "Atlantic/Azores", tags: ["azores", "sata", "island-service"] },
  { id: "flw", name: "Flores Airport (Aeroporto das Flores)", displayName: "Flores (FLW)", country: "PT", countryCode: "PT", category: "air", city: "Santa Cruz das Flores", iata: "FLW", timezone: "Atlantic/Azores", tags: ["azores-west", "sata", "azores-triple-point", "waterfalls"] },

// ---------- Paste into RAIL_STATIONS (category: "rail") ----------

  { id: "lisboa-santa-apolonia-rail", name: "Lisboa Santa Apolónia İstasyonu (Estação de Santa Apolónia)", displayName: "Lisbon Santa Apolónia Station", country: "PT", countryCode: "PT", category: "rail", city: "Lisbon", timezone: "Europe/Lisbon", tags: ["historic-riverfront", "cp", "international-direction", "madrid-lusitania-hotel-train-suspended", "sintra-commuter"] },
  { id: "lisboa-oriente-rail", name: "Lisboa Oriente İstasyonu (Estação de Lisboa Oriente / Gare do Oriente)", displayName: "Lisbon Oriente Station", country: "PT", countryCode: "PT", category: "rail", city: "Lisbon", timezone: "Europe/Lisbon", tags: ["calatrava-design", "1998-expo", "most-modern-hub", "alfapendular-start", "all-ic-lines", "metro-bus-integrated"] },
  { id: "lisboa-entrecampos-rail", name: "Lisboa Entrecampos İstasyonu (Estação de Entrecampos)", displayName: "Lisbon Entrecampos Station", country: "PT", countryCode: "PT", category: "rail", city: "Lisbon", timezone: "Europe/Lisbon", tags: ["central-lisbon", "cp", "ic-trains", "sintra-commuter"] },
  { id: "lisboa-rossio-rail", name: "Lisboa Rossio İstasyonu (Estação do Rossio) (Banliyö)", displayName: "Lisbon Rossio Station (Commuter)", country: "PT", countryCode: "PT", category: "rail", city: "Lisbon", timezone: "Europe/Lisbon", tags: ["commuter", "sintra-line", "historic-terminus", "rossio-square"] },
  { id: "lisboa-cais-do-sodre-rail", name: "Lisboa Cais do Sodré İstasyonu (Banliyö)", displayName: "Lisbon Cais do Sodré Station (Commuter)", country: "PT", countryCode: "PT", category: "rail", city: "Lisbon", timezone: "Europe/Lisbon", tags: ["commuter", "cascais-line", "ferry-interchange", "riverfront"] },
  { id: "porto-campanha-rail", name: "Porto Campanhã İstasyonu (Estação do Porto Campanhã)", displayName: "Porto Campanhã Station", country: "PT", countryCode: "PT", category: "rail", city: "Porto", timezone: "Europe/Lisbon", tags: ["north-hub", "cp", "alfapendular", "ic-trains", "madrid-direction"] },
  { id: "porto-sao-bento-rail", name: "Porto São Bento İstasyonu (Estação de São Bento)", displayName: "Porto São Bento Station", country: "PT", countryCode: "PT", category: "rail", city: "Porto", timezone: "Europe/Lisbon", tags: ["azulejo-palace", "city-center", "cp", "regional", "douro-trains"] },
  { id: "braga-rail", name: "Braga İstasyonu (Estação de Braga)", displayName: "Braga Station", country: "PT", countryCode: "PT", category: "rail", city: "Braga", timezone: "Europe/Lisbon", tags: ["minho", "cp-urban", "alfapendular-terminus", "porto-connection"] },
  { id: "guimaraes-rail", name: "Guimarães İstasyonu (Estação de Guimarães)", displayName: "Guimarães Station", country: "PT", countryCode: "PT", category: "rail", city: "Guimarães", timezone: "Europe/Lisbon", tags: ["birthplace-of-portugal", "ufc-2018", "cp", "porto-line"] },
  { id: "viana-do-castelo-rail", name: "Viana do Castelo İstasyonu (Estação de Viana do Castelo)", displayName: "Viana do Castelo Station", country: "PT", countryCode: "PT", category: "rail", city: "Viana do Castelo", timezone: "Europe/Lisbon", tags: ["minho-coast", "cp-regional", "line-end"] },
  { id: "valenca-rail", name: "Valença İstasyonu (Estação de Valença)", displayName: "Valença Station", country: "PT", countryCode: "PT", category: "rail", city: "Valença", timezone: "Europe/Lisbon", tags: ["spain-border", "tui-opposite", "cp-regional", "international-corridor"] },
  { id: "nine-rail", name: "Nine İstasyonu (Estação de Nine)", displayName: "Nine Station", country: "PT", countryCode: "PT", category: "rail", city: "Nine", timezone: "Europe/Lisbon", tags: ["junction", "cp", "braga-avenso-branch"] },
  { id: "regua-rail", name: "Régua İstasyonu (Estação de Peso da Régua)", displayName: "Peso da Régua Station", country: "PT", countryCode: "PT", category: "rail", city: "Peso da Régua", timezone: "Europe/Lisbon", tags: ["douro-valley", "unesco-vineyards", "douro-historic-train-start", "wine-museum"] },
  { id: "pinhao-rail", name: "Pinhão İstasyonu (Estação de Pinhão)", displayName: "Pinhão Station", country: "PT", countryCode: "PT", category: "rail", city: "Pinhão", timezone: "Europe/Lisbon", tags: ["douro-heart", "azulejo-station", "wine-quinta-tours", "douro-line"] },
  { id: "pocinho-rail", name: "Pocinho İstasyonu (Estação de Pocinho)", displayName: "Pocinho Station", country: "PT", countryCode: "PT", category: "rail", city: "Pocinho", timezone: "Europe/Lisbon", tags: ["douro-east-end", "coa-rock-artunesco", "line-end", "regional"] },
  { id: "tua-rail", name: "Tua İstasyonu (Estação de Tua)", displayName: "Tua Station", country: "PT", countryCode: "PT", category: "rail", city: "Tua", timezone: "Europe/Lisbon", tags: ["douro-tua-confluence", "cp-regional", "small-stop"] },
  { id: "coimbra-b-rail", name: "Coimbra-B İstasyonu (Estação de Coimbra-B)", displayName: "Coimbra-B Station", country: "PT", countryCode: "PT", category: "rail", city: "Coimbra", timezone: "Europe/Lisbon", tags: ["main-station", "cp", "alfapendular", "ic-trains", "university-city"] },
  { id: "coimbra-a-rail", name: "Coimbra-A İstasyonu (Estação de Coimbra) (Bölgesel)", displayName: "Coimbra-A Station (Regional)", country: "PT", countryCode: "PT", category: "rail", city: "Coimbra", timezone: "Europe/Lisbon", tags: ["city-center", "cp-regional", "single-car"] },
  { id: "aveiro-rail", name: "Aveiro İstasyonu (Estação de Aveiro)", displayName: "Aveiro Station", country: "PT", countryCode: "PT", category: "rail", city: "Aveiro", timezone: "Europe/Lisbon", tags: ["canal-venice-of-portugal", "cp", "alfapendular", "north-line"] },
  { id: "entroncamento-rail", name: "Entroncamento İstasyonu (Estação de Entroncamento)", displayName: "Entroncamento Station", country: "PT", countryCode: "PT", category: "rail", city: "Entroncamento", timezone: "Europe/Lisbon", tags: ["national-junction", "locomotive-museum", "cp", "north-south-beira-lines"] },
  { id: "santarem-rail", name: "Santarém İstasyonu", displayName: "Santarém Station", country: "PT", countryCode: "PT", category: "rail", city: "Santarém", timezone: "Europe/Lisbon", tags: ["tagus-valley", "cp", "ic-trains", "gothic-capitals"] },
  { id: "guarda-rail", name: "Guarda İstasyonu (Estação da Guarda)", displayName: "Guarda Station", country: "PT", countryCode: "PT", category: "rail", city: "Guarda", timezone: "Europe/Lisbon", tags: ["highest-city-1056m", "beira-alta", "cp", "vilar-formoso-spain-border", "spain-services-limited", "line-repairs"] },
  { id: "covilha-rail", name: "Covilhã İstasyonu (Estação da Covilhã)", displayName: "Covilhã Station", country: "PT", countryCode: "PT", category: "rail", city: "Covilhã", timezone: "Europe/Lisbon", tags: ["serra-da-estrela-gateway", "beira-baixa", "cp", "line-repair-partial"] },
  { id: "castelo-branco-rail", name: "Castelo Branco İstasyonu", displayName: "Castelo Branco Station", country: "PT", countryCode: "PT", category: "rail", city: "Castelo Branco", timezone: "Europe/Lisbon", tags: ["beira-baixa", "cp", "regional", "limited"] },
  { id: "leiria-rail", name: "Leiria İstasyonu (Kısıtlı Hizmet)", displayName: "Leiria Station (Limited)", country: "PT", countryCode: "PT", category: "rail", city: "Leiria", timezone: "Europe/Lisbon", tags: ["west-line", "cp-regional", "limited-service"] },
  { id: "figueira-da-foz-rail", name: "Figueira da Foz İstasyonu", displayName: "Figueira da Foz Station", country: "PT", countryCode: "PT", category: "rail", city: "Figueira da Foz", timezone: "Europe/Lisbon", tags: ["mondego-mouth", "beach-town", "cp-regional", "line-end"] },
  { id: "tomar-rail", name: "Tomar İstasyonu", displayName: "Tomar Station", country: "PT", countryCode: "PT", category: "rail", city: "Tomar", timezone: "Europe/Lisbon", tags: ["templar-town", "unesco", "cp-regional", "linha-do-tomar"] },
  { id: "evora-rail", name: "Évora İstasyonu (Estação de Évora)", displayName: "Évora Station", country: "PT", countryCode: "PT", category: "rail", city: "Évora", timezone: "Europe/Lisbon", tags: ["alentejo-capital", "unesco-roman-temple", "cp", "ic-lisbon", "linha-do-alentejo"] },
  { id: "beja-rail", name: "Beja İstasyonu (Estação de Beja)", displayName: "Beja Station", country: "PT", countryCode: "PT", category: "rail", city: "Beja", timezone: "Europe/Lisbon", tags: ["alentejo-south", "cp", "ic-lisbon", "regional"] },
  { id: "casa-branca-rail", name: "Casa Branca İstasyonu", displayName: "Casa Branca Station", country: "PT", countryCode: "PT", category: "rail", city: "Casa Branca", timezone: "Europe/Lisbon", tags: ["junction", "evora-beja-split", "cp"] },
  { id: "faro-rail", name: "Faro İstasyonu (Estação de Faro)", displayName: "Faro Station", country: "PT", countryCode: "PT", category: "rail", city: "Faro", timezone: "Europe/Lisbon", tags: ["algarve-hub", "cp", "alfapendular", "ic-lisbon", "spanish-border-lines"] },
  { id: "tunes-rail", name: "Tunes İstasyonu (Estação de Tunes)", displayName: "Tunes Station", country: "PT", countryCode: "PT", category: "rail", city: "Tunes", timezone: "Europe/Lisbon", tags: ["algarve-junction", "lagos-branch-split", "cp"] },
  { id: "lagos-rail", name: "Lagos İstasyonu (Estação de Lagos)", displayName: "Lagos Station", country: "PT", countryCode: "PT", category: "rail", city: "Lagos", timezone: "Europe/Lisbon", tags: ["algarve-west", "line-end", "cp-regional", "marina"] },
  { id: "albufeira-ferreiras-rail", name: "Albufeira-Ferreiras İstasyonu", displayName: "Albufeira-Ferreiras Station", country: "PT", countryCode: "PT", category: "rail", city: "Albufeira", timezone: "Europe/Lisbon", tags: ["algarve-tourism", "cp", "ic-trains", "beach-access"] },
  { id: "loule-rail", name: "Loulé İstasyonu", displayName: "Loulé Station", country: "PT", countryCode: "PT", category: "rail", city: "Loulé", timezone: "Europe/Lisbon", tags: ["algarve", "cp-regional", "small-stop"] },
  { id: "tavira-rail", name: "Tavira İstasyonu", displayName: "Tavira Station", country: "PT", countryCode: "PT", category: "rail", city: "Tavira", timezone: "Europe/Lisbon", tags: ["eastern-algarve", "gilao-river", "cp-regional"] },
  { id: "villa-real-santo-antonio-rail", name: "Vila Real de Santo António İstasyonu", displayName: "Vila Real de Santo António Station", country: "PT", countryCode: "PT", category: "rail", city: "Vila Real de Santo António", timezone: "Europe/Lisbon", tags: ["guadiana-mouth", "spain-border", "ayamonte-opposite", "cp-line-end"] },
  { id: "portimao-rail", name: "Portimão İstasyonu", displayName: "Portimão Station", country: "PT", countryCode: "PT", category: "rail", city: "Portimão", timezone: "Europe/Lisbon", tags: ["algarve-central", "arade-river", "cp-regional"] },
  { id: "douro-historic-rail", name: "Comboio Histórico do Douro (Douro Tarihî Treni)", displayName: "Douro Historical Train", country: "PT", countryCode: "PT", category: "rail", city: "Peso da Régua", timezone: "Europe/Lisbon", tags: ["tourist-heritage-train", "regua-pocinho", "vintage-carriages", "douro-valley", "seasonal"] },
  { id: "vouga-historic-rail", name: "Comboio Histórico do Vouga (Vouga Tarihî Treni)", displayName: "Vouga Historical Train", country: "PT", countryCode: "PT", category: "rail", city: "Aveiro", timezone: "Europe/Lisbon", tags: ["tourist-heritage-train", "narrow-gauge", "serta-line", "seasonal", "museum-train"] },

// ---------- Paste into FERRY_PORTS (category: "sea") ----------

  { id: "funchal-port", name: "Funchal Limanı (Porto do Funchal) - Feribot Terminali", displayName: "Funchal Ferry Port", country: "PT", countryCode: "PT", category: "sea", city: "Funchal", timezone: "Atlantic/Madeira", tags: ["madeira", "porto-santo-ferry", "atlanticoline", "hydrofoil", "year-round"] },
  { id: "porto-santo-port", name: "Porto Santo Limanı (Porto de Vila Baleira)", displayName: "Porto Santo Port", country: "PT", countryCode: "PT", category: "sea", city: "Porto Santo", timezone: "Atlantic/Madeira", tags: ["madeira-neighbor", "golden-beach", "atlanticoline", "funchal-link"] },
  { id: "ponta-delgada-port", name: "Ponta Delgada Limanı (Porto de Ponta Delgada)", displayName: "Ponta Delgada Port", country: "PT", countryCode: "PT", category: "sea", city: "Ponta Delgada", timezone: "Atlantic/Azores", tags: ["azores-main-port", "atlanticoline", "island-hopping", "cruise"] },
  { id: "angra-pria-port", name: "Angra do Heroísmo Limanı / Praia da Vitória Limanı", displayName: "Angra do Heroísmo / Praia da Vitória Port", country: "PT", countryCode: "PT", category: "sea", city: "Angra do Heroísmo", timezone: "Atlantic/Azores", tags: ["terceira-island", "unesco-town", "atlanticoline", "triangle-ferry"] },
  { id: "horta-port", name: "Horta Limanı (Porto da Horta)", displayName: "Horta Port", country: "PT", countryCode: "PT", category: "sea", city: "Horta", timezone: "Atlantic/Azores", tags: ["faial-island", "world-famous-marina", "pico-ferry-30min", "atlanticoline", "volcano-montanha"] },
  { id: "madalena-port", name: "Madalena Limanı (Porto da Madalena)", displayName: "Madalena Port", country: "PT", countryCode: "PT", category: "sea", city: "Madalena", timezone: "Atlantic/Azores", tags: ["pico-island", "horta-ferry-30min", "triangle-line", "atlanticoline", "vineyardunesco"] },
  { id: "velas-port", name: "Velas Limanı (Porto de Velas) & Calheta Limanı", displayName: "Velas & Calheta Port (São Jorge)", country: "PT", countryCode: "PT", category: "sea", city: "Velas", timezone: "Atlantic/Azores", tags: ["sao-jorge-island", "triangle-ferry", "horta-madalena-lines", "atlanticoline", "faja-trail"] },
  { id: "graciosa-port", name: "Santa Cruz da Graciosa Limanı", displayName: "Santa Cruz da Graciosa Port", country: "PT", countryCode: "PT", category: "sea", city: "Santa Cruz da Graciosa", timezone: "Atlantic/Azores", tags: ["azores", "atlanticoline", "island-service"] },
  { id: "santa-maria-port", name: "Vila do Porto Limanı", displayName: "Vila do Porto Port (Santa Maria)", country: "PT", countryCode: "PT", category: "sea", city: "Vila do Porto", timezone: "Atlantic/Azores", tags: ["azores-south", "atlanticoline", "baia-dos-anjos"] },
  { id: "flores-port", name: "Lajes das Flores Limanı / Santa Cruz das Flores Limanı", displayName: "Lajes / Santa Cruz das Flores Port", country: "PT", countryCode: "PT", category: "sea", city: "Santa Cruz das Flores", timezone: "Atlantic/Azores", tags: ["azores-west", "atlanticoline", "waterfalls-access"] },
  { id: "corvo-port", name: "Corvo Limanı (Porto da Casa)", displayName: "Corvo Port", country: "PT", countryCode: "PT", category: "sea", city: "Corvo", timezone: "Atlantic/Azores", tags: ["smallest-island", "atlanticoline", "remote", "limited-schedule"] },
  { id: "lisbon-cruise", name: "Lizbon Kruvaziyer Terminali (Terminal de Cruzeiros de Lisboa)", displayName: "Lisbon Cruise Terminal", country: "PT", countryCode: "PT", category: "sea", city: "Lisbon", timezone: "Europe/Lisbon", tags: ["main-cruise-port", "rocha-conde-obidos", "med-atlantic-itineraries", "major-lines"] },
  { id: "porto-lexoes-cruise", name: "Porto / Leixões Kruvaziyer Terminali (Terminal de Cruzeiros de Leixões)", displayName: "Porto/Leixões Cruise Terminal", country: "PT", countryCode: "PT", category: "sea", city: "Matosinhos", timezone: "Europe/Lisbon", tags: ["north-cruise-port", "matosinhos", "porto-access", "cruise"] },
  { id: "funchal-cruise", name: "Funchal Kruvaziyer Limanı (Porto do Funchal)", displayName: "Funchal Cruise Port", country: "PT", countryCode: "PT", category: "sea", city: "Funchal", timezone: "Atlantic/Madeira", tags: ["madeira-cruise", "atlantic-crossings-stop", "winter-season-busy"] },
  { id: "ponta-delgada-cruise", name: "Ponta Delgada Kruvaziyer Limanı (Azorlar)", displayName: "Ponta Delgada Cruise Port", country: "PT", countryCode: "PT", category: "sea", city: "Ponta Delgada", timezone: "Atlantic/Azores", tags: ["azores-cruise", "transatlantic-stop", "north-atlantic"] },
  { id: "horta-cruise", name: "Horta Kruvaziyer Limanı (Azorlar - Faial)", displayName: "Horta Cruise Port", country: "PT", countryCode: "PT", category: "sea", city: "Horta", timezone: "Atlantic/Azores", tags: ["azores-cruise", "marina-peters-caffe", "transatlantic-history"] },
  { id: "portimao-cruise", name: "Portimão Kruvaziyer Limanı (Algarve)", displayName: "Portimão Cruise Port", country: "PT", countryCode: "PT", category: "sea", city: "Portimão", timezone: "Europe/Lisbon", tags: ["algarve-cruise", "arade-river", "benagil-access"] },
  { id: "angra-cruise", name: "Praia da Vitória / Angra do Heroísmo (Azorlar - Terceira)", displayName: "Terceira Cruise Port", country: "PT", countryCode: "PT", category: "sea", city: "Angra do Heroísmo", timezone: "Atlantic/Azores", tags: ["azores-cruise", "unesco-angra", "island-hop-call"] },

// ---------- Paste into BUS_HUBS (category: "bus") ----------

  { id: "lisbon-sete-rios-bus", name: "Sete Rios Otobüs Terminali (Terminal Rodoviário de Sete Rios)", displayName: "Lisbon Sete Rios Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Lisbon", timezone: "Europe/Lisbon", tags: ["main-terminal", "rede-expressos", "flixbus", "renex", "international-madrid", "metro-jardim-zoo"] },
  { id: "lisbon-oriente-bus", name: "Oriente Otobüs Terminali (Terminal Rodoviário de Lisboa Oriente)", displayName: "Lisbon Oriente Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Lisbon", timezone: "Europe/Lisbon", tags: ["gare-do-oriente", "train-metro-integrated", "rede-expressos", "flixbus", "expo-area"] },
  { id: "porto-campo-24-agosto-bus", name: "Campo 24 de Agosto Terminali - Kapalı", displayName: "Porto Campo 24 de Agosto Terminal (Closed)", country: "PT", countryCode: "PT", category: "bus", city: "Porto", timezone: "Europe/Lisbon", tags: ["closed-long-term", "former-main-terminal", "multi-point-departures-now"] },
  { id: "porto-casa-da-musica-bus", name: "Garage Atlântico / Casa da Música Terminali", displayName: "Porto Casa da Música Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Porto", timezone: "Europe/Lisbon", tags: ["porto-main-departure", "rede-expressos", "flixbus", "metro-connected"] },
  { id: "porto-campanha-bus", name: "Terminal Rodoviário de Campanhã (Yeni Porto Terminali)", displayName: "Porto Campanhã Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Porto", timezone: "Europe/Lisbon", tags: ["new-terminal", "rail-interchange", "international", "rede-expressos", "flixbus"] },
  { id: "porto-rede-expressos-stops", name: "Rede Expressos / Rodonorte Kalkı Noktaları (Porto, çeşitli)", displayName: "Porto Rede Expressos/Rodonorte Pickup Points", country: "PT", countryCode: "PT", category: "bus", city: "Porto", timezone: "Europe/Lisbon", tags: ["pickup-points", "multiple-locations", "no-central-terminal", "rede-expressos", "rodonorte"] },
  { id: "faro-bus", name: "Faro Otobüs Terminali (Terminal Rodoviário de Faro)", displayName: "Faro Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Faro", timezone: "Europe/Lisbon", tags: ["algarve-hub", "rede-expressos", "eva-transportes", "spain-connection"] },
  { id: "lagos-bus", name: "Lagos Otobüs Terminali (Terminal Rodoviário de Lagos)", displayName: "Lagos Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Lagos", timezone: "Europe/Lisbon", tags: ["algarve-west", "eva", "rede-expressos", "tourism"] },
  { id: "portimao-bus", name: "Portimão Otobüs Terminali", displayName: "Portimão Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Portimão", timezone: "Europe/Lisbon", tags: ["algarve-central", "eva", "rede-expressos"] },
  { id: "albufeira-bus", name: "Albufeira Otobüs Terminali (Terminal Rodoviário de Albufeira)", displayName: "Albufeira Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Albufeira", timezone: "Europe/Lisbon", tags: ["algarve-tourism", "eva", "rede-expressos", "seasonal-peak"] },
  { id: "coimbra-bus", name: "Coimbra Otobüs Terminali (Terminal Rodoviário de Coimbra)", displayName: "Coimbra Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Coimbra", timezone: "Europe/Lisbon", tags: ["central-portugal", "university-city", "rede-expressos", "flixbus", "madrid-malaga", "joalto"] },
  { id: "leiria-bus", name: "Leiria Otobüs Terminali", displayName: "Leiria Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Leiria", timezone: "Europe/Lisbon", tags: ["west-line", "rede-expressos", "rodoviaria-do-tejo", "fátima-connection"] },
  { id: "aveiro-bus", name: "Aveiro Otobüs Terminali", displayName: "Aveiro Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Aveiro", timezone: "Europe/Lisbon", tags: ["canal-city", "rede-expressos", "transdev", "flixbus"] },
  { id: "viseu-bus", name: "Viseu Otobüs Terminali", displayName: "Viseu Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Viseu", timezone: "Europe/Lisbon", tags: ["beira-alta", "rede-expressos", "regional"] },
  { id: "guarda-bus", name: "Guarda Otobüs Terminali", displayName: "Guarda Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Guarda", timezone: "Europe/Lisbon", tags: ["highest-city", "beira-alta", "rede-expressos", "regional"] },
  { id: "castelo-branco-bus", name: "Castelo Branco Otobüs Terminali", displayName: "Castelo Branco Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Castelo Branco", timezone: "Europe/Lisbon", tags: ["beira-baixa", "rede-expressos", "regional"] },
  { id: "covilha-bus", name: "Covilhã Otobüs Terminali", displayName: "Covilhã Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Covilhã", timezone: "Europe/Lisbon", tags: ["serra-da-estrela", "rede-expressos", "university"] },
  { id: "fatima-bus", name: "Fátima Otobüs Terminali", displayName: "Fátima Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Fátima", timezone: "Europe/Lisbon", tags: ["pilgrimage-site", "year-round-tourism", "rede-expressos", "shrine-shuttle"] },
  { id: "braga-bus", name: "Braga Otobüs Terminali (Central de Camionagem de Braga)", displayName: "Braga Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Braga", timezone: "Europe/Lisbon", tags: ["minho", "rede-expressos", "porto-commuter", "bom-jesus-funicular-direction"] },
  { id: "guimaraes-bus", name: "Guimarães Otobüs Terminali (Central de Camionagem de Guimarães)", displayName: "Guimarães Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Guimarães", timezone: "Europe/Lisbon", tags: ["birthplace-of-portugal", "rede-expressos", "regional"] },
  { id: "viana-do-castelo-bus", name: "Viana do Castelo Otobüs Terminali (Central de Camionagem)", displayName: "Viana do Castelo Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Viana do Castelo", timezone: "Europe/Lisbon", tags: ["minho-coast", "rede-expressos", "regional"] },
  { id: "vila-real-bus", name: "Vila Real Otobüs Terminali (Rodoviária de Vila Real)", displayName: "Vila Real Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Vila Real", timezone: "Europe/Lisbon", tags: ["douro-north", "rede-expressos", "regional"] },
  { id: "braganca-bus", name: "Bragança Otobüs Terminali (Terminal Rodoviário de Bragança)", displayName: "Bragança Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Bragança", timezone: "Europe/Lisbon", tags: ["trás-os-montes", "rede-expressos", "regional", "mountain-interior"] },
  { id: "chaves-bus", name: "Chaves Otobüs Terminali", displayName: "Chaves Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Chaves", timezone: "Europe/Lisbon", tags: ["north-border", "thermal-spa", "rede-expressos", "regional"] },
  { id: "evora-bus", name: "Évora Otobüs Terminali (Terminal Rodoviário de Évora)", displayName: "Évora Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Évora", timezone: "Europe/Lisbon", tags: ["alentejo-capital", "unesco", "rede-expressos", "regional"] },
  { id: "beja-bus", name: "Beja Otobüs Terminali", displayName: "Beja Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Beja", timezone: "Europe/Lisbon", tags: ["alentejo-south", "rede-expressos", "regional"] },
  { id: "portalegre-bus", name: "Portalegre Otobüs Terminali", displayName: "Portalegre Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Portalegre", timezone: "Europe/Lisbon", tags: ["alentejo-border", "tapestry-museum", "rede-expressos", "regional"] },
  { id: "elvas-bus", name: "Elvas Otobüs Terminali", displayName: "Elvas Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Elvas", timezone: "Europe/Lisbon", tags: ["spain-border", "gualtar-rampartsunesco", "rede-expressos", "regional"] },
  { id: "setubal-bus", name: "Setúbal Otobüs Terminali", displayName: "Setúbal Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Setúbal", timezone: "Europe/Lisbon", tags: ["sado-estuary", "arrábida-access", "rede-expressos", "lisbon-commuter"] },
  { id: "funchal-bus", name: "Funchal Otobüs Terminali (Madeira)", displayName: "Funchal Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Funchal", timezone: "Atlantic/Madeira", tags: ["madeira", "horarios-do-funchal", "intercity-island", "airport-connection"] },
  { id: "ponta-delgada-bus", name: "Ponta Delgada Otobüs Terminali (Azorlar, São Miguel)", displayName: "Ponta Delgada Bus Terminal", country: "PT", countryCode: "PT", category: "bus", city: "Ponta Delgada", timezone: "Atlantic/Azores", tags: ["azores-main-island", "azoressul", "seta-azores", "airport-connection"] },

// ============================================================
// TOPLAM: 14 air + 40 rail + 18 sea + 31 bus = 103 kayıt
// Notlar:
// - Portekiz ana karasında uluslararası feribot yoktur; İspanya
//   veya Kuzey Afrika'ya bağlantı hava/yoluyladır. Feribotlar
//   yalnızca Azorlar (AtlânticLine) ve Madeira adaları arasıdır.
// - Madeira ve Azorlar'da demiryolu yoktur — ulaşım tamamen
//   hava + otobüs + feribotla sağlanır.
// - Lizbon yeni havalimanı projesi gündemdedir (mevcut Humberto
//   Delgado kapasite sınırında).
// - Lizbon-Madrid "Lusitânia Comboio Hotel" gece treni 2020'den
//   beri askıdadır (yeniden başlangıç tarihi belirsiz, 2024
//   itibariyla); CP + Renfe ortak işletmesiydi.
// - Beira Alta hattı (Guarda→Vilar Formoso→Salamanca/Madrid)
//   yolcu seferi askıda/çok sınırlı; Beira Baixa hattı (Lizbon-
//   Covilhã-Guarda) onarım nedeniyle kısmi hizmettedir —
//   alternatif olarak otobüs ikame eder.
// - Lizbon-Spain hızlı tren (Alta Velocidade) projesi
//   planlama aşamasındadır.
// - Porto'da tek büyük merkezi otogar yoktur: Campo 24 de Agosto
//   uzun süredir kapalı, seferler Campanhã + Casa da Música +
//   çeşitli kalkış noktalarından yapılır.
// - Rede Expressos serbestleşen pazarda hâlâ dominanttır;
//   FlixBus, Eva Transportes (Algarve), ALSA/Internorte
//   (uluslararası) diğer önemli oyunculardır.
// - Lizbon Oriente, Calatrava tasarımı (1998 Expo) Portekiz'in
//   en modern ulaşım hub'ıdır; Alfa Pendular'ın çoğu buradan
//   kalkar.
// - Bilgiler 2024-2025 itibariyle geçerlidir.
// ============================================================
