// ============================================================
// FreeBuff Travel — Romania (RO) destination entries
// Converted from: TravelApp_Romania.pdf
// NOTE: Landlocked on 3 sides — Black Sea coast is short; all
// non-Black-Sea "sea" records are Danube river piers. Rail
// operator: CFR Călători (+ Softrans, Regio Călători, Astra
// Trans Carpatic, TFC). 7 Mocăniță tourist narrow-gauge lines.
// ============================================================

// ---------- Paste into AIRPORTS (category: "air") ----------

  { id: "otp", name: "Henri Coandă International Airport (Bucharest / Otopeni)", displayName: "Bucharest (OTP)", country: "RO", countryCode: "RO", category: "air", city: "Bucharest", iata: "OTP", timezone: "Europe/Bucharest", tags: ["main-hub", "tarom", "blue-air-base", "wizz-air", "rail-planned", "bus-connection"] },
  { id: "bbu", name: "Aurel Vlaicu Airport (Bucharest / Băneasa)", displayName: "Bucharest (BBU)", country: "RO", countryCode: "RO", category: "air", city: "Bucharest", iata: "BBU", timezone: "Europe/Bucharest", tags: ["city-airport", "business-aviation", "limited-scheduled", "otp-secondary"] },
  { id: "clj", name: "Avram Iancu International Airport", displayName: "Cluj-Napoca (CLJ)", country: "RO", countryCode: "RO", category: "air", city: "Cluj-Napoca", iata: "CLJ", timezone: "Europe/Bucharest", tags: ["transylvania-hub", "second-busiest", "wizz-air", "blue-air", "it-city"] },
  { id: "tsr", name: "Traian Vuia International Airport", displayName: "Timișoara (TSR)", country: "RO", countryCode: "RO", category: "air", city: "Timișoara", iata: "TSR", timezone: "Europe/Bucharest", tags: ["western-romania", "wizz-air", "blue-air", "banat"] },
  { id: "ias", name: "Iași International Airport", displayName: "Iași (IAS)", country: "RO", countryCode: "RO", category: "air", city: "Iași", iata: "IAS", timezone: "Europe/Bucharest", tags: ["moldavia", "wizz-air", "blue-air", "growth"] },
  { id: "sbz", name: "Sibiu International Airport", displayName: "Sibiu (SBZ)", country: "RO", countryCode: "RO", category: "air", city: "Sibiu", iata: "SBZ", timezone: "Europe/Bucharest", tags: ["transylvania", "lufthansa-connections", "charter", "european-capital-of-culture-2007"] },
  { id: "bcm", name: "Bacău Airport - George Enescu", displayName: "Bacău (BCM)", country: "RO", countryCode: "RO", category: "air", city: "Bacău", iata: "BCM", timezone: "Europe/Bucharest", tags: ["moldavia", "romania-air-sports", "regional", "low-cost"] },
  { id: "cra", name: "Craiova Airport", displayName: "Craiova (CRA)", country: "RO", countryCode: "RO", category: "air", city: "Craiova", iata: "CRA", timezone: "Europe/Bucharest", tags: ["oltenia", "wizz-air", "regional"] },
  { id: "omr", name: "Oradea International Airport", displayName: "Oradea (OMR)", country: "RO", countryCode: "RO", category: "air", city: "Oradea", iata: "OMR", timezone: "Europe/Bucharest", tags: ["western-border", "wizz-air", "regional", "hungary-direction"] },
  { id: "scv", name: "Suceava - Ștefan cel Mare Airport", displayName: "Suceava (SCV)", country: "RO", countryCode: "RO", category: "air", city: "Suceava", iata: "SCV", timezone: "Europe/Bucharest", tags: ["bukovina", "regional", "salcea"] },
  { id: "tgm", name: "Târgu Mureș - Transilvania Airport", displayName: "Târgu Mureș (TGM)", country: "RO", countryCode: "RO", category: "air", city: "Târgu Mureș", iata: "TGM", timezone: "Europe/Bucharest", tags: ["transylvania", "wizz-air", "regional"] },
  { id: "suj", name: "Satu Mare Airport", displayName: "Satu Mare (SUJ)", country: "RO", countryCode: "RO", category: "air", city: "Satu Mare", iata: "SUJ", timezone: "Europe/Bucharest", tags: ["north-west", "regional", "hungary-border-area"] },
  { id: "bay", name: "Baia Mare Airport", displayName: "Baia Mare (BAY)", country: "RO", countryCode: "RO", category: "air", city: "Baia Mare", iata: "BAY", timezone: "Europe/Bucharest", tags: ["maramureș", "regional", "limited"] },
  { id: "cnd", name: "Constanța - Mihail Kogălniceanu Airport", displayName: "Constanța (CND)", country: "RO", countryCode: "RO", category: "air", city: "Constanța", iata: "CND", timezone: "Europe/Bucharest", tags: ["black-sea", "mangalia-adjacent", "regional", "military-shared"] },
  { id: "tce", name: "Tulcea - Delta Dunării Airport", displayName: "Tulcea (TCE)", country: "RO", countryCode: "RO", category: "air", city: "Tulcea", iata: "TCE", timezone: "Europe/Bucharest", tags: ["danube-delta", "unesco", "regional", "limited"] },
  { id: "arw", name: "Arad International Airport", displayName: "Arad (ARW)", country: "RO", countryCode: "RO", category: "air", city: "Arad", iata: "ARW", timezone: "Europe/Bucharest", tags: ["very-limited", "timisoara-competition", "cargo-general-aviation", "seasonal-charter"] },
  { id: "ghv", name: "Brașov-Ghimbav Airport", displayName: "Brașov (GHV)", country: "RO", countryCode: "RO", category: "air", city: "Brașov", iata: "GHV", timezone: "Europe/Bucharest", tags: ["new-2023", "transylvania-tourism", "designed-1m-capacity", "ski-access"] },

// ---------- Paste into RAIL_STATIONS (category: "rail") ----------

  { id: "bucuresti-nord-rail", name: "București Nord (Gara de Nord)", displayName: "Bucharest North Station", country: "RO", countryCode: "RO", category: "rail", city: "Bucharest", timezone: "Europe/Bucharest", tags: ["main-hub", "cfr-calatori", "softrans", "regio-calatori", "international-moldova-germany", "budapest-sofia-directions"] },
  { id: "bucuresti-obor-rail", name: "București Obor", displayName: "Bucharest Obor Station", country: "RO", countryCode: "RO", category: "rail", city: "Bucharest", timezone: "Europe/Bucharest", tags: ["east-bucharest", "regional", "urziceni-slobozia-calarasi-line", "cfr"] },
  { id: "bucuresti-basarab-rail", name: "București Basarab", displayName: "Bucharest Basarab Station", country: "RO", countryCode: "RO", category: "rail", city: "Bucharest", timezone: "Europe/Bucharest", tags: ["near-gara-de-nord", "limited-passenger", "maneuver-station", "cfr"] },
  { id: "cluj-napoca-rail", name: "Cluj-Napoca (Gara Cluj-Napoca)", displayName: "Cluj-Napoca Station", country: "RO", countryCode: "RO", category: "rail", city: "Cluj-Napoca", timezone: "Europe/Bucharest", tags: ["transylvania-hub", "cfr", "budapest-direction", "interregio"] },
  { id: "brasov-rail", name: "Brașov (Gara Brașov)", displayName: "Brașov Station", country: "RO", countryCode: "RO", category: "rail", city: "Brașov", timezone: "Europe/Bucharest", tags: ["transylvania", "cfr", "bucharest-line", "sinaia-prahova-valley"] },
  { id: "sibiu-rail", name: "Sibiu (Gara Sibiu)", displayName: "Sibiu Station", country: "RO", countryCode: "RO", category: "rail", city: "Sibiu", timezone: "Europe/Bucharest", tags: ["transylvania", "cfr", "medias-branch", "unesco-adjacent"] },
  { id: "sighisoara-rail", name: "Sighișoara (Gara Sighișoara)", displayName: "Sighișoara Station", country: "RO", countryCode: "RO", category: "rail", city: "Sighișoara", timezone: "Europe/Bucharest", tags: ["unesco-town", "cfr", "bucharest-cluj-line"] },
  { id: "medias-rail", name: "Mediaș (Gara Mediaș)", displayName: "Mediaș Station", country: "RO", countryCode: "RO", category: "rail", city: "Mediaș", timezone: "Europe/Bucharest", tags: ["transylvania", "cfr", "regional-branch"] },
  { id: "alba-iulia-rail", name: "Alba Iulia (Gara Alba Iulia)", displayName: "Alba Iulia Station", country: "RO", countryCode: "RO", category: "rail", city: "Alba Iulia", timezone: "Europe/Bucharest", tags: ["carolina-citadel", "cfr", "regional"] },
  { id: "targu-mures-rail", name: "Târgu Mureș (Gara Târgu Mureș)", displayName: "Târgu Mureș Station", country: "RO", countryCode: "RO", category: "rail", city: "Târgu Mureș", timezone: "Europe/Bucharest", tags: ["transylvania", "cfr", "regio", "cluj-line"] },
  { id: "sfantu-gheorghe-rail", name: "Sfântu Gheorghe (Gara Sfântu Gheorghe)", displayName: "Sfântu Gheorghe Station", country: "RO", countryCode: "RO", category: "rail", city: "Sfântu Gheorghe", timezone: "Europe/Bucharest", tags: ["covasna", "cfr", "regional"] },
  { id: "miercurea-ciuc-rail", name: "Miercurea Ciuc (Gara Miercurea Ciuc)", displayName: "Miercurea Ciuc Station", country: "RO", countryCode: "RO", category: "rail", city: "Miercurea Ciuc", timezone: "Europe/Bucharest", tags: ["harghita", "cfr", "siculeni-branch"] },
  { id: "bistrita-nord-rail", name: "Bistrița Nord (Gara Bistrița Nord)", displayName: "Bistrița Nord Station", country: "RO", countryCode: "RO", category: "rail", city: "Bistrița", timezone: "Europe/Bucharest", tags: ["regional", "cfr", "cluj-branch"] },
  { id: "timisoara-nord-rail", name: "Timișoara Nord (Gara Timișoara Nord)", displayName: "Timișoara North Station", country: "RO", countryCode: "RO", category: "rail", city: "Timișoara", timezone: "Europe/Bucharest", tags: ["western-hub", "cfr", "arad-budapest-line", "interregio"] },
  { id: "arad-rail", name: "Arad (Gara Arad)", displayName: "Arad Station", country: "RO", countryCode: "RO", category: "rail", city: "Arad", timezone: "Europe/Bucharest", tags: ["western-border", "cfr", "curtici-budapest-line", "international"] },
  { id: "curtici-rail", name: "Curtici (Gara Curtici)", displayName: "Curtici Station", country: "RO", countryCode: "RO", category: "rail", city: "Curtici", timezone: "Europe/Bucharest", tags: ["hungary-border", "passport-control-point", "cfr", "mav", "arad-lopshaza-budapest"] },
  { id: "oradea-rail", name: "Oradea (Gara Oradea)", displayName: "Oradea Station", country: "RO", countryCode: "RO", category: "rail", city: "Oradea", timezone: "Europe/Bucharest", tags: ["hungary-border-area", "cfr", "budapest-direct", "biharkeresztes-gate"] },
  { id: "deva-rail", name: "Deva (Gara Deva)", displayName: "Deva Station", country: "RO", countryCode: "RO", category: "rail", city: "Deva", timezone: "Europe/Bucharest", tags: ["hunedoara", "cfr", "interregio"] },
  { id: "hunedoara-rail", name: "Hunedoara (Gara Hunedoara)", displayName: "Hunedoara Station", country: "RO", countryCode: "RO", category: "rail", city: "Hunedoara", timezone: "Europe/Bucharest", tags: ["corvin-castle", "cfr", "regional-branch"] },
  { id: "lugoj-rail", name: "Lugoj (Gara Lugoj)", displayName: "Lugoj Station", country: "RO", countryCode: "RO", category: "rail", city: "Lugoj", timezone: "Europe/Bucharest", tags: ["timis-valley", "cfr", "regional"] },
  { id: "caransebes-rail", name: "Caransebeș (Gara Caransebeș)", displayName: "Caransebeș Station", country: "RO", countryCode: "RO", category: "rail", city: "Caransebeș", timezone: "Europe/Bucharest", tags: ["junction", "cfr", "resita-branch", "bucuresti-timisoara"] },
  { id: "resita-rail", name: "Reșița (Gara Reșița)", displayName: "Reșița Station", country: "RO", countryCode: "RO", category: "rail", city: "Reșița", timezone: "Europe/Bucharest", tags: ["end-of-branch", "cfr", "timisoara-via-caransebes", "industrial-heritage"] },
  { id: "iasi-rail", name: "Iași (Gara Iași)", displayName: "Iași Station", country: "RO", countryCode: "RO", category: "rail", city: "Iași", timezone: "Europe/Bucharest", tags: ["moldavia-capital", "cfr", "chisinau-direction-limited", "ungheni-transfer"] },
  { id: "ungheni-rail", name: "Ungheni (Gara Ungheni)", displayName: "Ungheni Station", country: "RO", countryCode: "RO", category: "rail", city: "Ungheni", timezone: "Europe/Bucharest", tags: ["moldova-border", "prut-river", "cfr", "gauge-change-point", "chisinau-transfer"] },
  { id: "suceava-rail", name: "Suceava (Gara Suceava / Burdujeni)", displayName: "Suceava Station (Burdujeni)", country: "RO", countryCode: "RO", category: "rail", city: "Suceava", timezone: "Europe/Bucharest", tags: ["bukovina", "cfr", "cernivci-direction-seasonal-war-affected"] },
  { id: "bacau-rail", name: "Bacău (Gara Bacău)", displayName: "Bacău Station", country: "RO", countryCode: "RO", category: "rail", city: "Bacău", timezone: "Europe/Bucharest", tags: ["moldavia", "cfr", "interregio", "roman-junction"] },
  { id: "roman-rail", name: "Roman (Gara Roman)", displayName: "Roman Station", country: "RO", countryCode: "RO", category: "rail", city: "Roman", timezone: "Europe/Bucharest", tags: ["junction", "bucuresti-suceava-iasi-split", "cfr"] },
  { id: "piatra-neamt-rail", name: "Piatra Neamț (Gara Piatra Neamț)", displayName: "Piatra Neamț Station", country: "RO", countryCode: "RO", category: "rail", city: "Piatra Neamț", timezone: "Europe/Bucharest", tags: ["neamț", "cfr", "branch", "bicaz-gorge-direction"] },
  { id: "galati-rail", name: "Galați (Gara Galați)", displayName: "Galați Station", country: "RO", countryCode: "RO", category: "rail", city: "Galați", timezone: "Europe/Bucharest", tags: ["danube-port-city", "cfr", "braila-ferry-link"] },
  { id: "braila-rail", name: "Brăila (Gara Brăila)", displayName: "Brăila Station", country: "RO", countryCode: "RO", category: "rail", city: "Brăila", timezone: "Europe/Bucharest", tags: ["danube", "cfr", "regional", "galati-link"] },
  { id: "focsani-rail", name: "Focșani (Gara Focșani)", displayName: "Focșani Station", country: "RO", countryCode: "RO", category: "rail", city: "Focșani", timezone: "Europe/Bucharest", tags: ["vrancea", "cfr", "bucuresti-iasi-line"] },
  { id: "botosani-rail", name: "Botoșani (Gara Botoșani)", displayName: "Botoșani Station", country: "RO", countryCode: "RO", category: "rail", city: "Botoșani", timezone: "Europe/Bucharest", tags: ["north-east", "cfr", "regional-branch"] },
  { id: "vaslui-rail", name: "Vaslui (Gara Vaslui)", displayName: "Vaslui Station", country: "RO", countryCode: "RO", category: "rail", city: "Vaslui", timezone: "Europe/Bucharest", tags: ["moldavia-east", "cfr", "iasi-bucuresti-line"] },
  { id: "constanta-rail", name: "Constanța (Gara Constanța)", displayName: "Constanța Station", country: "RO", countryCode: "RO", category: "rail", city: "Constanța", timezone: "Europe/Bucharest", tags: ["black-sea-terminus", "cfr", "mangalia-summer-intensive", "bucharest-ic"] },
  { id: "mangalia-rail", name: "Mangalia (Gara Mangalia)", displayName: "Mangalia Station", country: "RO", countryCode: "RO", category: "rail", city: "Mangalia", timezone: "Europe/Bucharest", tags: ["black-sea-resorts", "constanta-line", "cfr", "regional"] },
  { id: "medgidia-rail", name: "Medgidia (Gara Medgidia)", displayName: "Medgidia Station", country: "RO", countryCode: "RO", category: "rail", city: "Medgidia", timezone: "Europe/Bucharest", tags: ["junction", "constantinople-line", "cfr", "baltchik-direction"] },
  { id: "tulcea-rail", name: "Tulcea (Gara Tulcea)", displayName: "Tulcea Station", country: "RO", countryCode: "RO", category: "rail", city: "Tulcea", timezone: "Europe/Bucharest", tags: ["danube-delta", "cfr", "regional", "narrow-gauge-mocanita-adjacent"] },
  { id: "craiova-rail", name: "Craiova (Gara Craiova)", displayName: "Craiova Station", country: "RO", countryCode: "RO", category: "rail", city: "Craiova", timezone: "Europe/Bucharest", tags: ["oltenia-hub", "cfr", "bucuresti-line", "timisoara-line"] },
  { id: "pitesti-rail", name: "Pitești (Gara Pitești)", displayName: "Pitești Station", country: "RO", countryCode: "RO", category: "rail", city: "Pitești", timezone: "Europe/Bucharest", tags: ["arges", "cfr", "bucuresti-craiova-line", "dacia-city"] },
  { id: "ramnicu-valcea-rail", name: "Râmnicu Vâlcea (Gara Râmnicu Vâlcea)", displayName: "Râmnicu Vâlcea Station", country: "RO", countryCode: "RO", category: "rail", city: "Râmnicu Vâlcea", timezone: "Europe/Bucharest", tags: ["oltenia-north", "cfr", "regio", "oceatului-line"] },
  { id: "drobeta-turnu-severin-rail", name: "Drobeta-Turnu Severin (Gara D. T. Severin)", displayName: "Drobeta-Turnu Severin Station", country: "RO", countryCode: "RO", category: "rail", city: "Drobeta-Turnu Severin", timezone: "Europe/Bucharest", tags: ["iron-gates", "cfr", "bucharest-line", "trajan-bridge-history"] },
  { id: "targu-jiu-rail", name: "Târgu Jiu (Gara Târgu Jiu)", displayName: "Târgu Jiu Station", country: "RO", countryCode: "RO", category: "rail", city: "Târgu Jiu", timezone: "Europe/Bucharest", tags: ["gheorghe-tattescu-sculpture-city", "cfr", "regional", "brancusi"] },
  { id: "petroani-rail", name: "Petroșani (Gara Petroșani)", displayName: "Petroșani Station", country: "RO", countryCode: "RO", category: "rail", city: "Petroșani", timezone: "Europe/Bucharest", tags: ["jiu-valley", "cfr", "mining-region", "regional"] },
  { id: "ploiesti-rail", name: "Ploiești (Gara Ploiești Sud & Ploiești Vest)", displayName: "Ploiești Station (South & West)", country: "RO", countryCode: "RO", category: "rail", city: "Ploiești", timezone: "Europe/Bucharest", tags: ["north-junction", "cfr", "brasov-moldova-split", "sinaia-campina"] },
  { id: "buzau-rail", name: "Buzău (Gara Buzău)", displayName: "Buzău Station", country: "RO", countryCode: "RO", category: "rail", city: "Buzău", timezone: "Europe/Bucharest", tags: ["cfr", "bucuresti-braila-line", "regional"] },
  { id: "faurei-rail", name: "Făurei (Gara Făurei)", displayName: "Făurei Station", country: "RO", countryCode: "RO", category: "rail", city: "Făurei", timezone: "Europe/Bucharest", tags: ["junction", "cfr", "bucuresti-constanta-braila-split"] },
  { id: "roiori-de-vede-rail", name: "Roșiori de Vede (Gara Roșiori)", displayName: "Roșiori de Vede Station", country: "RO", countryCode: "RO", category: "rail", city: "Roșiori de Vede", timezone: "Europe/Bucharest", tags: ["teleorman", "cfr", "regional"] },
  { id: "giurgiu-rail", name: "Giurgiu (Gara Giurgiu Nord)", displayName: "Giurgiu Nord Station", country: "RO", countryCode: "RO", category: "rail", city: "Giurgiu", timezone: "Europe/Bucharest", tags: ["danube-ruse-border", "cfr", "bulgaria-connection", "bridge"] },
  { id: "satu-mare-rail", name: "Satu Mare (Gara Satu Mare)", displayName: "Satu Mare Station", country: "RO", countryCode: "RO", category: "rail", city: "Satu Mare", timezone: "Europe/Bucharest", tags: ["north-west", "cfr", "regional"] },
  { id: "baia-mare-rail", name: "Baia Mare (Gara Baia Mare)", displayName: "Baia Mare Station", country: "RO", countryCode: "RO", category: "rail", city: "Baia Mare", timezone: "Europe/Bucharest", tags: ["maramureș", "cfr", "regional", "jibou-branch"] },
  { id: "sighetu-marmatiei-rail", name: "Sighetu Marmației (Gara Sighetu Marmației)", displayName: "Sighetu Marmației Station", country: "RO", countryCode: "RO", category: "rail", city: "Sighetu Marmației", timezone: "Europe/Bucharest", tags: ["maramureș-wooden-churches", "cfr", "terminus", "ukraine-border-area"] },
  { id: "vatra-dornei-rail", name: "Vatra Dornei (Gara Vatra Dornei)", displayName: "Vatra Dornei Station", country: "RO", countryCode: "RO", category: "rail", city: "Vatra Dornei", timezone: "Europe/Bucharest", tags: ["spa-town", "cfr", "bucovina-mountains"] },
  { id: "jibou-rail", name: "Jibou (Gara Jibou)", displayName: "Jibou Station", country: "RO", countryCode: "RO", category: "rail", city: "Jibou", timezone: "Europe/Bucharest", tags: ["junction", "cfr", "salaj", "baia-mare-branch"] },
  { id: "dej-rail", name: "Dej (Gara Dej Călători)", displayName: "Dej Station", country: "RO", countryCode: "RO", category: "rail", city: "Dej", timezone: "Europe/Bucharest", tags: ["junction", "cfr", "cluj-baia-mare-split", "someșul-line"] },
  { id: "simeria-rail", name: "Simeria (Gara Simeria)", displayName: "Simeria Station", country: "RO", countryCode: "RO", category: "rail", city: "Simeria", timezone: "Europe/Bucharest", tags: ["junction", "cfr", "hunedoara-branch", "arlovas-line"] },
  { id: "adjud-rail", name: "Adjud (Gara Adjud)", displayName: "Adjud Station", country: "RO", countryCode: "RO", category: "rail", city: "Adjud", timezone: "Europe/Bucharest", tags: ["junction", "cfr", "bucuresti-iasi-buzau-split"] },
  { id: "pascani-rail", name: "Pașcani (Gara Pașcani)", displayName: "Pașcani Station", country: "RO", countryCode: "RO", category: "rail", city: "Pașcani", timezone: "Europe/Bucharest", tags: ["junction", "cfr", "iasi-suceava-line"] },
  { id: "copsa-mica-rail", name: "Copșa Mică (Gara Copșa Mică)", displayName: "Copșa Mică Station", country: "RO", countryCode: "RO", category: "rail", city: "Copșa Mică", timezone: "Europe/Bucharest", tags: ["junction", "cfr", "medias-sibiu-line", "industrial-history"] },
  { id: "fetesti-rail", name: "Fetești (Gara Fetești)", displayName: "Fetești Station", country: "RO", countryCode: "RO", category: "rail", city: "Fetești", timezone: "Europe/Bucharest", tags: ["danube-bridge", "cfr", "bucuresti-constantinople-line"] },
  { id: "mocanita-vieului-de-sus-rail", name: "Mocănița Vișeu de Sus - Valea Vaserului", displayName: "Mocănița Vișeu de Sus Steam Railway", country: "RO", countryCode: "RO", category: "rail", city: "Vișeu de Sus", timezone: "Europe/Bucharest", tags: ["tourist-heritage-railway", "760mm-narrow-gauge", "steam", "last-working-forest-railway-europe", "vaser-valley-21km", "year-round-summer-peak", "unesco-tentative"] },
  { id: "mocanita-moldovita-rail", name: "Mocănița Moldovița", displayName: "Mocănița Moldovița Railway", country: "RO", countryCode: "RO", category: "rail", city: "Moldovița", timezone: "Europe/Bucharest", tags: ["tourist-heritage-railway", "bukovina", "unesco-painted-monasteries-nearby", "summer-only", "argel-moldovita-12km"] },
  { id: "mocanita-hutulca-rail", name: "Mocănița Hutulca (Câmpulung Moldovenesc)", displayName: "Mocănița Hutulca Railway", country: "RO", countryCode: "RO", category: "rail", city: "Câmpulung Moldovenesc", timezone: "Europe/Bucharest", tags: ["tourist-heritage-railway", "bukovina", "summer-only", "narrow-gauge"] },
  { id: "mocanita-sibiu-rail", name: "Mocănița Sibiu - Cisnădie (Hârtibaci valley)", displayName: "Mocănița Sibiu-Cisnădie Railway", country: "RO", countryCode: "RO", category: "rail", city: "Cisnădie", timezone: "Europe/Bucharest", tags: ["tourist-heritage-railway", "hartibaci-valley", "revival-project", "limited-service"] },
  { id: "mocanita-agnita-rail", name: "Mocănița Agnita - Sibiu (eski hat)", displayName: "Mocănița Agnita-Sibiu Railway (Old Line)", country: "RO", countryCode: "RO", category: "rail", city: "Agnita", timezone: "Europe/Bucharest", tags: ["tourist-heritage-railway", "former-line", "revival-attempts", "limited"] },
  { id: "mocanita-covasna-rail", name: "Mocănița Covasna - Comandău", displayName: "Mocănița Covasna-Comandău Railway", country: "RO", countryCode: "RO", category: "rail", city: "Covasna", timezone: "Europe/Bucharest", tags: ["tourist-heritage-railway", "tusnad-direction", "narrow-gauge", "seasonal"] },
  { id: "mocanita-brad-rail", name: "Mocănița Brad - Crișcior", displayName: "Mocănița Brad-Crișcior Railway", country: "RO", countryCode: "RO", category: "rail", city: "Brad", timezone: "Europe/Bucharest", tags: ["tourist-heritage-railway", "hunedoara", "narrow-gauge", "seasonal"] },

// ---------- Paste into FERRY_PORTS (category: "sea") ----------

  { id: "constanta-port", name: "Constanța Limanı - Kruvaziyer Terminali", displayName: "Constanța Cruise Terminal", country: "RO", countryCode: "RO", category: "sea", city: "Constanța", timezone: "Europe/Bucharest", tags: ["black-sea-main-port", "cruise", "cargo-major", "mamaia-access"] },
  { id: "mangalia-port", name: "Mangalia Limanı", displayName: "Mangalia Port", country: "RO", countryCode: "RO", category: "sea", city: "Mangalia", timezone: "Europe/Bucharest", tags: ["black-sea-south", "resorts", "shipyard", "limited-passenger"] },
  { id: "tulcea-port", name: "Tulcea - Tuna Deltası Feribot/Gemi İskelesi", displayName: "Tulcea Danube Delta Pier", country: "RO", countryCode: "RO", category: "sea", city: "Tulcea", timezone: "Europe/Bucharest", tags: ["danube-delta-unesco", "delta-boat-tours", "fantanile-narii-ferry", "regional"] },
  { id: "galati-port", name: "Galați - Tuna Nehir İskelesi", displayName: "Galați Danube Pier", country: "RO", countryCode: "RO", category: "sea", city: "Galați", timezone: "Europe/Bucharest", tags: ["danube-river-cruise", "a-rosa", "nicko-cruises", "braila-ferry-local", "moldova-giurgiulesti-no-regular-ferry"] },
  { id: "braila-port", name: "Brăila - Tuna Nehir İskelesi", displayName: "Brăila Danube Pier", country: "RO", countryCode: "RO", category: "sea", city: "Brăila", timezone: "Europe/Bucharest", tags: ["danube-river-cruise-stop", "no-regular-ferry", "galati-local-crossing"] },
  { id: "giurgiu-port", name: "Giurgiu - Tuna Nehir İskelesi", displayName: "Giurgiu Danube Pier", country: "RO", countryCode: "RO", category: "sea", city: "Giurgiu", timezone: "Europe/Bucharest", tags: ["danube", "ruse-bulgaria-opposite", "bridge", "limited-river-services"] },
  { id: "drobeta-port", name: "Drobeta-Turnu Severin - Tuna Nehir İskelesi", displayName: "Drobeta-Turnu Severin Danube Pier", country: "RO", countryCode: "RO", category: "sea", city: "Drobeta-Turnu Severin", timezone: "Europe/Bucharest", tags: ["iron-gates", "danube-river-cruise", "iron-gate-1-dam", "dragasani-gate"] },
  { id: "orsova-port", name: "Orșova - Tuna", displayName: "Orșova Danube Port", country: "RO", countryCode: "RO", category: "sea", city: "Orșova", timezone: "Europe/Bucharest", tags: ["iron-gates-center", "danube-river-cruise", "mehadia-direction"] },
  { id: "calafat-port", name: "Calafat - Tuna Geçidi", displayName: "Calafat Danube Crossing", country: "RO", countryCode: "RO", category: "sea", city: "Calafat", timezone: "Europe/Bucharest", tags: ["vidin-bulgaria-opposite", "calafat-vidin-bridge-2013", "former-ferry-now-bridge", "rail-road"] },
  { id: "bechet-port", name: "Bechet - Tuna Geçidi", displayName: "Bechet Danube Crossing", country: "RO", countryCode: "RO", category: "sea", city: "Bechet", timezone: "Europe/Bucharest", tags: ["oreahovo-bulgaria-opposite", "small-car-ferry", "variable-season", "municipal"] },
  { id: "zimnicea-port", name: "Zimnicea - Tuna Geçidi", displayName: "Zimnicea Danube Crossing", country: "RO", countryCode: "RO", category: "sea", city: "Zimnicea", timezone: "Europe/Bucharest", tags: ["small-crossing", "bulgaria-opposite", "local", "variable"] },
  { id: "turnu-magurele-port", name: "Turnu Măgurele - Tuna Geçidi", displayName: "Turnu Măgurele Danube Crossing", country: "RO", countryCode: "RO", category: "sea", city: "Turnu Măgurele", timezone: "Europe/Bucharest", tags: ["nikopol-bulgaria-opposite", "small-ferry", "local", "variable"] },
  { id: "sulina-port", name: "Sulina - Tuna Deltası", displayName: "Sulina Danube Delta Port", country: "RO", countryCode: "RO", category: "sea", city: "Sulina", timezone: "Europe/Bucharest", tags: ["danube-mouth-black-sea", "delta-tour-boats", "black-sea-cruise-rare", "europe-easternmost-point-nearby"] },

// ---------- Paste into BUS_HUBS (category: "bus") ----------

  { id: "bucuresti-militari-bus", name: "Autogara Militari (Autogara Păcii)", displayName: "Bucharest Militari Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Bucharest", timezone: "Europe/Bucharest", tags: ["main-terminal", "flixbus", "international", "domestic"] },
  { id: "bucuresti-rahova-bus", name: "Autogara Rahova (Autogara Filaret civarı)", displayName: "Bucharest Rahova Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Bucharest", timezone: "Europe/Bucharest", tags: ["domestic", "regional-south", "multiple-operators"] },
  { id: "bucuresti-obor-bus", name: "Autogara Obor", displayName: "Bucharest Obor Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Bucharest", timezone: "Europe/Bucharest", tags: ["domestic", "moldova-direction", "regional"] },
  { id: "bucuresti-titan-bus", name: "Autogara Titan", displayName: "Bucharest Titan Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Bucharest", timezone: "Europe/Bucharest", tags: ["domestic", "regional"] },
  { id: "bucuresti-other-bus", name: "Autogara Drumul Taberei / Diğer Kalkış Noktaları", displayName: "Bucharest Other Terminals/Pickups", country: "RO", countryCode: "RO", category: "bus", city: "Bucharest", timezone: "Europe/Bucharest", tags: ["multiple-small-stops", "companies-own-offices", "flixbus-various-stops"] },
  { id: "cluj-napoca-bus", name: "Autogara Cluj-Napoca (Beta, Fany vb.)", displayName: "Cluj-Napoca Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Cluj-Napoca", timezone: "Europe/Bucharest", tags: ["transylvania-hub", "multiple-terminals", "beta", "fany", "international"] },
  { id: "brasov-bus", name: "Autogara Brașov", displayName: "Brașov Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Brașov", timezone: "Europe/Bucharest", tags: ["transylvania", "tourism", "domestic", "international"] },
  { id: "sibiu-bus", name: "Autogara Sibiu", displayName: "Sibiu Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Sibiu", timezone: "Europe/Bucharest", tags: ["transylvania", "atlassib-hq", "flixbus", "fany", "germany-austria-hungary-italy-spain"] },
  { id: "targu-mures-bus", name: "Autogara Târgu Mureș", displayName: "Târgu Mureș Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Târgu Mureș", timezone: "Europe/Bucharest", tags: ["transylvania", "flixbus", "fany", "budapest-vienna-germany"] },
  { id: "alba-iulia-bus", name: "Autogara Alba Iulia", displayName: "Alba Iulia Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Alba Iulia", timezone: "Europe/Bucharest", tags: ["carolina-citadel", "domestic", "international-germany-austria-hungary"] },
  { id: "sighisoara-bus", name: "Autogara Sighișoara", displayName: "Sighișoara Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Sighișoara", timezone: "Europe/Bucharest", tags: ["unesco-town", "domestic", "regional"] },
  { id: "bistrita-bus", name: "Autogara Bistrița", displayName: "Bistrița Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Bistrița", timezone: "Europe/Bucharest", tags: ["transylvania-north", "domestic"] },
  { id: "timisoara-bus", name: "Autogara Timișoara", displayName: "Timișoara Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Timișoara", timezone: "Europe/Bucharest", tags: ["western-hub", "international", "flixbus", "germany-hungary-serbia"] },
  { id: "arad-bus", name: "Autogara Arad", displayName: "Arad Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Arad", timezone: "Europe/Bucharest", tags: ["western-border", "international", "hungary-lines"] },
  { id: "oradea-bus", name: "Autogara Oradea", displayName: "Oradea Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Oradea", timezone: "Europe/Bucharest", tags: ["hungary-border", "international", "budapest-lines"] },
  { id: "deva-bus", name: "Autogara Deva", displayName: "Deva Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Deva", timezone: "Europe/Bucharest", tags: ["hunedoara", "domestic", "regional"] },
  { id: "resita-bus", name: "Autogara Reșița", displayName: "Reșița Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Reșița", timezone: "Europe/Bucharest", tags: ["banat-east", "domestic", "regional"] },
  { id: "iasi-bus", name: "Autogara Iași", displayName: "Iași Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Iași", timezone: "Europe/Bucharest", tags: ["moldavia-capital", "international", "chisinau-lines", "domestic"] },
  { id: "suceava-bus", name: "Autogara Suceava", displayName: "Suceava Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Suceava", timezone: "Europe/Bucharest", tags: ["bukovina", "domestic", "international"] },
  { id: "bacau-bus", name: "Autogara Bacău", displayName: "Bacău Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Bacău", timezone: "Europe/Bucharest", tags: ["moldavia", "domestic", "international"] },
  { id: "piatra-neamt-bus", name: "Autogara Piatra Neamț", displayName: "Piatra Neamț Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Piatra Neamț", timezone: "Europe/Bucharest", tags: ["neamț", "domestic", "bicaz-gorge-access"] },
  { id: "botosani-bus", name: "Autogara Botoșani", displayName: "Botoșani Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Botoșani", timezone: "Europe/Bucharest", tags: ["north-east", "domestic"] },
  { id: "vaslui-bus", name: "Autogara Vaslui", displayName: "Vaslui Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Vaslui", timezone: "Europe/Bucharest", tags: ["moldavia-east", "domestic"] },
  { id: "galati-bus", name: "Autogara Galați", displayName: "Galați Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Galați", timezone: "Europe/Bucharest", tags: ["danube", "domestic", "braila-link"] },
  { id: "braila-bus", name: "Autogara Brăila", displayName: "Brăila Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Brăila", timezone: "Europe/Bucharest", tags: ["danube", "domestic", "regional"] },
  { id: "focsani-bus", name: "Autogara Focșani", displayName: "Focșani Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Focșani", timezone: "Europe/Bucharest", tags: ["vrancea", "domestic", "regional"] },
  { id: "constanta-bus", name: "Autogara Constanța", displayName: "Constanța Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Constanța", timezone: "Europe/Bucharest", tags: ["black-sea", "summer-peak", "domestic", "international"] },
  { id: "craiova-bus", name: "Autogara Craiova", displayName: "Craiova Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Craiova", timezone: "Europe/Bucharest", tags: ["oltenia-hub", "domestic", "international"] },
  { id: "pitesti-bus", name: "Autogara Pitești", displayName: "Pitești Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Pitești", timezone: "Europe/Bucharest", tags: ["arges", "domestic", "regional"] },
  { id: "ploiesti-bus", name: "Autogara Ploiești", displayName: "Ploiești Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Ploiești", timezone: "Europe/Bucharest", tags: ["prahova", "domestic", "regional"] },
  { id: "targoviste-bus", name: "Autogara Târgoviște", displayName: "Târgoviște Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Târgoviște", timezone: "Europe/Bucharest", tags: ["dambovita", "domestic", "regional"] },
  { id: "ramnicu-valcea-bus", name: "Autogara Râmnicu Vâlcea", displayName: "Râmnicu Vâlcea Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Râmnicu Vâlcea", timezone: "Europe/Bucharest", tags: ["oltenia-north", "domestic", "germany-italy-lines"] },
  { id: "targu-jiu-bus", name: "Autogara Târgu Jiu", displayName: "Târgu Jiu Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Târgu Jiu", timezone: "Europe/Bucharest", tags: ["brancusi-sculptures", "domestic"] },
  { id: "drobeta-bus", name: "Autogara Drobeta-Turnu Severin", displayName: "Drobeta-Turnu Severin Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Drobeta-Turnu Severin", timezone: "Europe/Bucharest", tags: ["iron-gates", "domestic", "regional"] },
  { id: "slobozia-bus", name: "Autogara Slobozia", displayName: "Slobozia Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Slobozia", timezone: "Europe/Bucharest", tags: ["calarasi", "domestic", "regional"] },
  { id: "calarasi-bus", name: "Autogara Călărași", displayName: "Călărași Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Călărași", timezone: "Europe/Bucharest", tags: ["danube", "domestic", "bulgaria-direction"] },
  { id: "giurgiu-bus", name: "Autogara Giurgiu", displayName: "Giurgiu Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Giurgiu", timezone: "Europe/Bucharest", tags: ["danube-ruse-border", "bulgaria-connection", "domestic"] },
  { id: "alexandria-bus", name: "Autogara Alexandria", displayName: "Alexandria Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Alexandria", timezone: "Europe/Bucharest", tags: ["teleorman", "domestic"] },
  { id: "buzau-bus", name: "Autogara Buzău", displayName: "Buzău Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Buzău", timezone: "Europe/Bucharest", tags: ["domestic", "regional"] },
  { id: "baia-mare-bus", name: "Autogara Baia Mare", displayName: "Baia Mare Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Baia Mare", timezone: "Europe/Bucharest", tags: ["maramureș", "domestic"] },
  { id: "satu-mare-bus", name: "Autogara Satu Mare", displayName: "Satu Mare Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Satu Mare", timezone: "Europe/Bucharest", tags: ["north-west", "domestic", "international"] },
  { id: "sighetu-bus", name: "Autogara Sighetu Marmației", displayName: "Sighetu Marmației Terminal", country: "RO", countryCode: "RO", category: "bus", city: "Sighetu Marmației", timezone: "Europe/Bucharest", tags: ["maramureș", "domestic", "regional"] },

// ============================================================
// TOPLAM: 17 air + 66 rail + 13 sea + 42 bus = 138 kayıt
// Notlar:
// - Romanya karasız değildir ama Karadeniz kıyısı kısadır; deniz
//   kayıtlarının çoğu Tuna nehri iskelesi/geçididir. Düzenli
//   uluslararası feribot yok denecek kadar azdır.
// - Calafat-Vidin Köprüsü (2013) açıldıktan sonra Calafat
//   feribotu durduruldu; Bechet/Zimnicea/Turnu Măgurele küçük
//   çaplı arabalı geçişlerle sınırlıdır.
// - Demiryolu ağı eski ve yavaştır; AB fonlarıyla modernizasyon
//   projeleri sürüyor. Belgrad-Budapeşte hızlı treni gibi
//   bölgesel mega projeler Romania'yı da etkileyecektir.
// - Bükreş-Chişinu treni bazı dönemlerde çalışır (Ungheni
//   aktarmalı, Prut nehri sınırı); Suceava-Cernivci (Ukrayna)
//   bağlantısı savaş nedeniyle askıda olabilir.
// - Timişoara-Belgrad doğrudan hat çok sınırlıdır (Vršac
//   üzerinden dönemsel bağlantı).
// - Mocăniță: 7 adet 760 mm turistik buharlı dar hatlı tren;
//   en ünlüsü Vişeu de Sus-Paltin (Avrupa'da hâlâ çalışan son
//   orman demiryollarından biri, UNESCO geçici liste).
// - Brașov-Ghimbav havalimanı 2023'te açıldı (~1M tasarım
//   kapasitesi); Arad çok düşük sivil trafiğe sahiptir.
// - Bilgiler 2024-2025 itibariyle geçerlidir.
// ============================================================
