// ============================================================
// FreeBuff Travel — Sweden (SE) destination entries
// Converted from: TravelApp_Sweden.pdf
// NOTE: Rich ferry network (Baltic + North Sea + lakes). Main
// rail operators: SJ, Västrec Tåg, Norrtåg, Krönatågen, Öresundståg.
// FlixBus acquired Swebus — dominant long-distance bus player.
// Bromma (BMA) and Göteborg City (GSE) airports are CLOSED.
// ============================================================

// ---------- Paste into AIRPORTS (category: "air") ----------

  { id: "arn", name: "Stockholm Arlanda Airport", displayName: "Stockholm (ARN)", country: "SE", countryCode: "SE", category: "air", city: "Stockholm", iata: "ARN", timezone: "Europe/Stockholm", tags: ["main-hub", "25-27m-passengers", "sas-base", "norwegian", "arlanda-express", "rail-connected"] },
  { id: "nyo", name: "Stockholm Skavsta Airport", displayName: "Stockholm Skavsta (NYO)", country: "SE", countryCode: "SE", category: "air", city: "Stockholm", iata: "NYO", timezone: "Europe/Stockholm", tags: ["low-cost", "ryanair-base", "wizz-air", "2-2-5m-passengers", "south-sweden", "airport-coach"] },
  { id: "bma", name: "Stockholm Bromma Airport", displayName: "Stockholm Bromma (BMA)", country: "SE", countryCode: "SE", category: "air", city: "Stockholm", iata: "BMA", timezone: "Europe/Stockholm", tags: ["closed", "city-airport-historical", "former-business-aviation"] },
  { id: "got", name: "Göteborg Landvetter Airport", displayName: "Göteborg (GOT)", country: "SE", countryCode: "SE", category: "air", city: "Göteborg", iata: "GOT", timezone: "Europe/Stockholm", tags: ["second-busiest", "6-5-7m-passengers", "west-coast", "flygbussarna-coach"] },
  { id: "gse", name: "Göteborg City Airport (Säve)", displayName: "Göteborg City (GSE)", country: "SE", countryCode: "SE", category: "air", city: "Göteborg", iata: "GSE", timezone: "Europe/Stockholm", tags: ["closed", "former-low-cost", "save-aerodrome-historical"] },
  { id: "mmx", name: "Malmö Sturup Airport", displayName: "Malmö (MMX)", country: "SE", countryCode: "SE", category: "air", city: "Malmö", iata: "MMX", timezone: "Europe/Stockholm", tags: ["skane-main", "2-5-3m-passengers", "wizz-air-base", "ryanair", "copenhagen-competition-30km", "low-cost"] },
  { id: "lla", name: "Luleå Airport (Kallax)", displayName: "Luleå (LLA)", country: "SE", countryCode: "SE", category: "air", city: "Luleå", iata: "LLA", timezone: "Europe/Stockholm", tags: ["norrland-north", "1-2-1-5m-passengers", "space-city", "baltic-coast"] },
  { id: "ume", name: "Umeå Airport", displayName: "Umeå (UME)", country: "SE", countryCode: "SE", category: "air", city: "Umeå", iata: "UME", timezone: "Europe/Stockholm", tags: ["vasterbotten", "1-1-2m-passengers", "university-city", "sas-norwegian"] },
  { id: "krn", name: "Kiruna Airport", displayName: "Kiruna (KRN)", country: "SE", countryCode: "SE", category: "air", city: "Kiruna", iata: "KRN", timezone: "Europe/Stockholm", tags: ["arctic", "ice-hotel", "mine-subsidence-relocation", "sas-norwegian", "northern-lights"] },
  { id: "gev", name: "Gällivare/Malmberget Airport", displayName: "Gällivare (GEV)", country: "SE", countryCode: "SE", category: "air", city: "Gällivare", iata: "GEV", timezone: "Europe/Stockholm", tags: ["norrland", "lkab-mining", "dunderkliffen", "regional"] },
  { id: "pja", name: "Pajala Airport", displayName: "Pajala (PJA)", country: "SE", countryCode: "SE", category: "air", city: "Pajala", iata: "PJA", timezone: "Europe/Stockholm", tags: ["far-north", "subsidized-route", "northern-lapland", "regional"] },
  { id: "ajr", name: "Arvidsjaur Airport", displayName: "Arvidsjaur (AJR)", country: "SE", countryCode: "SE", category: "air", city: "Arvidsjaur", iata: "AJR", timezone: "Europe/Stockholm", tags: ["norrland", "winter-testing-hub", "subsidized", "regional"] },
  { id: "hmv", name: "Hemavan/Tärnaby Airport", displayName: "Hemavan (HMV)", country: "SE", countryCode: "SE", category: "air", city: "Hemavan", iata: "HMV", timezone: "Europe/Stockholm", tags: ["lapland-south", "ski-resort", "subsidized", "klövsjö-direction"] },
  { id: "lyc", name: "Lycksele Airport", displayName: "Lycksele (LYC)", country: "SE", countryCode: "SE", category: "air", city: "Lycksele", iata: "LYC", timezone: "Europe/Stockholm", tags: ["vasterbotten", "amapola-flyg-subsidized", "stockholm-arlanda", "10-15k-passengers"] },
  { id: "vhm", name: "Vilhelmina Airport", displayName: "Vilhelmina (VHM)", country: "SE", countryCode: "SE", category: "air", city: "Vilhelmina", iata: "VHM", timezone: "Europe/Stockholm", tags: ["lapland", "subsidized", "5-10k-passengers", "regional"] },
  { id: "sqo", name: "Storuman Airport (Gunnarn)", displayName: "Storuman (SQO)", country: "SE", countryCode: "SE", category: "air", city: "Storuman", iata: "SQO", timezone: "Europe/Stockholm", tags: ["lapland-south", "regional", "subsidized"] },
  { id: "oer", name: "Örnsköldsvik/Gideå Airport", displayName: "Örnsköldsvik (OER)", country: "SE", countryCode: "SE", category: "air", city: "Örnsköldsvik", iata: "OER", timezone: "Europe/Stockholm", tags: ["high-coast", "regional", "subsidized"] },
  { id: "sdl", name: "Sundsvall-Timrå Airport (Midlanda)", displayName: "Sundsvall (SDL)", country: "SE", countryCode: "SE", category: "air", city: "Sundsvall", iata: "SDL", timezone: "Europe/Stockholm", tags: ["medelpad", "0-4-0-5m-passengers", "regional", "sas"] },
  { id: "krf", name: "Kramfors-Sollefteå Airport (Höga Kusten Airport)", displayName: "Kramfors (KRF)", country: "SE", countryCode: "SE", category: "air", city: "Kramfors", iata: "KRF", timezone: "Europe/Stockholm", tags: ["high-coast-unesco", "regional", "subsidized"] },
  { id: "osd", name: "Östersund/Åre Airport (Frösön)", displayName: "Östersund/Åre (OSD)", country: "SE", countryCode: "SE", category: "air", city: "Östersund", iata: "OSD", timezone: "Europe/Stockholm", tags: ["jamtland", "are-ski-resort", "0-4-0-5m-passengers", "regional"] },
  { id: "evg", name: "Sveg Airport", displayName: "Sveg (EVG)", country: "SE", countryCode: "SE", category: "air", city: "Sveg", iata: "EVG", timezone: "Europe/Stockholm", tags: ["härjedalen", "subsidized", "regional", "tiny"] },
  { id: "mxx", name: "Mora/Siljan Airport", displayName: "Mora (MXX)", country: "SE", countryCode: "SE", category: "air", city: "Mora", iata: "MXX", timezone: "Europe/Stockholm", tags: ["dalarna", "zorn-museum", "inlandsbanan-south-terminus", "regional"] },
  { id: "ble", name: "Borlänge/Falun Airport (Dala Airport)", displayName: "Borlänge/Falun (BLE)", country: "SE", countryCode: "SE", category: "air", city: "Borlänge", iata: "BLE", timezone: "Europe/Stockholm", tags: ["dalarna", "regional", "kupolen-shopping"] },
  { id: "vst", name: "Västerås/Stockholm-Västerås Airport", displayName: "Västerås (VST)", country: "SE", countryCode: "SE", category: "air", city: "Västerås", iata: "VST", timezone: "Europe/Stockholm", tags: ["stockholm-secondary", "low-cost", "ryanair", "mälaren"] },
  { id: "orb", name: "Örebro Airport", displayName: "Örebro (ORB)", country: "SE", countryCode: "SE", category: "air", city: "Örebro", iata: "ORB", timezone: "Europe/Stockholm", tags: ["central-sweden", "regional", "limited"] },
  { id: "nrk", name: "Norrköping Airport (Kungsängen)", displayName: "Norrköping (NRK)", country: "SE", countryCode: "SE", category: "air", city: "Norrköping", iata: "NRK", timezone: "Europe/Stockholm", tags: ["ostergotland", "regional", "saab-adjacent"] },
  { id: "lpi", name: "Linköping/Saab Airport (Malmen)", displayName: "Linköping (LPI)", country: "SE", countryCode: "SE", category: "air", city: "Linköping", iata: "LPI", timezone: "Europe/Stockholm", tags: ["saab-aircraft", "regional", "technum"] },
  { id: "ksd", name: "Karlstad Airport", displayName: "Karlstad (KSD)", country: "SE", countryCode: "SE", category: "air", city: "Karlstad", iata: "KSD", timezone: "Europe/Stockholm", tags: ["varmland", "regional", "vattern-lake"] },
  { id: "tyf", name: "Torsby Airport (Fryklanda)", displayName: "Torsby (TYF)", country: "SE", countryCode: "SE", category: "air", city: "Torsby", iata: "TYF", timezone: "Europe/Stockholm", tags: ["varmland", "subsidized", "regional"] },
  { id: "gvx", name: "Gävle/Sandviken Airport", displayName: "Gävle (GVX)", country: "SE", countryCode: "SE", category: "air", city: "Gävle", iata: "GVX", timezone: "Europe/Stockholm", tags: ["halsingland", "regional", "stockholm-north"] },
  { id: "vby", name: "Visby Airport", displayName: "Visby (VBY)", country: "SE", countryCode: "SE", category: "air", city: "Visby", iata: "VBY", timezone: "Europe/Stockholm", tags: ["gotland-unesco", "0-4-0-5m-passengers", "seasonal-peak", "sas"] },
  { id: "agh", name: "Ängelholm-Helsingborg Airport", displayName: "Ängelholm (AGH)", country: "SE", countryCode: "SE", category: "air", city: "Ängelholm", iata: "AGH", timezone: "Europe/Stockholm", tags: ["skane-north", "regional", "båstad-tennis"] },
  { id: "had", name: "Halmstad City Airport", displayName: "Halmstad (HAD)", country: "SE", countryCode: "SE", category: "air", city: "Halmstad", iata: "HAD", timezone: "Europe/Stockholm", tags: ["halland", "regional", "limited"] },
  { id: "vxo", name: "Växjö/Småland Airport", displayName: "Växjö (VXO)", country: "SE", countryCode: "SE", category: "air", city: "Växjö", iata: "VXO", timezone: "Europe/Stockholm", tags: ["smaland", "regional", "glass-country-access"] },
  { id: "klr", name: "Kalmar/Öland Airport", displayName: "Kalmar (KLR)", country: "SE", countryCode: "SE", category: "air", city: "Kalmar", iata: "KLR", timezone: "Europe/Stockholm", tags: ["kalmar-county", "oland-bridge", "regional"] },
  { id: "rnb", name: "Ronneby Airport (Kallinge)", displayName: "Ronneby (RNB)", country: "SE", countryCode: "SE", category: "air", city: "Ronneby", iata: "RNB", timezone: "Europe/Stockholm", tags: ["blekinge", "regional", "karlshamn-adjacent"] },
  { id: "kid", name: "Kristianstad/Österlen Airport", displayName: "Kristianstad (KID)", country: "SE", countryCode: "SE", category: "air", city: "Kristianstad", iata: "KID", timezone: "Europe/Stockholm", tags: ["skane-east", "regional", "aegir-cenote"] },
  { id: "jkg", name: "Jönköping Airport (Axamo)", displayName: "Jönköping (JKG)", country: "SE", countryCode: "SE", category: "air", city: "Jönköping", iata: "JKG", timezone: "Europe/Stockholm", tags: ["smaland-capital", "regional", "vattern"] },
  { id: "thn", name: "Trollhättan-Vänersborg Airport", displayName: "Trollhättan (THN)", country: "SE", countryCode: "SE", category: "air", city: "Trollhättan", iata: "THN", timezone: "Europe/Stockholm", tags: ["volvo-era", "regional", "canal-locks"] },
  { id: "sft", name: "Skellefteå Airport", displayName: "Skellefteå (SFT)", country: "SE", countryCode: "SE", category: "air", city: "Skellefteå", iata: "SFT", timezone: "Europe/Stockholm", tags: ["north-coast", "0-2-0-25m-passengers", "data-center-city", "regional"] },
  { id: "hfs", name: "Hagfors Airport", displayName: "Hagfors (HFS)", country: "SE", countryCode: "SE", category: "air", city: "Hagfors", iata: "HFS", timezone: "Europe/Stockholm", tags: ["varmland", "subsidized", "udeholm-steel", "5k-passengers"] },

// ---------- Paste into RAIL_STATIONS (category: "rail") ----------

  { id: "stockholm-c-rail", name: "Stockholm Centralstation (Stockholm C)", displayName: "Stockholm Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Stockholm", timezone: "Europe/Stockholm", tags: ["main-hub", "sj", "arlanda-express", "metro-t-bana", "cityterminalen-bus"] },
  { id: "goteborg-c-rail", name: "Göteborg Centralstation (Göteborg C)", displayName: "Göteborg Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Göteborg", timezone: "Europe/Stockholm", tags: ["second-hub", "sj", "oslo-lines", "copenhagen-lines", "nils-ericson-bus"] },
  { id: "malmo-c-rail", name: "Malmö Centralstation (Malmö C)", displayName: "Malmö Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Malmö", timezone: "Europe/Stockholm", tags: ["oresund-bridge", "sj", "oresundstag", "copenhagen-20min", "eurostar-sthlm"] },
  { id: "malmo-triangeln-rail", name: "Malmö Triangeln (yer altı istasyonu)", displayName: "Malmö Triangeln (Underground)", country: "SE", countryCode: "SE", category: "rail", city: "Malmö", timezone: "Europe/Stockholm", tags: ["underground", "p21-train", "oresundstag", "city-center"] },
  { id: "malmo-hyllie-rail", name: "Malmö Hyllie", displayName: "Malmö Hyllie Station", country: "SE", countryCode: "SE", category: "rail", city: "Malmö", timezone: "Europe/Stockholm", tags: ["oresund-line", "malmo-arena", "oresundstag", "last-swedish-stop"] },
  { id: "lund-rail", name: "Lund Centralstation", displayName: "Lund Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Lund", timezone: "Europe/Stockholm", tags: ["university-city", "sj", "oresundstag", "krönatågen", "europe-lines"] },
  { id: "helsingborg-c-rail", name: "Helsingborg Centralstation (Knutpunkten)", displayName: "Helsingborg Central (Knutpunkten)", country: "SE", countryCode: "SE", category: "rail", city: "Helsingborg", timezone: "Europe/Stockholm", tags: ["train-ferry-bus-interchange", "sj", "oresundstag", "denmark-helsingor-ferry"] },
  { id: "kristianstad-c-rail", name: "Kristianstad Centralstation", displayName: "Kristianstad Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Kristianstad", timezone: "Europe/Stockholm", tags: ["skane-east", "sj", "regional"] },
  { id: "karlshamn-rail", name: "Karlskrona Station", displayName: "Karlskrona Station", country: "SE", countryCode: "SE", category: "rail", city: "Karlskrona", timezone: "Europe/Stockholm", tags: ["naval-city-unesco", "sj", "terminus", "stena-gdynia-port-connection"] },
  { id: "hassleholm-rail", name: "Hässleholm Centralstation", displayName: "Hässleholm Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Hässleholm", timezone: "Europe/Stockholm", tags: ["junction", "sj", "södra-stambanan", "kust-till-kust"] },
  { id: "alvesta-rail", name: "Alvesta Station", displayName: "Alvesta Station", country: "SE", countryCode: "SE", category: "rail", city: "Alvesta", timezone: "Europe/Stockholm", tags: ["junction", "södra-stambanan-kust-till-kust-split", "sj", "kronoberg"] },
  { id: "vaxjo-rail", name: "Växjö Station", displayName: "Växjö Station", country: "SE", countryCode: "SE", category: "rail", city: "Växjö", timezone: "Europe/Stockholm", tags: ["smaland-capital", "sj", "krönatågen", "kalmar-branch"] },
  { id: "kalmar-c-rail", name: "Kalmar Centralstation", displayName: "Kalmar Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Kalmar", timezone: "Europe/Stockholm", tags: ["baltic-coast", "sj", "terminus", "oland-bridge-nearby"] },
  { id: "norrkoping-c-rail", name: "Norrköping Centralstation", displayName: "Norrköping Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Norrköping", timezone: "Europe/Stockholm", tags: ["ostergotland", "sj", "södra-stambanan", "motala-ström"] },
  { id: "linkoping-c-rail", name: "Linköping Centralstation", displayName: "Linköping Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Linköping", timezone: "Europe/Stockholm", tags: ["ostergotland-capital", "sj", "södra-stambanan", "saab-city"] },
  { id: "jonkoping-c-rail", name: "Jönköping Centralstation (Resecentrum)", displayName: "Jönköping Central (Resecentrum)", country: "SE", countryCode: "SE", category: "rail", city: "Jönköping", timezone: "Europe/Stockholm", tags: ["vattern-lake", "sj", "terminus", "bus-interchange"] },
  { id: "nassjo-rail", name: "Nässjö Centralstation", displayName: "Nässjö Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Nässjö", timezone: "Europe/Stockholm", tags: ["junction", "södra-stambanan", "oskarshamn-branch", "jonkoping-line", "sj"] },
  { id: "katrineholm-rail", name: "Katrineholm Centralstation", displayName: "Katrineholm Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Katrineholm", timezone: "Europe/Stockholm", tags: ["södermanland", "sj", "vastmanland-line"] },
  { id: "hallsberg-rail", name: "Hallsberg Station", displayName: "Hallsberg Station", country: "SE", countryCode: "SE", category: "rail", city: "Hallsberg", timezone: "Europe/Stockholm", tags: ["freight-hub", "sj", "regional", "norge-vagen-line"] },
  { id: "orebro-c-rail", name: "Örebro Centralstation", displayName: "Örebro Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Örebro", timezone: "Europe/Stockholm", tags: ["central-sweden", "sj", "stockholm-oslo-corridor"] },
  { id: "karlstad-c-rail", name: "Karlstad Centralstation", displayName: "Karlstad Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Karlstad", timezone: "Europe/Stockholm", tags: ["värmland-capital", "sj", "vänern-lake", "oslo-line"] },
  { id: "vasteras-c-rail", name: "Västerås Centralstation", displayName: "Västerås Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Västerås", timezone: "Europe/Stockholm", tags: ["mälaren", "sj", "mälartåg", "stockholm-1h"] },
  { id: "eskilstuna-c-rail", name: "Eskilstuna Centralstation", displayName: "Eskilstuna Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Eskilstuna", timezone: "Europe/Stockholm", tags: ["sörmland", "sj", "mälartåg", "stockholm-line"] },
  { id: "uppsala-c-rail", name: "Uppsala Centralstation", displayName: "Uppsala Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Uppsala", timezone: "Europe/Stockholm", tags: ["university-city", "sj", "mälartåg", "stockholm-40min", "northern-lines"] },
  { id: "gavle-c-rail", name: "Gävle Centralstation", displayName: "Gävle Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Gävle", timezone: "Europe/Stockholm", tags: ["halsingland", "sj", "east-coast-line"] },
  { id: "soderhamn-rail", name: "Söderhamn Station", displayName: "Söderhamn Station", country: "SE", countryCode: "SE", category: "rail", city: "Söderhamn", timezone: "Europe/Stockholm", tags: ["halsingland-coast", "sj", "regional", "mittbanan"] },
  { id: "hudiksvall-rail", name: "Hudiksvall Station", displayName: "Hudiksvall Station", country: "SE", countryCode: "SE", category: "rail", city: "Hudiksvall", timezone: "Europe/Stockholm", tags: ["halsingland-coast", "sj", "regional"] },
  { id: "sundsvall-c-rail", name: "Sundsvall Centralstation", displayName: "Sundsvall Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Sundsvall", timezone: "Europe/Stockholm", tags: ["medelpad", "sj", "norrtåg", "mittbanan", "stockholm-3-5-4-5h"] },
  { id: "ange-rail", name: "Ånge Station", displayName: "Ånge Station", country: "SE", countryCode: "SE", category: "rail", city: "Ånge", timezone: "Europe/Stockholm", tags: ["junction", "mittbanan-ostkustbanan-split", "sj", "norrtåg"] },
  { id: "ostersund-c-rail", name: "Östersund Centralstation", displayName: "Östersund Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Östersund", timezone: "Europe/Stockholm", tags: ["jämtland-capital", "sj", "norrtåg", "mittbanan-west-terminus", "are-ski"] },
  { id: "ore-rail", name: "Öre Station", displayName: "Öre Station", country: "SE", countryCode: "SE", category: "rail", city: "Öre", timezone: "Europe/Stockholm", tags: ["are-ski-access", "mittbanan", "sj-night-train", "norrtåg", "stockholm-night-direct", "winter-peak"] },
  { id: "storlien-rail", name: "Storlien Station", displayName: "Storlien Station", country: "SE", countryCode: "SE", category: "rail", city: "Storlien", timezone: "Europe/Stockholm", tags: ["sweden-norway-border", "meråkerbanen", "trondheim-connection", "sj", "vy-tåg"] },
  { id: "ornskoldsvik-rail", name: "Örnsköldsvik Station (Örnsköldsvik/Husum yakını)", displayName: "Örnsköldsvik Station", country: "SE", countryCode: "SE", category: "rail", city: "Örnsköldsvik", timezone: "Europe/Stockholm", tags: ["high-coast", "norrtåg", "regional"] },
  { id: "umea-ostra-rail", name: "Umeå Centralstation (Umeå Östra -- yeni)", displayName: "Umeå Östra Station (New)", country: "SE", countryCode: "SE", category: "rail", city: "Umeå", timezone: "Europe/Stockholm", tags: ["vasterbotten-capital", "norrtåg", "new-station", "stambanan-north-terminus", "bridge-access"] },
  { id: "skelleftea-rail", name: "Skellefteå Station (Bureå yakını)", displayName: "Skellefteå Station", country: "SE", countryCode: "SE", category: "rail", city: "Skellefteå", timezone: "Europe/Stockholm", tags: ["north-coast", "norrtåg", "regional", "data-center-city"] },
  { id: "lulea-c-rail", name: "Luleå Centralstation", displayName: "Luleå Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Luleå", timezone: "Europe/Stockholm", tags: ["norrbotten-coast", "malmbanan-terminus", "sj", "norrtåg", "gammelstad-unesco"] },
  { id: "boden-c-rail", name: "Boden Centralstation", displayName: "Boden Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Boden", timezone: "Europe/Stockholm", tags: ["junction", "malmbanan-inlandsbanan-split", "sj", "military-fortress"] },
  { id: "gallivare-rail", name: "Gällivare Station", displayName: "Gällivare Station", country: "SE", countryCode: "SE", category: "rail", city: "Gällivare", timezone: "Europe/Stockholm", tags: ["malmbanan", "lkab-mining", "inlandsbanan-north-terminus", "sj-night-train", "norrtåg", "narvik-line"] },
  { id: "kiruna-rail", name: "Kiruna Station", displayName: "Kiruna Station", country: "SE", countryCode: "SE", category: "rail", city: "Kiruna", timezone: "Europe/Stockholm", tags: ["worlds-northernmost-railway-town", "malmbanan", "mine-subsidence-relocation", "lkab", "narvik-ore-line", "sj"] },
  { id: "abisko-rail", name: "Abisko Turiststation / Abisko Östra", displayName: "Abisko Station (Tourist/Östra)", country: "SE", countryCode: "SE", category: "rail", city: "Abisko", timezone: "Europe/Stockholm", tags: ["lapponia-unesco", "aurora-borealis", "kungsleden-trailhead", "malmbanan", "sj-night-train", "tourist-station"] },
  { id: "narvik-rail", name: "Narvik Station (Norveç -- İsveç'ten gelen hat)", displayName: "Narvik Station (Norway)", country: "SE", countryCode: "SE", category: "rail", city: "Narvik", timezone: "Europe/Oslo", tags: ["norway-terminus-swedish-line", "ore-port", "malmbanan-iron-ore", "sj-former", "scenic-fjord"] },
  { id: "borlange-rail", name: "Borlänge Station", displayName: "Borlänge Station", country: "SE", countryCode: "SE", category: "rail", city: "Borlänge", timezone: "Europe/Stockholm", tags: ["dalarna", "sj", "regional", "falun-adjacent"] },
  { id: "falun-c-rail", name: "Falun Centralstation", displayName: "Falun Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Falun", timezone: "Europe/Stockholm", tags: ["dalarna-copper-mountain-unesco", "sj", "regional"] },
  { id: "mora-rail", name: "Mora Station", displayName: "Mora Station", country: "SE", countryCode: "SE", category: "rail", city: "Mora", timezone: "Europe/Stockholm", tags: ["siljan-lake", "zorn", "inlandsbanan-south-terminus", "sj", "regional"] },
  { id: "halmstad-c-rail", name: "Halmstad Centralstation", displayName: "Halmstad Central Station", country: "SE", countryCode: "SE", category: "rail", city: "Halmstad", timezone: "Europe/Stockholm", tags: ["halland-coast", "sj", "kust-till-kust"] },
  { id: "falkenberg-rail", name: "Falkenberg Station", displayName: "Falkenberg Station", country: "SE", countryCode: "SE", category: "rail", city: "Falkenberg", timezone: "Europe/Stockholm", tags: ["halland-coast", "sj", "regional"] },
  { id: "varberg-rail", name: "Varberg Station", displayName: "Varberg Station", country: "SE", countryCode: "SE", category: "rail", city: "Varberg", timezone: "Europe/Stockholm", tags: ["halland-coast", "sj", "kust-till-kust", "ferry-grenaa-connection"] },
  { id: "kristinehamn-rail", name: "Kristinehamn Station", displayName: "Kristinehamn Station", country: "SE", countryCode: "SE", category: "rail", city: "Kristinehamn", timezone: "Europe/Stockholm", tags: ["värmland-coast", "sj", "stockholm-oslo-line"] },
  { id: "arvika-rail", name: "Arvika Station", displayName: "Arvika Station", country: "SE", countryCode: "SE", category: "rail", city: "Arvika", timezone: "Europe/Stockholm", tags: ["värmland-west", "sj", "oslo-line", "regional"] },
  { id: "charlottenberg-rail", name: "Charlottenberg Station", displayName: "Charlottenberg Station", country: "SE", countryCode: "SE", category: "rail", city: "Charlottenberg", timezone: "Europe/Stockholm", tags: ["norway-border", "sj", "oslo-stockholm-line", "shopping-village"] },
  { id: "inlandsbanan-rail", name: "Inlandsbanan (Orta Hat Demiryolu)", displayName: "Inlandsbanan (Inland Railway)", country: "SE", countryCode: "SE", category: "rail", city: "Mora", timezone: "Europe/Stockholm", tags: ["scenic-tourist-railway", "mora-ostersund-gallivare", "1300km", "summer-only-jun-aug", "tourist-pass", "reindeer-moose-bears", "inlandsbanan-ab"] },

// ---------- Paste into FERRY_PORTS (category: "sea") ----------

  { id: "stockholm-ports", name: "Stockholm Limanları (Ports of Stockholm)", displayName: "Stockholm Ports", country: "SE", countryCode: "SE", category: "sea", city: "Stockholm", timezone: "Europe/Stockholm", tags: ["capital-cruise", "finland-lines", "tallink-silja", "gotland-ferry", "archipelago"] },
  { id: "goteborg-port", name: "Göteborg Limanı (Port of Gothenburg)", displayName: "Gothenburg Port", country: "SE", countryCode: "SE", category: "sea", city: "Göteborg", timezone: "Europe/Stockholm", tags: ["largest-port", "freight-cruise", "denmark-lines", "cruise-terminal"] },
  { id: "helsingborg-port", name: "Helsingborg Limanı", displayName: "Helsingborg Port", country: "SE", countryCode: "SE", category: "sea", city: "Helsingborg", timezone: "Europe/Stockholm", tags: ["denmark-helsingor-20min", "hh-line", "eurowebia-ferry", "stena"] },
  { id: "trelleborg-port", name: "Trelleborg Limanı", displayName: "Trelleborg Port", country: "SE", countryCode: "SE", category: "sea", city: "Trelleborg", timezone: "Europe/Stockholm", tags: ["southmost-sweden", "stena-line", "ferries-del-trein-poland-germany", "ro-pax", "year-round"] },
  { id: "ystad-port", name: "Ystad Limanı", displayName: "Ystad Port", country: "SE", countryCode: "SE", category: "sea", city: "Ystad", timezone: "Europe/Stockholm", tags: ["poland-connection", "unity-line-swine", "tt-line", "bornholm-feeder", "ro-pax"] },
  { id: "malmo-port", name: "Malmö Limanı (CMP -- Copenhagen Malmö Port)", displayName: "Malmö Port (CMP)", country: "SE", countryCode: "SE", category: "sea", city: "Malmö", timezone: "Europe/Stockholm", tags: ["oresund-shared-port", "cruise", "freight", "passenger-limited"] },
  { id: "karlskrona-port", name: "Karlskrona Limanı", displayName: "Karlskrona Port", country: "SE", countryCode: "SE", category: "sea", city: "Karlskrona", timezone: "Europe/Stockholm", tags: ["unesco-naval-base", "stena-line", "gdynia-poland-nightly-10-11h", "stena-vision-spirit"] },
  { id: "karlshamn-port", name: "Karlshamn Limanı", displayName: "Karlshamn Port", country: "SE", countryCode: "SE", category: "sea", city: "Karlshamn", timezone: "Europe/Stockholm", tags: ["lithuania-connection", "dfds", "klaipeda-nightly-14-15h", "ro-pax", "blekinge"] },
  { id: "nynashamn-port", name: "Nynäshamn Limanı", displayName: "Nynäshamn Port", country: "SE", countryCode: "SE", category: "sea", city: "Nynäshamn", timezone: "Europe/Stockholm", tags: ["gotland-main-ferry", "destination-gotland", "visby-3-4h", "stockholm-south-60km", "year-round-summer-peak"] },
  { id: "oskarshamn-port", name: "Oskarshamn Limanı", displayName: "Oskarshamn Port", country: "SE", countryCode: "SE", category: "sea", city: "Oskarshamn", timezone: "Europe/Stockholm", tags: ["gotland-ferry", "visby-link", "ostergotland"] },
  { id: "vastervik-port", name: "Västervik Limanı (sinirli)", displayName: "Västervik Port (Limited)", country: "SE", countryCode: "SE", category: "sea", city: "Västervik", timezone: "Europe/Stockholm", tags: ["limited", "tjust-archipelago", "local-boats"] },
  { id: "varberg-port", name: "Varberg Limanı", displayName: "Varberg Port", country: "SE", countryCode: "SE", category: "sea", city: "Varberg", timezone: "Europe/Stockholm", tags: ["denmark-connection", "stena-line", "grenaa-4h", "2024-active-check-schedule"] },
  { id: "stromstad-port", name: "Strömstad Limanı", displayName: "Strömstad Port", country: "SE", countryCode: "SE", category: "sea", city: "Strömstad", timezone: "Europe/Stockholm", tags: ["norway-border-area", "fjord-line", "sandefjord-2-5h", "fjord-cat-summer", "koster-islands-local-ferry"] },
  { id: "umea-port", name: "Umeå Limanı -- Holmsund", displayName: "Umeå/Holmsund Port", country: "SE", countryCode: "SE", category: "sea", city: "Holmsund", timezone: "Europe/Stockholm", tags: ["bothnia-coast", "finland-lines", "kvarken-unesco", "crossings"] },
  { id: "grisslehamn-port", name: "Grisslehamn Limanı", displayName: "Grisslehamn Port", country: "SE", countryCode: "SE", category: "sea", city: "Grisslehamn", timezone: "Europe/Stockholm", tags: ["eckerö-finland", "eckerö-linjen", "2h", "shortest-sweden-aland-crossing", "year-round-2-4-daily"] },
  { id: "sundsvall-harnosand-port", name: "Sundsvall/Härnösand -- (sinirli kruvaziyer)", displayName: "Sundsvall/Härnösand (Limited Cruise)", country: "SE", countryCode: "SE", category: "sea", city: "Sundsvall", timezone: "Europe/Stockholm", tags: ["limited-cruise", "cargo-main", "bothnia-coast"] },
  { id: "lulea-port", name: "Luleå Limanı -- (kargo ağırlıklı)", displayName: "Luleå Port (Cargo-focused)", country: "SE", countryCode: "SE", category: "sea", city: "Luleå", timezone: "Europe/Stockholm", tags: ["cargo-iron-ore", "no-passenger-ferry", "rare-cruise", "bothnia-north"] },
  { id: "visby-port", name: "Visby Limanı (Gotland)", displayName: "Visby Port (Gotland)", country: "SE", countryCode: "SE", category: "sea", city: "Visby", timezone: "Europe/Stockholm", tags: ["gotland-unesco", "nynashamn-oskarshamn-ferry", "medieval-town", "cruise"] },
  { id: "ven-ferry", name: "Ven Adası Feribotu", displayName: "Ven Island Ferry", country: "SE", countryCode: "SE", category: "sea", city: "Kullen", timezone: "Europe/Stockholm", tags: ["ven-island", "laser-hoburgen-ferry", "haliseds-summer", "day-trip", "helsingborg-30min"] },
  { id: "visingo-ferry", name: "Visingsö Feribotu (Jönköping)", displayName: "Visingsö Ferry", country: "SE", countryCode: "SE", category: "sea", city: "Visingsö", timezone: "Europe/Stockholm", tags: ["vattern-lake", "kungsbacka-ferry", "car-ferry", "island-day-trip"] },

// ---------- Paste into BUS_HUBS (category: "bus") ----------

  { id: "stockholm-cityterminalen-bus", name: "Stockholm -- Cityterminalen (Klarabergsviadukten)", displayName: "Stockholm Cityterminalen", country: "SE", countryCode: "SE", category: "bus", city: "Stockholm", timezone: "Europe/Stockholm", tags: ["main-terminal", "flixbus", "nettbuss", "arlanda-coach", "oslo-copenhagen-hamburg"] },
  { id: "goteborg-nilsericson-bus", name: "Göteborg -- Nils Ericson Terminalen", displayName: "Göteborg Nils Ericson Terminal", country: "SE", countryCode: "SE", category: "bus", city: "Göteborg", timezone: "Europe/Stockholm", tags: ["main-terminal", "flixbus", "nettbuss", "oslo-copenhagen-berlin"] },
  { id: "malmo-c-bus", name: "Malmö -- Malmö Centralstation (otobüs durağı)", displayName: "Malmö Central Bus Stop", country: "SE", countryCode: "SE", category: "bus", city: "Malmö", timezone: "Europe/Stockholm", tags: ["no-separate-terminal", "station-front", "flixbus", "nettbuss", "copenhagen-45min", "skanetrafiken"] },
  { id: "uppsala-bus", name: "Uppsala -- Uppsala Centralstation (Resecentrum)", displayName: "Uppsala Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Uppsala", timezone: "Europe/Stockholm", tags: ["stockholm-70km", "flixbus", "vy", "y-buss", "northern-lines"] },
  { id: "linkoping-bus", name: "Linköping -- Resecentrum", displayName: "Linköping Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Linköping", timezone: "Europe/Stockholm", tags: ["flixbus", "vy-bus4you", "ostergotland"] },
  { id: "norrkoping-bus", name: "Norrköping -- Resecentrum", displayName: "Norrköping Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Norrköping", timezone: "Europe/Stockholm", tags: ["flixbus", "ostergotland"] },
  { id: "jonkoping-bus", name: "Jönköping -- Resecentrum", displayName: "Jönköping Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Jönköping", timezone: "Europe/Stockholm", tags: ["geographic-center-junction", "flixbus", "vy-bus4you"] },
  { id: "orebro-bus", name: "Örebro -- Resecentrum", displayName: "Örebro Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Örebro", timezone: "Europe/Stockholm", tags: ["flixbus", "oslo-line", "central-sweden"] },
  { id: "karlstad-bus", name: "Karlstad -- Resecentrum", displayName: "Karlstad Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Karlstad", timezone: "Europe/Stockholm", tags: ["värmland", "flixbus", "oslo-line"] },
  { id: "vasteras-bus", name: "Västerås -- Resecentrum", displayName: "Västerås Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Västerås", timezone: "Europe/Stockholm", tags: ["malaren", "flixbus", "stockholm-coach"] },
  { id: "sundsvall-bus", name: "Sundsvall -- Resecentrum / Navet (yeni terminal)", displayName: "Sundsvall Resecentrum/Navet", country: "SE", countryCode: "SE", category: "bus", city: "Sundsvall", timezone: "Europe/Stockholm", tags: ["new-terminal-navet", "flixbus", "y-buss", "medelpad"] },
  { id: "umea-bus", name: "Umeå -- Resecentrum / Vasaplan", displayName: "Umeå Resecentrum/Vasaplan", country: "SE", countryCode: "SE", category: "bus", city: "Umeå", timezone: "Europe/Stockholm", tags: ["vasterbotten", "flixbus", "y-buss", "northern-coach"] },
  { id: "lulea-bus", name: "Luleå -- Smedjegatan (otobüs terminali)", displayName: "Luleå Smedjegatan Terminal", country: "SE", countryCode: "SE", category: "bus", city: "Luleå", timezone: "Europe/Stockholm", tags: ["northern-terminus", "flixbus", "y-buss", "länstrafiken-norrbotten", "kiruna-haparanda"] },
  { id: "ostersund-bus", name: "Östersund -- Resecentrum (Gustav III:s Torg)", displayName: "Östersund Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Östersund", timezone: "Europe/Stockholm", tags: ["jämtland", "flixbus", "y-buss", "vy", "are-ski-peak-winter"] },
  { id: "helsingborg-bus", name: "Helsingborg -- Knutpunkten", displayName: "Helsingborg Knutpunkten", country: "SE", countryCode: "SE", category: "bus", city: "Helsingborg", timezone: "Europe/Stockholm", tags: ["train-ferry-bus-hub", "denmark-ferry-connection", "skanetrafiken"] },
  { id: "halmstad-bus", name: "Halmstad -- Resecentrum", displayName: "Halmstad Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Halmstad", timezone: "Europe/Stockholm", tags: ["halland", "flixbus", "regional"] },
  { id: "kalmar-bus", name: "Kalmar -- Resecentrum", displayName: "Kalmar Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Kalmar", timezone: "Europe/Stockholm", tags: ["baltic-coast", "regional", "oland-bridge"] },
  { id: "vaxjo-bus", name: "Växjö -- Resecentrum", displayName: "Växjö Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Växjö", timezone: "Europe/Stockholm", tags: ["smaland", "regional", "glass-country"] },
  { id: "karlshamn-bus", name: "Karlskrona -- Resecentrum", displayName: "Karlskrona Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Karlskrona", timezone: "Europe/Stockholm", tags: ["blekinge-naval-city", "regional", "ferry-connection"] },
  { id: "gavle-bus", name: "Gävle -- Resecentrum", displayName: "Gävle Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Gävle", timezone: "Europe/Stockholm", tags: ["halsingland", "flixbus", "stockholm-north"] },
  { id: "falun-bus", name: "Falun -- Resecentrum", displayName: "Falun Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Falun", timezone: "Europe/Stockholm", tags: ["dalarna", "regional", "borlange-adjacent"] },
  { id: "kiruna-bus", name: "Kiruna -- Stadshuset/Resecentrum", displayName: "Kiruna Resecentrum", country: "SE", countryCode: "SE", category: "bus", city: "Kiruna", timezone: "Europe/Stockholm", tags: ["arctic", "northern-lights", "ice-hotel", "y-buss", "regional"] },

// ============================================================
// TOPLAM: 41 air + 51 rail + 20 sea + 22 bus = 134 kayıt
// Notlar:
// - Bromma (BMA) ve Göteborg City (GSE) havalimanları KAPANDI;
//   tarihsel referans için korundu. Malmö Sturup (MMX) Skåne'nin
//   ana havalimanıdır (~30 km ötedeki Kopenhag Kastrup ile
//   yoğun rekabet).
// - Kuzeydeki küçük havalimanlarının çoğu devlet sübvansiyonlu
//   hatlarla ayakta kalır (Amapola Flyg, BRA); yaz sezonunda
//   kuzey havalimanları ve feribot hatları mevsimseldir.
// - Swebus'un FlixBus tarafından devralınmasıyla İsveç otobüs
//   pazarı FlixBus etkisine girmiştir.
// - Åland'a köprü vardır, feribot yoktur (ayrı not).
// - Inlandsbanan ~1.300 km'lik ünlü turistik tren hattıdır
//   (Mora-Östersund-Gällivare); yalnızca yazın Haziran-Ağustos
//   çalışır, turistler için "pass" satılır. Geyik, ren geyiği,
//   ayı görülebilir.
// - Rallarbanan bir demiryolu DEĞİLDİR — Malmbanan inşaatında
//   kullanılan tarihi patikadır (yürüyüş/bisiklet); kayıtlara
//   eklenmedi, bu notta anıldı.
// - Kiruna istasyonu maden çökmesi nedeniyle şehirle birlikte
//   taşınıyor; Abisko Aurora Borealis ve Kungsleden için kritik
//   duraktır.
// - Narvik (Norveç) istasyonu İsveç Malmbanan hattının son
//   durağı olduğundan bu listede yer alıyor (demir cevheri
//   limanı, fjord manzarası).
// - Yeni altyapı projeleri sürmektedir; bilgiler 2024-2025
//   itibariyle geçerlidir.
// ============================================================
