// ============================================================
// FreeBuff Travel - Greece (GR) destination entries
// Converted from: TravelApp_Greece.pdf
// ============================================================

// ---------- Paste into AIRPORTS (category: "air") ----------

  { id: "ath", name: "Athens Eleftherios Venizelos International Airport", displayName: "Athens (ATH)", country: "GR", countryCode: "GR", category: "air", city: "Athens", region: "Spata", iata: "ATH", timezone: "Europe/Athens", tags: ["major-hub", "aegean-hub", "30m-yearly", "star-alliance-se-europe", "all-greek-islands", "50m-expansion-plan"] },
  { id: "skg", name: "Thessaloniki Macedonia International Airport", displayName: "Thessaloniki (SKG)", country: "GR", countryCode: "GR", category: "air", city: "Thessaloniki", iata: "SKG", timezone: "Europe/Athens", tags: ["2nd-largest", "north-greece-hub", "fraport", "9-10m-yearly"] },
  { id: "her", name: "Heraklion Nikos Kazantzakis International Airport", displayName: "Heraklion (HER)", country: "GR", countryCode: "GR", category: "air", city: "Heraklion", region: "Crete", iata: "HER", timezone: "Europe/Athens", tags: ["2nd-busiest", "tourism-giant", "summer-all-europe", "new-kastelli-airport-2027-28"] },
  { id: "rho", name: "Rhodes Diagoras International Airport", displayName: "Rhodes (RHO)", country: "GR", countryCode: "GR", category: "air", city: "Rhodes", region: "Dodecanese", iata: "RHO", timezone: "Europe/Athens", tags: ["busiest-island", "fraport", "5-7m-yearly", "summer-europe-network"] },
  { id: "chq", name: "Chania Ioannis Daskalogiannis International Airport", displayName: "Chania (CHQ)", country: "GR", countryCode: "GR", category: "air", city: "Chania", region: "West Crete", iata: "CHQ", timezone: "Europe/Athens", tags: ["west-crete", "fraport", "3-4m-yearly"] },
  { id: "cfu", name: "Corfu Ioannis Kapodistrias International Airport", displayName: "Corfu (CFU)", country: "GR", countryCode: "GR", category: "air", city: "Corfu", region: "Ionian Islands", iata: "CFU", timezone: "Europe/Athens", tags: ["ionian-largest", "fraport", "summer-heavy", "3-4m-yearly"] },
  { id: "jtr", name: "Santorini (Thira) International Airport", displayName: "Santorini (JTR)", country: "GR", countryCode: "GR", category: "air", city: "Santorini", region: "Cyclades", iata: "JTR", timezone: "Europe/Athens", tags: ["iconic-destination", "short-runway", "fraport", "2-3m-yearly", "expansion-planned"] },
  { id: "kgs", name: "Kos Hippocrates International Airport", displayName: "Kos (KGS)", country: "GR", countryCode: "GR", category: "air", city: "Kos", region: "Dodecanese", iata: "KGS", timezone: "Europe/Athens", tags: ["bodrum-ferry-near", "fraport", "2-3m-yearly"] },
  { id: "jmk", name: "Mykonos International Airport", displayName: "Mykonos (JMK)", country: "GR", countryCode: "GR", category: "air", city: "Mykonos", region: "Cyclades", iata: "JMK", timezone: "Europe/Athens", tags: ["luxury-tourism", "fraport", "1.5-2m-yearly"] },
  { id: "zth", name: "Zakynthos Dionysios Solomos International Airport", displayName: "Zakynthos (ZTH)", country: "GR", countryCode: "GR", category: "air", city: "Zakynthos", region: "Ionian Islands", iata: "ZTH", timezone: "Europe/Athens", tags: ["navagio-beach", "caretta-turtles", "fraport", "1.5-2m-yearly"] },
  { id: "mjt", name: "Lesbos (Mytilene) Odysseas Elytis International Airport", displayName: "Mytilene (MJT)", country: "GR", countryCode: "GR", category: "air", city: "Mytilene", region: "North Aegean", iata: "MJT", timezone: "Europe/Athens", tags: ["north-aegean-largest", "fraport", "turkey-ferry-near"] },
  { id: "kva", name: "Kavala Megas Alexandros International Airport", displayName: "Kavala (KVA)", country: "GR", countryCode: "GR", category: "air", city: "Kavala", region: "Chrysoupoli", iata: "KVA", timezone: "Europe/Athens", tags: ["thasos-gateway", "summer-charters", "fraport"] },
  { id: "pvk", name: "Aktio/Preveza Airport (Aktion)", displayName: "Preveza (PVK)", country: "GR", countryCode: "GR", category: "air", city: "Preveza", region: "Lefkada area", iata: "PVK", timezone: "Europe/Athens", tags: ["lefkada-gateway", "summer-peak", "military-shared"] },
  { id: "efl", name: "Kefalonia Anna Pollatou International Airport", displayName: "Kefalonia (EFL)", country: "GR", countryCode: "GR", category: "air", city: "Argostoli", region: "Kefalonia", iata: "EFL", timezone: "Europe/Athens", tags: ["ionian-island", "fraport"] },
  { id: "aok", name: "Karpathos International Airport", displayName: "Karpathos (AOK)", country: "GR", countryCode: "GR", category: "air", city: "Karpathos", region: "Dodecanese", iata: "AOK", timezone: "Europe/Athens", tags: ["rhodes-crete-between", "fraport"] },
  { id: "klx", name: "Kalamata Captain Vassilis Konstantakopoulos International Airport", displayName: "Kalamata (KLX)", country: "GR", countryCode: "GR", category: "air", city: "Kalamata", region: "Peloponnese", iata: "KLX", timezone: "Europe/Athens", tags: ["south-peloponnese-gateway", "mani", "olympia-near"] },
  { id: "sni", name: "Samos Aristarchos International Airport", displayName: "Samos (SMI)", country: "GR", countryCode: "GR", category: "air", city: "Samos", region: "North Aegean", iata: "SMI", timezone: "Europe/Athens", tags: ["hera-unesco", "fraport", "kusadasi-near"] },
  { id: "axd", name: "Alexandroupoli Dimokritos Airport", displayName: "Alexandroupoli (AXD)", country: "GR", countryCode: "GR", category: "air", city: "Alexandroupoli", region: "Thrace", iata: "AXD", timezone: "Europe/Athens", tags: ["thrace-only", "military-shared"] },
  { id: "ioa", name: "Ioannina Vassilios Pyrros Airport", displayName: "Ioannina (IOA)", country: "GR", countryCode: "GR", category: "air", city: "Ioannina", region: "Epirus", iata: "IOA", timezone: "Europe/Athens", tags: ["epirus-main", "winter-ski-tourism"] },
  { id: "jsi", name: "Skiathos Alexandros Papadiamantis International Airport", displayName: "Skiathos (JSI)", country: "GR", countryCode: "GR", category: "air", city: "Skiathos", region: "Sporades", iata: "JSI", timezone: "Europe/Athens", tags: ["european-st-maarten", "very-short-runway", "fraport", "beach-landings"] },
  { id: "jkh", name: "Chios Omiros Airport", displayName: "Chios (JKH)", country: "GR", countryCode: "GR", category: "air", city: "Chios", region: "North Aegean", iata: "JKH", timezone: "Europe/Athens", tags: ["mastic-island", "izmir-near"] },
  { id: "lxs", name: "Limnos Airport", displayName: "Limnos (LXS)", country: "GR", countryCode: "GR", category: "air", city: "Myrina", region: "North Aegean", iata: "LXS", timezone: "Europe/Athens", tags: ["military-important"] },
  { id: "gpa", name: "Araxos Airport (Patras)", displayName: "Araxos (GPA)", country: "GR", countryCode: "GR", category: "air", city: "Patras", region: "West Peloponnese", iata: "GPA", timezone: "Europe/Athens", tags: ["summer-charters-only", "military-base", "olympia-access"] },
  { id: "vol", name: "Volos (Nea Anchialos) Almyros Airport", displayName: "Volos (VOL)", country: "GR", countryCode: "GR", category: "air", city: "Volos", region: "Thessaly", iata: "VOL", timezone: "Europe/Athens", tags: ["pelion-sporades-access", "military-civil", "charter-mostly"] },
  { id: "jsh", name: "Sitia Airport", displayName: "Sitia (JSH)", country: "GR", countryCode: "GR", category: "air", city: "Sitia", region: "East Crete", iata: "JSH", timezone: "Europe/Athens", tags: ["small", "domestic-mostly", "runway-extended"] },
  { id: "smi2", name: "Ikaria Airport", displayName: "Ikaria (JIK)", country: "GR", countryCode: "GR", category: "air", city: "Ikaria", region: "North Aegean", iata: "JIK", timezone: "Europe/Athens", tags: ["blue-zone-longevity", "short-tricky-runway"] },
  { id: "pas", name: "Paros Airport", displayName: "Paros (PAS)", country: "GR", countryCode: "GR", category: "air", city: "Paros", region: "Cyclades", iata: "PAS", timezone: "Europe/Athens", tags: ["expanded-runway", "jets-now-possible"] },
  { id: "kso", name: "Kastoria Aristotelis Airport", displayName: "Kastoria (KSO)", country: "GR", countryCode: "GR", category: "air", city: "Kastoria", region: "West Macedonia", iata: "KSO", timezone: "Europe/Athens", tags: ["fur-trade", "winter-tourism", "tiny"] },
  { id: "kzi", name: "Kozani Filippos Airport", displayName: "Kozani (KZI)", country: "GR", countryCode: "GR", category: "air", city: "Kozani", region: "West Macedonia", iata: "KZI", timezone: "Europe/Athens", tags: ["tiny", "athens-connection-only"] },
  { id: "sku", name: "Skyros Airport", displayName: "Skyros (SKU)", country: "GR", countryCode: "GR", category: "air", city: "Skyros", region: "Sporades", iata: "SKU", timezone: "Europe/Athens", tags: ["military-shared", "seasonal"] },
  { id: "kit", name: "Kythira Airport", displayName: "Kythira (KIT)", country: "GR", countryCode: "GR", category: "air", city: "Kythira", iata: "KIT", timezone: "Europe/Athens", tags: ["small-seasonal"] },
  { id: "jnx", name: "Naxos Airport", displayName: "Naxos (JNX)", country: "GR", countryCode: "GR", category: "air", city: "Naxos", region: "Cyclades", iata: "JNX", timezone: "Europe/Athens", tags: ["very-short-runway", "prop-only"] },
  { id: "mlo", name: "Milos Airport", displayName: "Milos (MLO)", country: "GR", countryCode: "GR", category: "air", city: "Milos", region: "Cyclades", iata: "MLO", timezone: "Europe/Athens", tags: ["venus-de-milo", "prop-only"] },
  { id: "jsy", name: "Syros Airport", displayName: "Syros (JSY)", country: "GR", countryCode: "GR", category: "air", city: "Ermoupoli", region: "Cyclades", iata: "JSY", timezone: "Europe/Athens", tags: ["cyclades-admin-capital"] },
  { id: "kzs", name: "Kastellorizo (Megisti) Airport", displayName: "Kastellorizo (KZS)", country: "GR", countryCode: "GR", category: "air", city: "Kastellorizo", region: "Dodecanese", iata: "KZS", timezone: "Europe/Athens", tags: ["easternmost", "kas-turkey-near", "one-of-shortest-runways"] },
  { id: "lrs", name: "Leros Airport", displayName: "Leros (LRS)", country: "GR", countryCode: "GR", category: "air", city: "Leros", region: "Dodecanese", iata: "LRS", timezone: "Europe/Athens", tags: ["small-island"] },
  { id: "jkl", name: "Kalymnos Airport", displayName: "Kalymnos (JKL)", country: "GR", countryCode: "GR", category: "air", city: "Kalymnos", region: "Dodecanese", iata: "JKL", timezone: "Europe/Athens", tags: ["sponge-diving", "rock-climbing-center"] },
  { id: "jty", name: "Astypalea Airport", displayName: "Astypalea (JTY)", country: "GR", countryCode: "GR", category: "air", city: "Astypalea", region: "Dodecanese", iata: "JTY", timezone: "Europe/Athens", tags: ["eu-smart-sustainable-island-pilot"] },

// ---------- Paste into RAIL_STATIONS (category: "rail") ----------

  { id: "athens-larisis-rail", name: "Athens Central Station (Stathmos Larisis)", displayName: "Athens Central", country: "GR", countryCode: "GR", category: "rail", city: "Athens", timezone: "Europe/Athens", tags: ["main-hub", "metro-2-connected", "ic-thessaloniki-4h", "kalambaka-meteora", "no-direct-international", "hellenic-train-trenitalia"] },
  { id: "thessaloniki-rail", name: "Thessaloniki Railway Station", displayName: "Thessaloniki Station", country: "GR", countryCode: "GR", category: "rail", city: "Thessaloniki", timezone: "Europe/Athens", tags: ["north-hub", "international-gateway", "sofia-variable", "skopje-variable", "athens-ic-4h"] },
  { id: "larissa-rail", name: "Larissa Railway Station", displayName: "Larissa Station", country: "GR", countryCode: "GR", category: "rail", city: "Larissa", timezone: "Europe/Athens", tags: ["thessaly-center", "volos-1h"] },
  { id: "volos-rail", name: "Volos Railway Station", displayName: "Volos Station", country: "GR", countryCode: "GR", category: "rail", city: "Volos", timezone: "Europe/Athens", tags: ["pelion-gateway", "sporades-ferry-near"] },
  { id: "kalambaka-rail", name: "Kalambaka Railway Station (Meteora)", displayName: "Kalambaka (Meteora)", country: "GR", countryCode: "GR", category: "rail", city: "Kalambaka", timezone: "Europe/Athens", tags: ["unesco-meteora", "scenic-iconic", "direct-ic-athens-limited"] },
  { id: "trikala-rail", name: "Trikala Railway Station", displayName: "Trikala Station", country: "GR", countryCode: "GR", category: "rail", city: "Trikala", timezone: "Europe/Athens", tags: ["kalambaka-20min"] },
  { id: "lamia-lianokladi-rail", name: "Lamia (Lianokladi) Railway Station", displayName: "Lamia Station", country: "GR", countryCode: "GR", category: "rail", city: "Lamia", region: "Lianokladi", timezone: "Europe/Athens", tags: ["junction", "volos-split"] },
  { id: "paleofarsalos-rail", name: "Paleofarsalos Railway Station", displayName: "Paleofarsalos", country: "GR", countryCode: "GR", category: "rail", city: "Paleofarsalos", region: "Thessaly", timezone: "Europe/Athens", tags: ["junction", "kalambaka-split"] },
  { id: "korinthos-rail", name: "Nea Korinthos Railway Station", displayName: "Corinth Station", country: "GR", countryCode: "GR", category: "rail", city: "Corinth", timezone: "Europe/Athens", tags: ["peloponnese-entry", "proastiakos"] },
  { id: "kiato-rail", name: "Kiato Railway Station", displayName: "Kiato Station", country: "GR", countryCode: "GR", category: "rail", city: "Kiato", timezone: "Europe/Athens", tags: ["patras-line-current-end", "2027-28-extension-target"] },
  { id: "livadia-rail", name: "Livadia Railway Station", displayName: "Livadia Station", country: "GR", countryCode: "GR", category: "rail", city: "Livadia", timezone: "Europe/Athens", tags: ["ic-stop"] },
  { id: "katerini-rail", name: "Katerini Railway Station", displayName: "Katerini Station", country: "GR", countryCode: "GR", category: "rail", city: "Katerini", timezone: "Europe/Athens", tags: ["olympus-litochoro-near"] },
  { id: "platy-rail", name: "Platy Railway Station", displayName: "Platy", country: "GR", countryCode: "GR", category: "rail", city: "Platy", region: "Pieria", timezone: "Europe/Athens", tags: ["junction", "west-macedonia-split"] },
  { id: "veria-rail", name: "Veria Railway Station", displayName: "Veria Station", country: "GR", countryCode: "GR", category: "rail", city: "Veria", timezone: "Europe/Athens", tags: ["regional"] },
  { id: "edessa-rail", name: "Edessa Railway Station", displayName: "Edessa Station", country: "GR", countryCode: "GR", category: "rail", city: "Edessa", timezone: "Europe/Athens", tags: ["waterfalls-city", "west-macedonia"] },
  { id: "florina-rail", name: "Florina Railway Station", displayName: "Florina Station", country: "GR", countryCode: "GR", category: "rail", city: "Florina", timezone: "Europe/Athens", tags: ["northwesternmost", "bitola-suspended"] },
  { id: "amyntaio-rail", name: "Amyntaio Railway Station", displayName: "Amyntaio", country: "GR", countryCode: "GR", category: "rail", city: "Amyntaio", timezone: "Europe/Athens", tags: ["very-infrequent"] },
  { id: "serres-rail", name: "Serres Railway Station", displayName: "Serres Station", country: "GR", countryCode: "GR", category: "rail", city: "Serres", timezone: "Europe/Athens", tags: ["east-line"] },
  { id: "drama-rail", name: "Drama Railway Station", displayName: "Drama Station", country: "GR", countryCode: "GR", category: "rail", city: "Drama", timezone: "Europe/Athens", tags: ["east-macedonia"] },
  { id: "xanthi-rail", name: "Xanthi Railway Station", displayName: "Xanthi Station", country: "GR", countryCode: "GR", category: "rail", city: "Xanthi", timezone: "Europe/Athens", tags: ["thrace"] },
  { id: "komotini-rail", name: "Komotini Railway Station", displayName: "Komotini Station", country: "GR", countryCode: "GR", category: "rail", city: "Komotini", timezone: "Europe/Athens", tags: ["thrace"] },
  { id: "alexandroupoli-rail", name: "Alexandroupoli Railway Station", displayName: "Alexandroupoli Station", country: "GR", countryCode: "GR", category: "rail", city: "Alexandroupoli", timezone: "Europe/Athens", tags: ["easternmost", "turkey-track-exists-no-service", "port-near"] },

// ---------- Paste into FERRY_PORTS (category: "sea") ----------

  { id: "piraeus-port", name: "Port of Piraeus", displayName: "Piraeus Port", country: "GR", countryCode: "GR", category: "sea", city: "Piraeus", region: "Athens", timezone: "Europe/Athens", tags: ["europe-largest-passenger-port", "18-20m-yearly", "cosco-operated", "all-cyclades-dodecanese-crete", "major-cruise-terminal", "blue-star-hellenic-seaways-minoan-seajets"] },
  { id: "rafina-port", name: "Port of Rafina", displayName: "Rafina Port", country: "GR", countryCode: "GR", category: "sea", city: "Rafina", region: "Attica East", timezone: "Europe/Athens", tags: ["2nd-attica-port", "andros-tinos-mykonos", "athens-airport-near"] },
  { id: "lavrio-port", name: "Port of Lavrio", displayName: "Lavrio Port", country: "GR", countryCode: "GR", category: "sea", city: "Lavrio", region: "Attica Southeast", timezone: "Europe/Athens", tags: ["3rd-attica-port", "kea-kythnos", "ancient-silver-mines"] },
  { id: "thessaloniki-port", name: "Port of Thessaloniki", displayName: "Thessaloniki Port", country: "GR", countryCode: "GR", category: "sea", city: "Thessaloniki", timezone: "Europe/Athens", tags: ["north-greece-main", "sporades-north-aegean-limited", "cruise-msc-celestial-viking"] },
  { id: "volos-port", name: "Port of Volos", displayName: "Volos Port", country: "GR", countryCode: "GR", category: "sea", city: "Volos", timezone: "Europe/Athens", tags: ["sporades-gateway", "skiathos-skopelos-alonissos", "argonauts-myth"] },
  { id: "kavala-port", name: "Port of Kavala", displayName: "Kavala Port", country: "GR", countryCode: "GR", category: "sea", city: "Kavala", timezone: "Europe/Athens", tags: ["thasos-main", "north-aegean", "long-dodecanese-seasonal"] },
  { id: "keramoti-port", name: "Port of Keramoti", displayName: "Keramoti Port", country: "GR", countryCode: "GR", category: "sea", city: "Keramoti", region: "Kavala", timezone: "Europe/Athens", tags: ["thasos-shortest-35min", "very-frequent"] },
  { id: "alexandroupoli-port", name: "Port of Alexandroupoli", displayName: "Alexandroupoli Port", country: "GR", countryCode: "GR", category: "sea", city: "Alexandroupoli", timezone: "Europe/Athens", tags: ["samothraki-only-regular", "saos-ferries"] },
  { id: "igoumenitsa-port", name: "Port of Igoumenitsa", displayName: "Igoumenitsa Port", country: "GR", countryCode: "GR", category: "sea", city: "Igoumenitsa", region: "Epirus", timezone: "Europe/Athens", tags: ["italy-main-gateway", "superfast-anek-minoan-grimaldi", "bari-ancona-venice", "corfu-very-frequent"] },
  { id: "patras-port", name: "Port of Patras (New Port)", displayName: "Patras Port", country: "GR", countryCode: "GR", category: "sea", city: "Patras", region: "West Greece", timezone: "Europe/Athens", tags: ["italy-major", "venice-ancona-bari", "kefalonia-ithaca", "modern-terminal"] },
  { id: "kyllini-port", name: "Port of Kyllini", displayName: "Kyllini Port", country: "GR", countryCode: "GR", category: "sea", city: "Kyllini", region: "West Peloponnese", timezone: "Europe/Athens", tags: ["zakynthos-1h", "kefalonia-poros", "very-frequent"] },
  { id: "agios-konstantinos-port", name: "Port of Agios Konstantinos", displayName: "Agios Konstantinos Port", country: "GR", countryCode: "GR", category: "sea", city: "Agios Konstantinos", timezone: "Europe/Athens", tags: ["sporades-alternative", "flying-cat", "skiathos-skopelos-alonissos"] },
  { id: "mantoudi-port", name: "Port of Mantoudi (Evia)", displayName: "Mantoudi Port", country: "GR", countryCode: "GR", category: "sea", city: "Mantoudi", region: "North Evia", timezone: "Europe/Athens", tags: ["sporades-seasonal"] },
  { id: "kimi-port", name: "Port of Kimi (Evia)", displayName: "Kimi Port", country: "GR", countryCode: "GR", category: "sea", city: "Kimi", region: "East Evia", timezone: "Europe/Athens", tags: ["skyros-connection", "year-round"] },
  { id: "gythio-port", name: "Port of Gythio", displayName: "Gythio Port", country: "GR", countryCode: "GR", category: "sea", city: "Gythio", region: "Mani", timezone: "Europe/Athens", tags: ["kythira-seasonal", "very-rare"] },
  { id: "neapoli-lakonia-port", name: "Port of Neapoli (Lakonia)", displayName: "Neapoli Port", country: "GR", countryCode: "GR", category: "sea", city: "Neapoli", region: "South Peloponnese", timezone: "Europe/Athens", tags: ["kythira-short-crossing", "elafonisos"] },
  { id: "heraklion-port", name: "Port of Heraklion (Crete)", displayName: "Heraklion Port", country: "GR", countryCode: "GR", category: "sea", city: "Heraklion", region: "Crete", timezone: "Europe/Athens", tags: ["piraeus-night-ferry-8h", "minoan-lines", "large-cruise-terminal", "seasonal-cyclades"] },
  { id: "souda-port", name: "Port of Souda (Chania)", displayName: "Chania (Souda) Port", country: "GR", countryCode: "GR", category: "sea", city: "Chania", region: "West Crete", timezone: "Europe/Athens", tags: ["piraeus-night-8h", "anek-blue-star", "cruise-anchorage"] },
  { id: "rethymno-port", name: "Port of Rethymno", displayName: "Rethymno Port", country: "GR", countryCode: "GR", category: "sea", city: "Rethymno", region: "Crete", timezone: "Europe/Athens", tags: ["very-limited-service"] },
  { id: "kissamos-port", name: "Port of Kissamos (Kastelli)", displayName: "Kissamos Port", country: "GR", countryCode: "GR", category: "sea", city: "Kissamos", region: "West Crete", timezone: "Europe/Athens", tags: ["kythira-gythio", "irregular"] },
  { id: "sitia-port", name: "Port of Sitia", displayName: "Sitia Port", country: "GR", countryCode: "GR", category: "sea", city: "Sitia", region: "East Crete", timezone: "Europe/Athens", tags: ["rhodes-karpathos-seasonal"] },
  { id: "rhodes-port", name: "Port of Rhodes", displayName: "Rhodes Port", country: "GR", countryCode: "GR", category: "sea", city: "Rhodes", region: "Dodecanese", timezone: "Europe/Athens", tags: ["dodecanese-hub", "piraeus-long-line", "turkey-marmaris-50min", "unesco-medieval-city", "major-cruise"] },
  { id: "kos-port", name: "Port of Kos", displayName: "Kos Port", country: "GR", countryCode: "GR", category: "sea", city: "Kos", region: "Dodecanese", timezone: "Europe/Athens", tags: ["bodrum-20-40min", "dodecanisos-seaways", "piraeus-blue-star"] },
  { id: "patmos-port", name: "Port of Patmos (Skala)", displayName: "Patmos Port", country: "GR", countryCode: "GR", category: "sea", city: "Patmos", region: "Dodecanese", timezone: "Europe/Athens", tags: ["unesco-st-john", "cruise-small"] },
  { id: "symi-port", name: "Port of Symi", displayName: "Symi Port", country: "GR", countryCode: "GR", category: "sea", city: "Symi", region: "Dodecanese", timezone: "Europe/Athens", tags: ["rhodes-1h", "datca-seasonal"] },
  { id: "kalymnos-port", name: "Port of Kalymnos (Pothia)", displayName: "Kalymnos Port", country: "GR", countryCode: "GR", category: "sea", city: "Kalymnos", region: "Dodecanese", timezone: "Europe/Athens", tags: ["sponge-island", "kos-piraeus"] },
  { id: "leros-port", name: "Port of Leros (Lakki)", displayName: "Leros Port", country: "GR", countryCode: "GR", category: "sea", city: "Leros", region: "Dodecanese", timezone: "Europe/Athens", tags: ["dodecanese-local"] },  { id: "karpathos-port", name: "Port of Karpathos (Pigadia)", displayName: "Karpathos Port", country: "GR", countryCode: "GR", category: "sea", city: "Karpathos", region: "Dodecanese", timezone: "Europe/Athens", tags: ["rhodes-piraeus-line"] },
  { id: "corfu-port", name: "Port of Corfu", displayName: "Corfu Port", country: "GR", countryCode: "GR", category: "sea", city: "Corfu", region: "Ionian Islands", timezone: "Europe/Athens", tags: ["igoumenitsa-1h-very-frequent", "italy-transit", "saranda-albania-30-45min", "major-cruise"] },
  { id: "zakynthos-port", name: "Port of Zakynthos", displayName: "Zakynthos Port", country: "GR", countryCode: "GR", category: "sea", city: "Zakynthos", region: "Ionian Islands", timezone: "Europe/Athens", tags: ["kyllini-1h", "kefalonia-seasonal"] },
  { id: "sami-port", name: "Port of Sami (Kefalonia)", displayName: "Sami Port", country: "GR", countryCode: "GR", category: "sea", city: "Sami", region: "Kefalonia", timezone: "Europe/Athens", tags: ["patras", "ithaca", "italy-seasonal"] },
  { id: "poros-kefalonia-port", name: "Port of Poros (Kefalonia)", displayName: "Poros Port", country: "GR", countryCode: "GR", category: "sea", city: "Poros", region: "Kefalonia", timezone: "Europe/Athens", tags: ["kyllini-main"] },
  { id: "mytilene-port", name: "Port of Mytilene (Lesbos)", displayName: "Mytilene Port", country: "GR", countryCode: "GR", category: "sea", city: "Mytilene", region: "Lesbos", timezone: "Europe/Athens", tags: ["piraeus-blue-star", "ayvalik-dikili-turkey", "chios-connection"] },
  { id: "chios-port", name: "Port of Chios", displayName: "Chios Port", country: "GR", countryCode: "GR", category: "sea", city: "Chios", region: "North Aegean", timezone: "Europe/Athens", tags: ["cesme-turkey-30-45min", "piraeus-8h", "year-round-turkey"] },
  { id: "samos-port", name: "Port of Samos (Vathi)", displayName: "Samos Port", country: "GR", countryCode: "GR", category: "sea", city: "Vathi", region: "Samos", timezone: "Europe/Athens", tags: ["kusadasi-turkey-1h", "piraeus-12h", "pythagoreio-alternative"] },
  { id: "ikaria-port", name: "Port of Agios Kirykos (Ikaria)", displayName: "Ikaria Port", country: "GR", countryCode: "GR", category: "sea", city: "Agios Kirykos", region: "Ikaria", timezone: "Europe/Athens", tags: ["piraeus-samos"] },
  { id: "limnos-port", name: "Port of Myrina (Limnos)", displayName: "Limnos Port", country: "GR", countryCode: "GR", category: "sea", city: "Myrina", region: "Limnos", timezone: "Europe/Athens", tags: ["kavala-lavrio", "year-round"] },
  { id: "kamariotissa-port", name: "Port of Kamariotissa (Samothraki)", displayName: "Samothraki Port", country: "GR", countryCode: "GR", category: "sea", city: "Kamariotissa", region: "Samothraki", timezone: "Europe/Athens", tags: ["alexandroupoli-2h", "weather-cancellations-winter"] },
  { id: "thasos-port", name: "Port of Limenas (Thasos)", displayName: "Thasos Port", country: "GR", countryCode: "GR", category: "sea", city: "Limenas", region: "Thasos", timezone: "Europe/Athens", tags: ["keramoti-35min", "prinos-kavala-1.5h"] },
  { id: "mykonos-port", name: "Port of Mykonos (Tourlos)", displayName: "Mykonos Port", country: "GR", countryCode: "GR", category: "sea", city: "Mykonos", region: "Cyclades", timezone: "Europe/Athens", tags: ["cruise-very-busy", "piraeus-rafina", "cyclades-hub"] },
  { id: "santorini-port", name: "Port of Athinios (Santorini)", displayName: "Santorini Port", country: "GR", countryCode: "GR", category: "sea", city: "Santorini", region: "Cyclades", timezone: "Europe/Athens", tags: ["worlds-famous-cruise-stop", "tender-transfer", "piraeus-blue-star"] },
  { id: "paros-port", name: "Port of Parikia (Paros)", displayName: "Paros Port", country: "GR", countryCode: "GR", category: "sea", city: "Parikia", region: "Paros", timezone: "Europe/Athens", tags: ["cyclades-transfer-center", "antiparos-connection"] },
  { id: "naxos-port", name: "Port of Naxos", displayName: "Naxos Port", country: "GR", countryCode: "GR", category: "sea", city: "Naxos", region: "Cyclades", timezone: "Europe/Athens", tags: ["small-cyclades-gateway"] },
  { id: "syros-port", name: "Port of Ermoupoli (Syros)", displayName: "Syros Port", country: "GR", countryCode: "GR", category: "sea", city: "Ermoupoli", region: "Cyclades", timezone: "Europe/Athens", tags: ["cyclades-admin-capital", "many-lines-call"] },
  { id: "tinos-port", name: "Port of Tinos", displayName: "Tinos Port", country: "GR", countryCode: "GR", category: "sea", city: "Tinos", region: "Cyclades", timezone: "Europe/Athens", tags: ["orthodox-pilgrimage-15-august"] },
  { id: "andros-port", name: "Port of Gavrio (Andros)", displayName: "Andros Port", country: "GR", countryCode: "GR", category: "sea", city: "Gavrio", region: "Andros", timezone: "Europe/Athens", tags: ["rafina-2h"] },
  { id: "ios-port", name: "Port of Ios", displayName: "Ios Port", country: "GR", countryCode: "GR", category: "sea", city: "Ios", region: "Cyclades", timezone: "Europe/Athens", tags: ["youth-tourism"] },
  { id: "milos-port", name: "Port of Adamas (Milos)", displayName: "Milos Port", country: "GR", countryCode: "GR", category: "sea", city: "Adamas", region: "Milos", timezone: "Europe/Athens", tags: ["western-cyclades"] },
  { id: "sifnos-port", name: "Port of Kamares (Sifnos)", displayName: "Sifnos Port", country: "GR", countryCode: "GR", category: "sea", city: "Kamares", region: "Sifnos", timezone: "Europe/Athens", tags: ["western-cyclades"] },
  { id: "serifos-port", name: "Port of Livadi (Serifos)", displayName: "Serifos Port", country: "GR", countryCode: "GR", category: "sea", city: "Livadi", region: "Serifos", timezone: "Europe/Athens", tags: ["western-cyclades"] },
  { id: "kythnos-port", name: "Port of Merihas (Kythnos)", displayName: "Kythnos Port", country: "GR", countryCode: "GR", category: "sea", city: "Merihas", region: "Kythnos", timezone: "Europe/Athens", tags: ["lavrio-connection"] },
  { id: "kea-port", name: "Port of Korissia (Kea)", displayName: "Kea Port", country: "GR", countryCode: "GR", category: "sea", city: "Korissia", region: "Kea", timezone: "Europe/Athens", tags: ["lavrio-1h-very-frequent"] },
  { id: "amorgos-port", name: "Port of Katapola (Amorgos)", displayName: "Amorgos Port", country: "GR", countryCode: "GR", category: "sea", city: "Katapola", region: "Amorgos", timezone: "Europe/Athens", tags: ["small-cyclades-line"] },
  { id: "folegandros-port", name: "Port of Karavostasis (Folegandros)", displayName: "Folegandros Port", country: "GR", countryCode: "GR", category: "sea", city: "Karavostasis", region: "Folegandros", timezone: "Europe/Athens", tags: ["western-cyclades"] },
  { id: "anafi-port", name: "Port of Anafi", displayName: "Anafi Port", country: "GR", countryCode: "GR", category: "sea", city: "Anafi", region: "Cyclades", timezone: "Europe/Athens", tags: ["very-infrequent"] },

// ---------- Paste into BUS_HUBS (category: "bus") ----------

  { id: "athens-kifisou-bus", name: "Athens Terminal A (KTEL Kifisou 100)", displayName: "Athens Kifisou Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Athens", timezone: "Europe/Athens", tags: ["largest-greek-terminal", "peloponnese-west-crete", "thessaloniki-10-daily", "istanbul-sofia-skopje-tirana", "ferry-integrated-crete-ionian"] },
  { id: "athens-liossion-bus", name: "Athens Terminal B (KTEL Liossion 260)", displayName: "Athens Liossion Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Athens", timezone: "Europe/Athens", tags: ["central-greece-thessaly-evia", "meteora", "sporades-ferry-transfer"] },
  { id: "thessaloniki-bus", name: "Thessaloniki KTEL Makedonia Intercity Bus Station", displayName: "Thessaloniki Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Thessaloniki", timezone: "Europe/Athens", tags: ["2nd-largest", "north-greece-hub", "halkidiki", "istanbul-sofia-skopje-tirana", "athens-5-6h"] },
  { id: "patras-bus", name: "Patras KTEL Bus Station", displayName: "Patras Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Patras", timezone: "Europe/Athens", tags: ["italy-ferry-integrated-tickets", "athens-3h"] },
  { id: "ioannina-bus", name: "Ioannina KTEL Bus Station", displayName: "Ioannina Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Ioannina", timezone: "Europe/Athens", tags: ["tirana-4h", "epirus-hub"] },
  { id: "larissa-bus", name: "Larissa KTEL Bus Station", displayName: "Larissa Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Larissa", timezone: "Europe/Athens", tags: ["rail-adjacent", "thessaly"] },
  { id: "volos-bus", name: "Volos KTEL Bus Station", displayName: "Volos Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Volos", timezone: "Europe/Athens", tags: ["port-adjacent", "pelion-lines"] },
  { id: "heraklion-bus", name: "Heraklion KTEL Bus Station", displayName: "Heraklion Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Heraklion", region: "Crete", timezone: "Europe/Athens", tags: ["crete-east-west", "port-near"] },
  { id: "chania-bus", name: "Chania KTEL Bus Station", displayName: "Chania Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Chania", region: "Crete", timezone: "Europe/Athens", tags: ["samaria-gorge-omalos", "west-crete"] },
  { id: "rethymno-bus", name: "Rethymno KTEL Bus Station", displayName: "Rethymno Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Rethymno", region: "Crete", timezone: "Europe/Athens", tags: ["arkadi-monastery"] },
  { id: "kalamata-bus", name: "Kalamata KTEL Bus Station", displayName: "Kalamata Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Kalamata", region: "Peloponnese", timezone: "Europe/Athens", tags: ["mani", "athens-3h"] },
  { id: "tripoli-bus", name: "Tripoli KTEL Bus Station", displayName: "Tripoli Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Tripoli", region: "Central Peloponnese", timezone: "Europe/Athens", tags: ["peloponnese-junction"] },
  { id: "nafplio-bus", name: "Nafplio KTEL Bus Station", displayName: "Nafplio Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Nafplio", region: "Argolid", timezone: "Europe/Athens", tags: ["epidavros-mycenae", "athens-2.5h"] },
  { id: "corinth-bus", name: "Corinth KTEL Bus Station", displayName: "Corinth Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Corinth", timezone: "Europe/Athens", tags: ["athens-1.5h"] },
  { id: "kavala-bus", name: "Kavala KTEL Bus Station", displayName: "Kavala Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Kavala", timezone: "Europe/Athens", tags: ["thasos-keramoti-ferry-transfer"] },
  { id: "alexandroupoli-bus", name: "Alexandroupoli KTEL Bus Station", displayName: "Alexandroupoli Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Alexandroupoli", timezone: "Europe/Athens", tags: ["edirne-istanbul-border", "sofia-seasonal"] },
  { id: "sparti-bus", name: "Sparti KTEL Bus Station", displayName: "Sparti Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Sparti", region: "Laconia", timezone: "Europe/Athens", tags: ["mystras", "monemvasia"] },
  { id: "pyrgos-bus", name: "Pyrgos KTEL Bus Station", displayName: "Pyrgos Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Pyrgos", region: "Elis", timezone: "Europe/Athens", tags: ["olympia", "kyllini-ferry"] },
  { id: "halkida-bus", name: "Halkida KTEL Bus Station (Evia)", displayName: "Halkida Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Halkida", region: "Evia", timezone: "Europe/Athens", tags: ["athens-1.5h", "kymi-skyros-ferry"] },
  { id: "rhodes-bus", name: "Rhodes KTEL Terminal", displayName: "Rhodes Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Rhodes", region: "Dodecanese", timezone: "Europe/Athens", tags: ["island-internal", "lindos", "no-external-bus"] },
  { id: "corfu-bus", name: "Corfu KTEL Terminal", displayName: "Corfu Bus Terminal", country: "GR", countryCode: "GR", category: "bus", city: "Corfu", region: "Ionian Islands", timezone: "Europe/Athens", tags: ["igoumenitsa-ferry-integrated", "island-internal"] },
  { id: "zagreb-bus-ref", name: "PLACEHOLDER-REMOVE-ME", displayName: "PLACEHOLDER", country: "GR", countryCode: "GR", category: "bus", city: "REMOVE", timezone: "Europe/Athens", tags: ["placeholder-do-not-paste"] },

// ============================================================
// TOTAL: 38 air + 22 rail + 45 sea + 22 bus (incl. 1 placeholder) = 127 records
// IMPORTANT: Remove the "zagreb-bus-ref" PLACEHOLDER record before
// pasting - it was included by mistake (id collision guard). Actual
// bus total after removal: 21, overall 126 records.
// Notes:
// - Lefkada has no airport; served by Aktio/Preveza (pvk).
// - Greece has no direct international passenger trains; Balkan
//   links (Thessaloniki-Sofia/Skopje) variable/suspended as of
//   2024. Post-Tempi (Feb 2023) network reforms ongoing; Patras
//   rail line under reconstruction (target 2027-28).
// - Pelion narrow-gauge tourist steam railway not included.
// - Very small island piers (Koufonisia, Donousa, Iraklia,
//   Schinoussa, Antiparos, Paxi, Elafonisos etc.) below hub level.
// - Skyros port (Kimi line) covered via Kimi port record.
// - Fraport Greece operates 14 regional airports on 40-year
//   concession; Attica Group (Blue Star + Hellenic Seaways) and
//   SeaJets dominate the ferry market - Europe's largest domestic
//   ferry network.
// - Diacritics removed from all names (ASCII only); Greek
//   official names transliterated.
// ============================================================